### ISSUE TITLE
Floating Target Health Bar Cutoff

### ISSUE THREAD

**Issue by Alamei** [CriticalFlaw/FlawHUD#1]
It appears that the UI element for the floating version of target health bars is slightly too small for its contents, causing the numbers to be clipped off on the right edge. You can see a basic example here: 
[FlawHUD - Floating Health Bar Cutoff](http://i.imgur.com/4VJVJbM.jpg)

**Comment by CriticalFlaw** [comment]
It's been fixed and will be included in the next update [http://puu.sh/q8Q6V/5a4e55e764.jpg](url)

**Comment by Alamei** [comment]
Excellent; thanks for the quick patch.
