### ISSUE TITLE
Health cross cut off 

### ISSUE THREAD

**Issue by Scoutman01** [CriticalFlaw/flawhud#101]
the health cross option doesn't display properly 
![20200808203815_1](https://user-images.githubusercontent.com/50184129/89717496-71d13500-d9b7-11ea-8aee-c361f321f8b2.jpg)

**Comment by Scoutman01** [comment]
also i don't have the bg for the spectatorguihealth did you disable it ?
![20200808205629_1](https://user-images.githubusercontent.com/50184129/89717758-c07fce80-d9b9-11ea-9851-5e5a9359caa9.jpg)

**Comment by CriticalFlaw** [comment]
Yes, I've changed it to color the health value itself because in other places it got cutoff and looked very odd. I'll correct the health cross in the first screenshot later tonight. Thank you for reporting it

**Comment by CriticalFlaw** [comment]
Fixed. Please redownload FlawHUD through the installer or on GitHub (not huds.tf). Thank you for reporting it.
