### ISSUE TITLE
Server Time is misplaced

### ISSUE THREAD

**Issue by qwedas** [CriticalFlaw/flawhud#105]
Before it would be right below the round time.
This is 4:3 1024x768 stretched to 16:9 1920x1080

![Screenshot from 2020-08-23 21-44-54](https://user-images.githubusercontent.com/32962637/90996293-52780180-e58c-11ea-9429-9ac47d0c6aa4.png)

The HUD version I was using previously was on  https://github.com/CriticalFlaw/FlawHUD/commit/955a4998dc19f9f27be109f9b3b0812aab46fe78 which didn't exhibit the same issue.

_How it looked before. Ignore the demo UI_
![82579312-9c031b80-9b5b-11ea-9edd-91ad9c68eab1](https://user-images.githubusercontent.com/32962637/90996719-97506800-e58d-11ea-8c09-aee5327b9229.png)

**Comment by CriticalFlaw** [comment]
Fixed. I intended to remove the server time when using the match HUD because 1. it can be viewed on the scoreboard and 2. it creates too much empty space between it and the match status (setup, overtime etc.) so it's only visible when the match hud is disabled.

**Comment by qwedas** [comment]
Is there anyway for me to bring it back? I play a ton of competitive 6vs6 and the server timer is useful for counting ubercharges as medic. Having to press tab to check the server time is a bit inconvenient.
