### ISSUE TITLE
Demoman Charges Overlapping

### ISSUE THREAD

**Issue by Scoutman01** [CriticalFlaw/flawhud#106]
the shield charge meter overlap with the loose cannon charge meter

**Comment by CriticalFlaw** [comment]
Done. Please download the latest version off GitHub.

**Comment by impale1** [comment]
they don't overlap, but I think they're too close together
![440_20231006160828_1](https://github.com/CriticalFlaw/flawhud/assets/117596825/1056589d-b2ac-4c68-9ad2-c9f25ddd758e)
