### ISSUE TITLE
Pazer wants to give more $$$ but doesn't know where (add .github/FUNDING.yml)

### ISSUE THREAD

**Issue by PazerOP** [CriticalFlaw/flawhud#108]
what am i gonna do with all these $1 bills, i gotta get rid of them

https://docs.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository

**Comment by CriticalFlaw** [comment]
Done. Now please give me more money 🤑 💰

**Comment by PazerOP** [comment]
wow !

**Comment by CriticalFlaw** [comment]
closing until more money is deposited
