### ISSUE TITLE
Multiple player status effects get cut off

### ISSUE THREAD

**Issue by Scoutman01** [CriticalFlaw/flawhud#109]
When you have 3 differents status the second one is cut in half and the third one can't be seen

![20200828193500_1](https://user-images.githubusercontent.com/50184129/91599833-321ebd00-e967-11ea-8a3d-a99d2f9184be.jpg)

**Comment by CriticalFlaw** [comment]
Here's the updated version. Spaced out the health buff, first status icon and damage values so it looks less cluttered.

![image](https://user-images.githubusercontent.com/6818236/93277163-9dea8d80-f78f-11ea-9705-7eb2fdf94112.png)
