### ISSUE TITLE
incorrect respawn counter

### ISSUE THREAD

**Issue by h9lk** [CriticalFlaw/flawhud#110]
still didn't understand how it should be displayed correctly

![20200829130725_1](https://user-images.githubusercontent.com/32390006/91634632-65f6f280-e9fa-11ea-8aa5-f25ad00b0cf2.jpg)

![20200812154737_1](https://user-images.githubusercontent.com/32390006/91634634-67281f80-e9fa-11ea-948b-551250d73813.jpg)

**Comment by CriticalFlaw** [comment]
Yeah, I don't think this is a bug nor what is the intended respawn timer for those player panels. So I'd just leave it as is
