### ISSUE TITLE
Smaller Spy Disguise Outline

### ISSUE THREAD

**Issue by ghost** [CriticalFlaw/flawhud#112]
Enhancement for those who want the Spy disguise but don't want it to cover up the screen like me.

**Comment by CriticalFlaw** [comment]
It looks like the Spy Disguise Outline is hardcoded so I can't reposition or downscale it. Closing this story because it cannot be addressed. Sorry about that.

**Comment by Scoutman01** [comment]
You can,

go to scripts and hudanimations_custom.txt, HudSpyDisguiseChanged section:

event HudSpyDisguiseChanged
{
	Animate PlayerStatusSpyOutlineImage		Alpha		"200"			Linear 0.0 0.2
	
	Animate PlayerStatusSpyOutlineImage		Position	"c-400 c-0"		Linear 0.0 0.2
	Animate PlayerStatusSpyOutlineImage		Size		"200 200"		Linear 0.0 0.2

	RunEvent HudSpyDisguiseHide	0.7
}

looks like this : https://imgur.com/a/JSaabAZ

**Comment by CriticalFlaw** [comment]
Did not think to try that, thanks @Scoutman01! Here's what it will look like now.

![20200916091128_1](https://user-images.githubusercontent.com/6818236/93342092-e8eeba00-f7fc-11ea-849a-8e01001169d1.jpg)
