### ISSUE TITLE
Item effect meters and weapon ammo disappears randomly

### ISSUE THREAD

**Issue by ghost** [CriticalFlaw/flawhud#114]
For some reason, the item effect meters and the ammo count for my weapon disappears randomly. Using the latest version.

**Comment by CriticalFlaw** [comment]
That's a known game bug. Unfortunately, it can't be fixed with HUD files.

**Comment by Scoutman01** [comment]
i think you need to inspect someone by pressing f in order to fix it

**Comment by ghost** [comment]
> That's a known game bug. Unfortunately, it can't be fixed with HUD files.

Oh thought it was with this hud.

> i think you need to inspect someone by pressing f in order to fix it

Yes that worked.
