### ISSUE TITLE
DamageAccountValue cut off

### ISSUE THREAD

**Issue by Scoutman01** [CriticalFlaw/flawhud#117]
heal 114 hp with the crossbow:
![Sans titre 1](https://user-images.githubusercontent.com/50184129/93396048-517a7d00-f877-11ea-881c-bccc66c62ac3.png)
do 65 damage with the ubersaw:
![Sans titre 2](https://user-images.githubusercontent.com/50184129/93396052-52abaa00-f877-11ea-9856-60b48ec721ea.png)

**Comment by CriticalFlaw** [comment]
Fixed. Thank you for reporting.
