### ISSUE TITLE
Halloween Mode Bugs

### ISSUE THREAD

**Issue by Scoutman01** [CriticalFlaw/flawhud#118]
the hudbosshealth overlap with the truce message
![Sans titre 1](https://user-images.githubusercontent.com/50184129/93399570-23e50200-f87e-11ea-9664-0f7445b960a5.png)
ctf halloween has the stock look, you need to change HudMiniGame_Base.res (tested on pl_rumble_event with bots)
![Sans titre 2](https://user-images.githubusercontent.com/50184129/93399753-7d4d3100-f87e-11ea-87c5-ad0b7e7a8896.png)
if 10 people and more push the cart, the numbers cut off
![Sans titre 3](https://user-images.githubusercontent.com/50184129/93399927-dddc6e00-f87e-11ea-8d2d-1ea399e6aa69.png)
on the winpanel, winning capture overlap with the top score blu player
![Sans titre 4](https://user-images.githubusercontent.com/50184129/93400098-4b889a00-f87f-11ea-9850-c10d55d36312.png)
the PoisonTimeLabel and the PoisonIcon overlap with the CarriedImage (but i think you did it on purpose)
![Sans titre 5](https://user-images.githubusercontent.com/50184129/93400362-ec775500-f87f-11ea-9883-5659727db5c7.png)![Sans titre 6](https://user-images.githubusercontent.com/50184129/93400365-eda88200-f87f-11ea-80d6-433acc311dd3.png)

**Comment by CriticalFlaw** [comment]
Which map are the second and last screenshots from?

**Comment by Scoutman01** [comment]
pl_rumble_event (Gravestone)
ctf_hellfire (when you cap the intel)

**Comment by CriticalFlaw** [comment]
Thanks. I'm just fixing that last issue right now. Here's what the updated kart minigame UI looks like
![image](https://user-images.githubusercontent.com/6818236/93404389-13219580-f858-11ea-8102-5df792727bb7.png)

**Comment by CriticalFlaw** [comment]
All the bugs listed here have now been fixed. Thank you for reporting.
