### ISSUE TITLE
Add High-resolution Class Images

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/flawhud#120]
https://www.teamfortress.tv/52291/high-res-class-select-images

**Comment by Scoutman01** [comment]
stock are better

**Comment by CriticalFlaw** [comment]
Those images are intended to work only on the Items screen, replacing the class emblems that flawhud currently uses which I will not be doing. If they would have been used to replace the 2D class images on the main game UI then I would have considered it.
