### ISSUE TITLE
Can't Close Item Drop Screen

### ISSUE THREAD

**Issue by scarface52** [CriticalFlaw/flawhud#123]
It doesn't happen consistently but when it does happen I can't click two bottom buttons and delete button. Upper ones work just fine. Hovering over them doesn't change the color of the button. When this happens mid game I can close it by pressing esc but it reappears every time I die. If it happens in main menu game soft locks and doesn't even let me search for a game and forces me to close the game.
![tf2](https://user-images.githubusercontent.com/71343424/94741519-e81d6280-037c-11eb-9bd8-e41f798af5e7.png)

**Comment by CriticalFlaw** [comment]
It's a known bug. Something to do with the game layering this behind something it shouldn't. You can get past it by pressing Enter.

**Comment by scarface52** [comment]
Okay thanks for the info.
