### ISSUE TITLE
Own Name not listed in "Mute Players" pop-up box

### ISSUE THREAD

**Issue by Mister36MN** [CriticalFlaw/flawhud#126]
It seems that when looking in the "Mute Players" Menu, your own name is not listed. Normally this would be totally fine, however in the case of selecting all players in a server to mute with Shift+Click (Sometimes you just gotta do it), it does seem to also select your name. 

As of yet, I have not been able to find a way to un-mute myself, even by selecting all players and unmuting. (muting myself in this case means I cannot see my own chat, but it still goes through).

This is a relatively minor issue but thought I would bring it to your attention.

This is on 2020.1001, but also initially occurred on a version a couple months older (before I updated to that, my own name was visible in the list)

**Comment by CriticalFlaw** [comment]
Valve recently changed the Mute Player list which [FlawHUD was updated to use](https://github.com/CriticalFlaw/FlawHUD/commit/f40748d7f9e29d935164c29b370f3322a5669273#diff-bb28e140415359f4d88187036b79ba45). If this is an issues you're experiencing with the default HUD then you should open an issue on Valve's issue tracker so they can fix it; 

https://github.com/ValveSoftware/Source-1-Games/issues

**Comment by Mister36MN** [comment]
Thank you, I will submit an issue in that github. I forgot they had changed that entire menu.

Issue here: https://github.com/ValveSoftware/Source-1-Games/issues/3396

**Comment by CriticalFlaw** [comment]
Thank you. Because there's nothing I can do and it's in their hands I'll be closing this issue.
