### ISSUE TITLE
Winpanel details label and avatar image freeze panel

### ISSUE THREAD

**Issue by Scoutman01** [CriticalFlaw/flawhud#127]
just a suggestion, make the details label to appear on the win panel and change the ypos to 130 :
![20201011133722_1](https://user-images.githubusercontent.com/50184129/95685763-22e38e00-0bfa-11eb-817c-0984e622c5ea.jpg)
in freezepanel_basic, change avatar image xpos to 45, wide to 14 and wide_minmode to 0 :
![Sans titre 1](https://user-images.githubusercontent.com/50184129/95686259-ff6e1280-0bfc-11eb-8293-b923733adf9f.png)

**Comment by CriticalFlaw** [comment]
I'd like there to be more of a gap between the details label and the killstreak player, perhaps 135 - just move the win panel up a bit more. For the freezepanel the avatar should be the same height as the black background. 

If you'd like to make those changes you're welcome to do so.

**Comment by CriticalFlaw** [comment]
Added in https://github.com/CriticalFlaw/FlawHUD/commit/cfa84c839d94875e5c30a2c1d0f421fe4809dfad by @Scoutman01
