### ISSUE TITLE
On 4:3 monitors when entering the mode selection the bottom isn't greyed.

### ISSUE THREAD

**Issue by nathanielcwm** [CriticalFlaw/flawhud#129]
![image](https://user-images.githubusercontent.com/22572406/95842705-716b6680-0d79-11eb-96fe-ce01a37ca17b.png)

Also applies when streamer mode is off. I won't send a screenshot because there's a ton to censor if it's off lol.

**Comment by CriticalFlaw** [comment]
Unfortunately, Valve hardcoded that grey area to not stretch across the screen and there's no way to change it.

**Comment by nathanielcwm** [comment]
rip
