### ISSUE TITLE
Support for some modifications

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/flawhud#131]
Hey. I would like to know if there is any possibility of adding any of the modifications below into FlawHUD.

1. [Menu Character Overhaul [WIP]](https://gamebanana.com/wips/52424)
2. [Loadout Backgrounds](https://gamebanana.com/guis/29307)
3. [Making the Loadout screen look like this](https://screenshots.gamebanana.com/img/ss/guis/5ce30c7dde6ae.jpg)
4. [MvM | Remove "toggle ready" Blinking/Pulsing](https://gamebanana.com/guis/36036)
5. [TF2 - Another Closed Captions Project!](https://gamebanana.com/guis/35712)
6. [Moby Francke Class Icons](https://gamebanana.com/guis/35900)
7. [Open Fortress Class Icons](https://gamebanana.com/guis/35878)
8. [smiley class portraits](https://gamebanana.com/guis/35820)
9. [Team Fortress 2 Classic Class Portraits](https://gamebanana.com/guis/33607)
10. [Discovery [Background]](https://gamebanana.com/guis/35647)
11. [Looping Sunset Menu Background](https://gamebanana.com/guis/35281)
12. [A Custom Main Menu Character Pack](https://gamebanana.com/guis/34815)
13. [Adroto's class portraits [icons]](https://gamebanana.com/guis/32918)
14. [Retro's Class Portraits](https://gamebanana.com/guis/34563)
15. [Old Portraits Remake](https://gamebanana.com/guis/34393)
16. [HD Main Menu Graphics](https://gamebanana.com/guis/33282)
17. [ToonHUD's Team-Colored Hitmarker](https://gamebanana.com/guis/33902)

**Comment by CriticalFlaw** [comment]
- **1, 12, 16** - Images like that would bloat FlawHUD's ~2.5MB file size. They're nice but users can install these themselves.
- **2, 10, 11** - All go against FlawHUD's dark theme. Loadout background only looks good on that page and not the rest.
- **3, 7, 9** - Could be considered if they are not used by another HUD, file size is not too big and the mod creator gives permission.
- **4** - Can be implemented in the next update.
- **5** - FlawHUD already uses modified closed captions intended for competitive. I could see if there's a change that can be made so this mod does not cause a crash without redesigning how captions currently look though.
- **6, 8, 13, 14, 15** - Of those I only liked moby and smiley, so I'll see if they look good in-game before considering.
- **17** - Could be added, will consider it.

**Comment by Tiagoquix** [comment]
> * **1, 12, 16** - Images like that would bloat FlawHUD's ~2.5MB file size. They're nice but users can install these themselves.
> * **2, 10, 11** - All go against FlawHUD's dark theme. Loadout background only looks good on that page and not the rest.

Alright.

> * **3, 7, 9** - Could be considered if they are not used by another HUD, file size is not too big and the mod creator gives permission.

Cool. I think that the [number 9](https://www.youtube.com/watch?v=A6g0mPo-uJM) is the best between the three.

> * **4** - Can be implemented in the next update.

Cool too.

> * **5** - FlawHUD already uses modified closed captions intended for competitive. I could see if there's a change that can be made so this mod does not cause a crash without redesigning how captions currently look though.

The mod is good but I changed my opinion and now I don't think that it should be included into FlawHUD. It is more user preference, and like you said, the focus is to have competitive captions, and not all in-game captions.

> * **6, 8, 13, 14, 15** - Of those I only liked moby and smiley, so I'll see if they look good in-game before considering.

In my opinion, [this](https://gamebanana.com/guis/32918) is the best of all class portraits.

> * **17** - Could be added, will consider it.

Alright.
