### ISSUE TITLE
Friends list and names won't appear.

### ISSUE THREAD

**Issue by qhacim** [CriticalFlaw/flawhud#135]
I switched from flawhud to funkehud but then switched back, and now flawhud won't show my friends list, leaderboard, kill feed names, or any names for that matter.

**Comment by CriticalFlaw** [comment]
That's because you have Streamer Mode enabled (it should say so on the bottom right corner of the main menu), to switch off it either turn off minmode or press the button on the right hand side of the main menu, right under the Refresh HUD button.

**Comment by qhacim** [comment]
Thanks man.
