### ISSUE TITLE
Mode Selection menu is cutoff in 4:3 resolution

### ISSUE THREAD

**Issue by ghost** [CriticalFlaw/flawhud#138]
4:3 1024x768
![image](https://user-images.githubusercontent.com/34733116/101205622-bc3f8700-3622-11eb-9208-f51a69eb2a5c.png)

**Comment by CriticalFlaw** [comment]
Don't think there's a way to fix this, because I can't scale the buttons to be smaller when in a lower resolution.

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/CriticalFlaw/FlawHUD/commit/498135ff73c1a72203e2fd82c7e4d493d5361437

The Create Server and Training Mode buttons were moved to the icon tray above the Friends List and the mode selection icons were shifted to be better positioned in 4:3 and 16:9 resolution.
