### ISSUE TITLE
Colors not working 

### ISSUE THREAD

**Issue by pooter90000** [CriticalFlaw/flawhud#141]
When I open the FlawHUD Installer and I try to change the HUD colors and click apply changes, there's a popup saying "An error occurred while applying the color settings. Sequence contains no elements". This might be entirely my fault, I might be doing it wrong, but I'm just pointing it out in case it is a problem.

**Comment by CriticalFlaw** [comment]
Make sure you're on the latest installer version (v1.9) and just to be safe, do a clean installation of flawhud (make sure it's removed from `tf/custom`) this error usually means that the installer got a different result from the one expected.

**Comment by CriticalFlaw** [comment]
Closing due to lack of response from the reporting user.
