### ISSUE TITLE
Players not being listed, empty kill feeds

### ISSUE THREAD

**Issue by Flavio11113** [CriticalFlaw/flawhud#142]
Hi,

I really like your HUD. Just got the problem that players are not being listed in TAB and kill feed contains no names.
Any solutions for this?

Video attached.
https://www.youtube.com/watch?v=Y8fft9fjk68

**Comment by CriticalFlaw** [comment]
You have streamer mode enabled (says on the bottom right corner of the main menu). To disable it, you'll need to toggle off minmode in game or your config if that's where it is set.

**Comment by Flavio11113** [comment]
Oh, yeah that was the problem. It was enabled by default. 

Thanks 👍
