### ISSUE TITLE
Modifying the main menu

### ISSUE THREAD

**Issue by inoblit** [CriticalFlaw/flawhud#146]
I'm really new to anything around mod/huds but I would like to know if it's possible to change the menu title that says "team fortress 2" in you hud, also how can I make the character portraits on the menu visible again ? I am using an older version of the HUD where it is stuck to the inferno update, I've looked into the files but I only managed to change the background and not the title or the character portraits. Thanks for the thelp !

**Comment by CriticalFlaw** [comment]
If you want the Team Fortress 2 title and character images you can copy `TFLogoImage` and `TFCharacterImage` from the latest version and paste it into yours. https://github.com/CriticalFlaw/flawhud/blob/master/resource/ui/mainmenuoverride.res#L191
