### ISSUE TITLE
Add an Options Panel

### ISSUE THREAD

**Issue by CriticalFlaw** [CriticalFlaw/flawhud#147]
Some HUDs use the MOTD panel for displaying HUD options that the user can select. Could be worth looking into and trying out.

- Refresh HUD
- Closed Captions
- Sound Fix
- Invisible Players Fix
- Display Netgraph
- Display Chat
- Streamer Mode

**Comment by Tiagoquix** [comment]
Some users use `cl_disablehtmlmotd 1`, and I think it would just disable this possible HUD feature.

For this reason, I think you shouldn't implement this feature.

**Comment by CriticalFlaw** [comment]
`cl_disablehtmlmotd` is only for the HTML MOTD pages seen when joining a server, or when a server has an ad like Skial. This command does not disable the MOTD panel on the main menu, so every user can still access it.

**Comment by CriticalFlaw** [comment]
Added in 0deb0a74c37d8a646bfb5b7938943e12815fa959
