### ISSUE TITLE
Add Customization Options

### ISSUE THREAD

**Issue by CriticalFlaw** [CriticalFlaw/flawhud#153]
There are some ideas that I would like to implement but wouldn't want to force other users to use, unless they chose to. The new editor allows for these customizations to be quickly implemented, so it's a good opportunity to add some new ones to flawhud. 

Below are some customizations (some admittedly copied from others) that I'd like to try:

- [x] Full width Ubercharge meter. (35ae0682c409e1f7d9a6844e04249f42a8b186f5)
- [x] Full screen scoreboard. (6d223016b6ae2ca989cc5272d2664c4cee0bbb60)
- [x] TF2 team panels for health and ammo. (f280850241be1c4de9824ce15238a6e463151e17)
- [x] Health and ammo in corners. (f280850241be1c4de9824ce15238a6e463151e17)
- [x] Alternate Class/Team selection pages. (d1a9edf3b53b9ea2a9a84e3e99036ff3e7a1fd8f, 7db913104e93b3d1f6075e6a9c6ac02d7c685daa)

Fixed bugs:
- Console button tooltip using incorrect text. (c8d43b9a1b2ae38af02da069efc93cfbe6dbd1cf)
- Corrected the position of the notification alert and panel. (99c83dee9f944fd50fe49d31b3c02ffd17924ecd)
- Corrected animation for colored health and ammo. (0db8e77be533cb4f4d8fc32f0f313370906806d8)

**Comment by NotTsunami** [comment]
Are 35ae0682c409e1f7d9a6844e04249f42a8b186f5, f280850241be1c4de9824ce15238a6e463151e17, d1a9edf3b53b9ea2a9a84e3e99036ff3e7a1fd8f and 7db913104e93b3d1f6075e6a9c6ac02d7c685daa intentionally excluded from master? These changes are present in the edit branch, and not on master branch. It would be cool to see these as a customization.

**Comment by CriticalFlaw** [comment]
Yes. I was not satisfied with how they turned out so I'll keep them in the edit branch and refine until I'm happy with the end result.

Since they'll be customization options they'll be easy to implement once ready

**Comment by NotTsunami** [comment]
> Yes. I was not satisfied with how they turned out so I'll keep them in the edit branch and refine until I'm happy with the end result.
> 
> Since they'll be customization options they'll be easy to implement once ready

Sounds good, look forward to it. Thanks for the response!
