### ISSUE TITLE
resource/ui/huditemeffectmeter_action.res

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/flawhud#154]
Shouldn't it be

```
#base "huditemeffectmeter.res"

"Resource/UI/huditemeffectmeter_action.res"
```

instead of just

```
#base "huditemeffectmetter.res
```

?

**Comment by CriticalFlaw** [comment]
No. The file is not used for anything and is only there to prevent the game from putting out an error in the console. The game code looks for huditemeffectmeter_action but doesn't actually use it for anything. There's no point in adding a #base

**Comment by Tiagoquix** [comment]
> There's no point in adding a #base

So why does this file have one?

**Comment by Tiagoquix** [comment]
Shouldn't it be empty instead?

**Comment by CriticalFlaw** [comment]
My bad I was mistaken. We actually need the #base to inherit ItemEffectMeter for the console error to go away. We don't need to include `"Resource/UI/huditemeffectmeter_action.res"` in the file to appease the game.
