### ISSUE TITLE
Player's medals are not being positioned correcly

### ISSUE THREAD

**Issue by huupoke** [CriticalFlaw/flawhud#159]
The medals on the scoreboard is not being positioned correctly, and some medals are missing.
The bug doesn't happen on the previous releases.
I'm using 1600x900 resolution, playing on Arch Linux.

**Screenshot**
![Screenshot_2021-05-31_21-43-57](https://user-images.githubusercontent.com/16283764/120210106-9acdf980-c259-11eb-9a1e-0908d154a3d9.png)

**Comment by CriticalFlaw** [comment]
This has already been reported and fixed here: https://github.com/CriticalFlaw/flawhud/issues/156

Please redownload the latest version off GitHub, huds.tf or using the editor. Thanks!
