### ISSUE TITLE
Outdated description in huds.tf

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/flawhud#164]
"Streamer Mode
If you're streaming on Twitch/YouTube and need extra protection against stream snipers and DDoS attacks, then you can toggle Streamer Mode by clicking on the Incognito button on the right hand side of the main menu."

The Incognito button has been removed.

https://huds.tf/site/s-FlawHUD

**Comment by Tiagoquix** [comment]
Also, I think the HUD's `README.md` should be updated to mention the new HUD options panel and the customizations folder.

**Comment by CriticalFlaw** [comment]
Updated the Streamer Mode description on huds.tf. Thanks!

The README has become too bloated. Will need to look into moving some of that information elsewhere or simplify the text. But we won't need a ticket for that, I'll look into it later.
