### ISSUE TITLE
resource/ui/huditemeffectmeter_cleaver.res in FlawHUD

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/flawhud#165]
Shouldn't it have a line like [this](https://github.com/SteamDatabase/GameTracking-TF2/blob/master/tf/tf2_misc_dir/resource/ui/huditemeffectmeter_cleaver.res#L58)?

FlawHUD's file: https://github.com/CriticalFlaw/flawhud/blob/master/resource/ui/huditemeffectmeter_cleaver.res

**Comment by CriticalFlaw** [comment]
It's not necessary as the game knows to use the Cleaver label when it is equipped.

![20210604233032_1](https://user-images.githubusercontent.com/6818236/120878822-eb609200-c58c-11eb-9c1f-9aef8dabed5b.jpg)
