### ISSUE TITLE
Intersecting HUS elements 4:3 (part 3) 

### ISSUE THREAD

**Issue by h9lk** [CriticalFlaw/flawhud#167]
decided test ur hud after updates, first thing noticed 1024x768 - incorrect display of rank and names of friends are overlaid on avatar 
![20210605110207_1](https://user-images.githubusercontent.com/32390006/120885375-3e6c3080-c5f1-11eb-8486-7f2022cf65cb.jpg)

second thing that found out regularity of appearance such squares on pl maps. Tried reload hud and option to fix visual problems, but it did not help
![20210605110542_1](https://user-images.githubusercontent.com/32390006/120885502-09aca900-c5f2-11eb-893e-0f8c58725d17.jpg)

also layering medic statistics with any item bar status 
![20210605111217_1](https://user-images.githubusercontent.com/32390006/120885627-96576700-c5f2-11eb-8e94-159946bbf61d.jpg)

traditionally unclear where menu 
![20210605110253_1](https://user-images.githubusercontent.com/32390006/120885680-cef74080-c5f2-11eb-941d-443736efacf6.jpg)

and also problem  found only in streamer mod, display of weapons only changes when streamer mod is turned off 
![20210605112020_1](https://user-images.githubusercontent.com/32390006/120885728-1087eb80-c5f3-11eb-9aec-f90abfa617d6.jpg)

With best wishes <3

**Comment by CriticalFlaw** [comment]
Looks like your HUD installation got completely booked. Could you please clear out of/custom and downloaded a fresh copy?

**Comment by h9lk** [comment]
> 
> 
> Looks like your HUD installation got completely booked. Could you please clear out of/custom and downloaded a fresh copy?

did not think that hud in release is so different from version github, ok, will try to find again
