### ISSUE TITLE
Missing mannpower supernova powerup charge meter

### ISSUE THREAD

**Issue by Scoutman01** [CriticalFlaw/flawhud#168]
In any mannpower map when you pick the supernova powerup :
![Mannpower_Mode_Powerup_Supernova_Icon](https://user-images.githubusercontent.com/50184129/121188033-fe16e780-c868-11eb-893e-db5fe9f4a9c3.png)
you have a charge meter controlled by : hudpowerupeffectmeter.res
![20210608144802_1](https://user-images.githubusercontent.com/50184129/121188180-256db480-c869-11eb-816a-c80603cb6493.jpg)

**Comment by CriticalFlaw** [comment]
Fixed in 0deb950070c38f219543ecd576aabf51c8801d19. Thank you for reporting!

![20210608222842_1](https://user-images.githubusercontent.com/6818236/121283421-10187a80-c8a9-11eb-8c8c-75ab98ab57e3.jpg)
