### ISSUE TITLE
Home Server is not up to date

### ISSUE THREAD

**Issue by ghost** [CriticalFlaw/flawhud#170]
Noticed I couldn't join the home server due to it being outdated, probably because of the Summer Update, so just thought I'd let u know! ( I did uninstall and reinstall the hud to make sure it wasn't me by the by lol )
![frownie face](https://user-images.githubusercontent.com/73834086/124026948-28ab1a80-d9a7-11eb-8342-f002875c6a99.png)

**Comment by CriticalFlaw** [comment]
It's pointing to my server, which isn't being actively maintained. I'll update it right now, but users are typically advised to set their own home server in `flawhud/resource/gamemenu.res`.

**Comment by CriticalFlaw** [comment]
Server has been updated. Thank you.

**Comment by ghost** [comment]
Ohh, makes sense. Sorry for the confusion lol
