### ISSUE TITLE
Add an option/customization to hide sponsors of the main menu

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/flawhud#171]
https://www.reddit.com/r/tf2/comments/oa35ry/i_use_flawhud_as_my_custom_hud_for_tf2_i_recently/

**Comment by CriticalFlaw** [comment]
It has already been moved to the Stats page as of the latest version.

https://twitter.com/CriticalFlaw_/status/1409369119862951938?s=19
