### ISSUE TITLE
Missing badges of the players in the bottom of the scoreboard

### ISSUE THREAD

**Issue by huupoke** [CriticalFlaw/flawhud#174]
The bottom players of each team won't have their medals shown on the scoreboard.
I'm using 1600x900 monitor with 1600x900 resolution. It seems to be clipped off in this resolution, because when I opened the screenshot in the image editor, the bottom player's profile picture is only 30x28, while the other players' are 30x30.
FlawHUD v2021.0628

![Screenshot_2021-07-20_22-08-43](https://user-images.githubusercontent.com/16283764/126352220-0ad04029-8a06-4a77-bad7-2f18de521738.png)

**Comment by CriticalFlaw** [comment]
This has been fixed in the latest version v2021.0727 (3a6db939a167941c244b4e64ea5c4995d0d79017). Thank you for reporting this!
![20210727204832_1](https://user-images.githubusercontent.com/6818236/127256567-f277c0e4-c8ee-4ec4-9c49-003d877ae2eb.jpg)
