### ISSUE TITLE
Unable to select a class on the Class Selection screen.

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/flawhud#175]
Sometimes I can't select a class using the mouse cursor. It just happens sometimes. Weird.

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/CriticalFlaw/flawhud/commit/5d08e1892b9f54406de30b61800d50beb6bb03fe

![image](https://user-images.githubusercontent.com/6818236/130333136-782bb302-31ce-4f89-bb3c-2f1de872d085.png)
