### ISSUE TITLE
Full Screen MOTD Button in HUD options

### ISSUE THREAD

**Issue by AgentArtemis** [CriticalFlaw/flawhud#180]
A feature request I would really like is a button to enable or disable full screen MOTD's in the HUD options.

A lot of communities (Such as Creators.TF) use the MOTD, being able to full screen it would be very convenient. 

![image](https://user-images.githubusercontent.com/71758866/130322376-dcd8a754-6887-4bde-83de-02a31ae488ce.png)

**Comment by CriticalFlaw** [comment]
This has already been requested in https://github.com/CriticalFlaw/flawhud/issues/176 and will be addressed in the next update.

**Comment by AgentArtemis** [comment]
Whoops didn't see that. Thank you.

**Comment by CriticalFlaw** [comment]
@AgentAlibi The MOTD and map info pages have been updated in 4ffa827c9b863496a5a0c9794dc3903346e82697
