### ISSUE TITLE
Floating health is out of place

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/flawhud#181]
![Screenshot_1](https://user-images.githubusercontent.com/30274161/130387111-b3514abf-ec65-455e-bbfd-6f3e78e78427.png)
![Screenshot_2](https://user-images.githubusercontent.com/30274161/130387116-bc8c9d05-2cfa-48f8-b276-50f0499ef3bc.png)
![Screenshot_3](https://user-images.githubusercontent.com/30274161/130387117-1c7f6592-2dda-44c2-b72d-ec8fd1588142.png)

**Comment by CriticalFlaw** [comment]
Fixed in 8063a82509833820be765948886b3bbc0c985c0c
