### ISSUE TITLE
What is the purpose of the null.wav file?

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/flawhud#184]
https://github.com/CriticalFlaw/flawhud/commit/b9b0f73889bc91c7b771b79ae48dbb2e0d41d774

**Comment by CriticalFlaw** [comment]
To suppress a console error that looks for that file.

Also, in the future - please ask questions in the support Discord server: https://discord.gg/hTdtK9vBhE
This issue tracker is meant for suggestions, bug reports or troubleshooting help.

**Comment by Tiagoquix** [comment]
I don't think a HUD should mess with this, but that's okay.
