### ISSUE TITLE
Remove RED/BLU view option in Loadout screen

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/flawhud#192]
Reasons to remove it:

- Does not work while connected to a server, since it requires `sv_cheats 1`.
- Botkillers do not work properly when viewing with the BLU skin.
- Skins do not change their colors.
- Team colored items (like items with the Team Spirit paint) do not change their color.

Screenshots comparing the normal versus the bugged version:

**Normal (Spy) - Weapon Skin**
![image](https://user-images.githubusercontent.com/30274161/137876526-31a3ab09-e8f9-4129-90ea-89e49fb03074.png)

**Bugged (Spy) - Weapon Skin**
![image](https://user-images.githubusercontent.com/30274161/137876453-35c2d2eb-574a-4312-9bae-8d5f82059fc7.png)

**Normal (Sniper) - Team Spirit paint**
![image](https://user-images.githubusercontent.com/30274161/137876649-13025702-74c4-457b-90e2-c6f6f4b00bc9.png)

**Bugged (Sniper) - Team Spirit paint**
![image](https://user-images.githubusercontent.com/30274161/137876690-ff7b0101-3c3c-4775-a7d4-f89d4ece5da8.png)

**Normal (Pyro) - Botkiller**
![image](https://user-images.githubusercontent.com/30274161/137876769-f0ed3514-d0de-41c1-ade4-8df1e033da28.png)

**Bugged (Pyro) - Botkiller**
![image](https://user-images.githubusercontent.com/30274161/137876811-baacfb15-432a-4386-8190-dea2fcd8ade9.png)

**Comment by CriticalFlaw** [comment]
I understand that this feature is buggy, but it's also very popular with the user base. But if that changes and enough people request it to be removed for the reasons you've given then I'll remove them.

**Comment by CriticalFlaw** [comment]
Closing due to lack of response in support of removing this feature. Will reopen for discussion if that changes.
