### ISSUE TITLE
Uneven low/overheal boxes

### ISSUE THREAD

**Issue by Silexos** [CriticalFlaw/flawhud#193]
I apologize since this is likely the most nitpicky bug I've found yet, but the two boxes indicating health and ammo aren't quite the same value. I remember editing it to be correct before but I unfortunately forgot what .res file I edited when swapping over to the most recent version.

![uneven_boxes](https://user-images.githubusercontent.com/85089160/138616077-0b0930cd-3e83-4342-9d6e-de998875b43a.jpg)

**Comment by CriticalFlaw** [comment]
This should fix the issue. Could you verify it, please? https://github.com/CriticalFlaw/flawhud/commit/8dd6f63a5704c85833242ba8645aba5a05d30519

**Comment by Silexos** [comment]
Alrighty it's even now, thank you so much!

**Comment by Silexos** [comment]
Heya I reopened the issue because the right box is now off center from the numerical values for ammo.

![offcentered](https://user-images.githubusercontent.com/85089160/138621925-55b253e8-c74b-4ac3-a0fb-c3ba1afe7eeb.jpg)

**Comment by CriticalFlaw** [comment]
The value of AmmoNoClip just needs to be extended then, hang on.

**Comment by CriticalFlaw** [comment]
Done. Should be good to go

**Comment by Silexos** [comment]
The boxes are all good! An interesting thing I found when testing the fix was that the shadows for weapons without reserve ammo are now to the left of the numerical value rather than the right. It should be noted that any weapon with reserve ammo works just fine.

![20211024191907_1](https://user-images.githubusercontent.com/85089160/138625267-7fa57944-c2f2-412a-b56f-c74e8dbf015b.jpg)

![20211024192035_1](https://user-images.githubusercontent.com/85089160/138625268-a966b7c0-997b-4659-8050-716e73ebdd24.jpg)

![20211024192045_1](https://user-images.githubusercontent.com/85089160/138625269-042f205f-6979-4e64-9803-b84f41c3a20c.jpg)

**Comment by CriticalFlaw** [comment]
That's my bad. I forgot to change the width of the shadow as well to fix the bigger box. Fixed now.

**Comment by Silexos** [comment]
Alrighty everything's working. Again thank you so much for the help!
