### ISSUE TITLE
Request: Menu Color Schemes

### ISSUE THREAD

**Issue by Silexos** [CriticalFlaw/flawhud#194]
I was wondering if potentially the option to change primary colors in the menus could be added to the hud editor at some point. By this I mean changing the color accent from the dark green found in various parts of the menus (i.e. class loadouts and the motd menu) to something like orange or purple.

**Comment by CriticalFlaw** [comment]
Those can be changed in `flawhud/resource/ui/scheme/clientscheme_colors.res` as most of the reused colors are defined there. Thing is that I didn't make flawhud with one color theme in mind (like rayshud has cyan), so while I could offer the option - it may not be clear to some users as so its intended purpose.
