### ISSUE TITLE
Adjust coaching interface

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/flawhud#196]
![image](https://user-images.githubusercontent.com/30274161/138906140-63b7edfc-b1e3-44ae-84ef-e466c0ed1342.png)

The interface is good as it is now, but could you please adjust the health so it appears below the student's profile picture?
Thanks.

**Comment by Tiagoquix** [comment]
Also, is there a way to remove the default crosshair from this interface?

**Comment by CriticalFlaw** [comment]
I hadn't even thought to check this interface in a long time. Looks like a simple enough change though.

> Also, is there a way to remove the default crosshair from this interface?

You have to disable that in the game options.

**Comment by Tiagoquix** [comment]
Yes but, I mean, I am not using a custom HUD crosshair. I am using a cyan dot, which is `cl_crosshair_file crosshair3` from the game itself. Even so, the default crosshair (`cl_crosshair_file default`) still appears together with my personal crosshair.

https://www.reddit.com/r/tf2scripthelp/wiki/crosshairs/

I think this might be hard-coded into the game itself, or maybe a change in some .res file could solve this.

**Comment by CriticalFlaw** [comment]
> Yes but, I mean, I am not using a custom HUD crosshair. I am using a cyan dot, which is `cl_crosshair_file crosshair3` from the game itself. Even so, the default crosshair (`cl_crosshair_file default`) still appears together with my personal crosshair.
> 
> https://www.reddit.com/r/tf2scripthelp/wiki/crosshairs/
> 
> I think this might be hard-coded into the game itself, or maybe a change in some .res file could solve this.

I know what you meant. If the options menu didn't work for you then you can try putting `cl_crosshair_scale 0` into console.

![image](https://user-images.githubusercontent.com/6818236/138975645-f37df3d9-472b-4aaf-a810-2f01749041a6.png)

**Comment by Tiagoquix** [comment]
All crosshair commands would control my personal cyan dot crosshair, and not the coaching crosshair itself.

I found this file: [Resource/UI/SpectatorCoach.res](https://pastebin.com/raw/KSbFii2T)

I can't test it now, but I think that if we set "visible" and "enabled" to 0 in "Crosshair" the problem would be solved.
Also, "HealthPositioning" should be what we are looking for.

**Comment by CriticalFlaw** [comment]
Fixed in ba096461864001917ccca12ecb78e59c8e9a6889
