### ISSUE TITLE
Engineer stuff icons weird

### ISSUE THREAD

**Issue by DimitriDR** [CriticalFlaw/flawhud#199]
Hello,

I have some kind of glitch with the v2021.1202. A picture will be more telling.

![Capture d’écran 2021-12-04 190107](https://user-images.githubusercontent.com/56969769/144719780-c1a3833c-35b9-4ef8-8986-995bb8a68443.png)

Thank you!

**Comment by CriticalFlaw** [comment]
Does `hud_reloadscheme` fix the problem?

**Comment by DimitriDR** [comment]
It did add something but definitely not what I expected.

![Capture d’écran 2021-12-05 115221](https://user-images.githubusercontent.com/56969769/144743561-27b000f5-cfe0-4ebf-b49c-14565d8b9457.png)

I saw an error in the console too (before doing the command, so idk):

```
'engineer.cfg' not present; not executing.
--- Missing Vgui material vgui/..\vgui\maps\menu_thumb_Missing
--- Missing Vgui material vgui/..\vgui\maps\menu_thumb_Missing
--- Missing Vgui material vgui/..\vgui\maps\menu_thumb_Missing
```

**Comment by CriticalFlaw** [comment]
Those console errors are unrelated. Could you post your `flawhud/resource/UI/hud_obj_sentrtgun.res` file here, please?

**Comment by DimitriDR** [comment]
> Those console errors are unrelated. Could you post your `flawhud/resource/UI/hud_obj_sentrtgun.res` file here, please?

Can't transfer via GH. Link: https://we.tl/t-PjOZl4DRSF

**Comment by CriticalFlaw** [comment]
Found the issue. The version uploaded to huds.tf had an in-development version of that file which wasn't meant to be released. I've reuploaded the correct version to huds.tf so you should not have a problem if you reinstall. Apologies for the inconvenience.

**Comment by DimitriDR** [comment]
Yeap, it works perfectly! I close the issue as the problem is solved 😄
