### ISSUE TITLE
MvM Wave Icons/Progress Bar Overlap 

### ISSUE THREAD

**Issue by Alamei** [CriticalFlaw/FlawHUD#2]
There's a minor bug in the MvM HUD resources causing the icons listing the bots in the active wave to overlap partially with the wave progress bar:
[FlawHUD - MvM Wave Icon/Progress Bar Overlap](http://i.imgur.com/v0R9Ogz.jpg)

**Comment by CriticalFlaw** [comment]
It's fixed now, thanks for reporting it!
