### ISSUE TITLE
Community Server List Font

### ISSUE THREAD

**Issue by Silexos** [CriticalFlaw/flawhud#200]
Heya found this small bug(?) with the latest release. The font in the community server list is the TF2 secondary font rather than the traditional one found in other Valve games. This happens even when the hud is customized for Code Pro fonts (as seen in the screenshot).

![20211211165416_1](https://user-images.githubusercontent.com/85089160/145696531-b2997190-54b4-4e8d-a5c8-a78e7a3ef4de.jpg)

After a bit more messing around the font also appears in the console and the server connect box. Likely the regular options menu as well but I haven't tested it.

**Comment by CriticalFlaw** [comment]
As part of f7fd21fdc118aa45744ea36c1a4f1dba34444cc9 I decided to remove the Source Font change. Two main reasons:

1. It would be difficult for me to offer multiple variants to match Code Pro.
2. After using it for a few days, it's been hard to see for me and few other people who have complained to me about it.
