### ISSUE TITLE
Loadout class icons not rendering properly on linux

### ISSUE THREAD

**Issue by pikasalt** [CriticalFlaw/flawhud#202]
Class icons on the loadout screen use the incorrect icons when used on linux. Behavior works fine when the game is ran under proton/wine.
![20211217212842_1](https://user-images.githubusercontent.com/52518103/146627511-7a1e688b-7b30-42b9-a800-4413bd0f3fce.jpg)

**Comment by CriticalFlaw** [comment]
Check that you don't have a font of the same name installed on Linux. Font issues like these are usually caused by a conflict.

**Comment by pikasalt** [comment]
I don't have the font installed, so that seems to complicate things here. Is there anything else that I could provide to help diagnose this issue?

**Comment by CriticalFlaw** [comment]
Maybe installing the font 😁

**Comment by pikasalt** [comment]
Tried installing the font, but the problem still persists :disappointed:

**Comment by pikasalt** [comment]
What file is responsible is responsible for the this panel? I'm thinking this could be related to a formatting error like #16, where some things failed to load based on capitalization.

**Comment by CriticalFlaw** [comment]
Try changing the names of fonts in `flawhud/resource/UI/fonts` to lowercase then make sure the font references in `flawhud/resource/UI/scheme/clientscheme_icons.res` and fonts.res to also lowercase. The font references will be found at the bottom of the file.

**Comment by pikasalt** [comment]
Still no dice. What's weird about this is that every other icon is working except those on the class loadout panel. Also trying to figure out why the icons work for pyro, heavy, and spy but not the other classes.

**Comment by CriticalFlaw** [comment]
In the `flawhud/resource/fonts/TF2Icons.ttf` file the class icons occupy characters 1-9, I've moved them around to see if that makes a difference. The change is in a separate branch so if you or anyone with a similar setup could test it and check if it works, that'd be great.

https://github.com/CriticalFlaw/flawhud/tree/%23202

**Comment by CriticalFlaw** [comment]
Closing due to lack of response.
