### ISSUE TITLE
Comp. Ready-Up Covers Players

### ISSUE THREAD

**Issue by Silexos** [CriticalFlaw/flawhud#204]
The comp mode ready-up menu covers up the player list at the top of the screen. The prompt to change the team name is still in the old spot however prior to the bug.

Old:
![20211211183551_1](https://user-images.githubusercontent.com/85089160/148712733-3fb5a746-83a3-4bc0-a9bc-ef98b81bacc5.jpg)

Current: 
![20211218173957_1](https://user-images.githubusercontent.com/85089160/148712742-efb95d54-14d9-4a3e-8847-9a2e81dc3541.jpg)

![20211218175108_1](https://user-images.githubusercontent.com/85089160/148712745-6af1ef9c-5f2b-47d6-b4c1-dce89c471b76.jpg)

**Comment by CriticalFlaw** [comment]
Fixed in ee7b2e4bc2ec852d7bd9fb02890bf7d95f45386d. Also cleaned up the file and repinned all the elements so it's easier to maintain in the future. Thank you for reporting this.
