### ISSUE TITLE
Health value cutoff when using specific editor options.

### ISSUE THREAD

**Issue by shaiico** [CriticalFlaw/flawhud#207]
![Current Build](https://i.imgur.com/UbjGnHP.png)

**Comment by CriticalFlaw** [comment]
Is this happening on the vanilla version or a version modified via the editor? If so, which setting do you have selected?

**Comment by shaiico** [comment]
> Is this happening on the vanilla version or a version modified via the editor? If so, which setting do you have selected?

Modified via the editor. May be worth mentioning that I have no other mods/configs of any kind.

![Custom](https://i.imgur.com/KEwjL5N.png)

**Comment by CriticalFlaw** [comment]
I have not been able to reproduce this issue with the editor and the options shown. Could be a file conflict or caused by manually updating files. Does it work if you reinstall flawhud via the editor and reapply all the options?

**Comment by CriticalFlaw** [comment]
Closing due to lack of response and not being able to reproduce the issue.
