### ISSUE TITLE
Kill Feed Killstreak number

### ISSUE THREAD

**Issue by Shivansh-yadav13** [CriticalFlaw/flawhud#210]
it doesn't look good

![Inkedcopy Screenshot (37)_LI](https://user-images.githubusercontent.com/87603425/152696569-ff1462a8-308e-4224-aac8-e061d2c97ef7.jpg)

is this bcoz of the font?
do we have font options I have installed it recently btw.

**Comment by CriticalFlaw** [comment]
This is because the font is so thin and there's no allocated spacing between it and the arrow. Unfortunately there's no option in the .res files to create the separation so this issue cannot be fixed.
