### ISSUE TITLE
--- Missing Vgui material vgui/..\vgui\maps\menu_thumb_Missing

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/flawhud#212]
This error still appears on the console, even with the fix implemented by the HUD.

**Comment by Tiagoquix** [comment]
Maybe you should implement a .VTF file too?

[And, I don't know, but in the .VMT file it points out to a file inside replay/thumbnails.](https://raw.githubusercontent.com/CriticalFlaw/flawhud/master/materials/vgui/maps/menu_thumb_Missing.vmt)

`"$baseTexture" "vgui/replay/thumbnails/menu_thumb_Missing"`

 That could be the problem.

**Comment by CriticalFlaw** [comment]
Have you tested this to confirm that it fixes the problem?

**Comment by Tiagoquix** [comment]
No, I just tried to deduce what the root of the problem is. I will test and post results later.

**Comment by Tiagoquix** [comment]
I tested by removing the menu_thumb_Missing.vtf from the replay/thumbnails folder and then adding an empty menu_thumb_Missing.vtf in vgui/maps, and also replacing the $baseTexture with the corresponding folder/place, but no success either. I think the problem is with the TF2 code itself, since the console logs: "Missing Vgui material vgui/..\vgui\maps\menu_thumb_Missing", so the code must be pointing to "vgui/..\vgui\maps", which is a non existent folder.

I think the best way to solve this is just to left the error there and remove the fix from the HUD.

**Comment by CriticalFlaw** [comment]
Agreed. No point in keeping it if it does not address the issue. Good to let valve know about it or see if team comtress has this fixed

**Comment by CriticalFlaw** [comment]
Removed in ce71df051e9073956cad823a5ea7548219091eb9
