### ISSUE TITLE
Closed captions not being properly shown

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/flawhud#219]
Tested the last update and here are the results: https://imgur.com/a/dxvz52z

A severe amount of strings in PT-BR got even worse, because since the "wide" has been increased to a very large value in hudlayout.res, the strings basically try to fit into a single line, but they fail.

Interestingly enough, even in English I found a collision error: https://i.imgur.com/yv25Hyp.png

FYI, I'm using the 1366x768 resolution and Code Pro fonts.

By the way, I also found it weird that the Closed Captions don't have a border like before, implying that they are infinite even after the screen space runs out.

I propose two solutions:

The first is for you to go back as the HUD was in the commit https://github.com/CriticalFlaw/flawhud/pull/217/commits/e289a171da2bb1bd6f2747eb21d75c1de93f3776 (it's ok to keep the current ypos). As can be seen in [this comment](https://github.com/CriticalFlaw/flawhud/pull/217#issuecomment-1050369578), the issue had been fully fixed ("This edit also fixed an issue where some strings were being cut off and not displaying all the text and/or were splitting incorrectly.").

The second is that I shorten the strings to keep the meaning, but make the length closer to English. Maybe they end up getting slightly bad, but I can try. I will certainly use a lot of abbreviations.

**Comment by Tiagoquix** [comment]
The third solution would be a nuke option: delete the PT-BR translations of the Closed Captions and just keep the English ones, but it would be kind of sad to do that.

**Comment by CriticalFlaw** [comment]
Updated in 613b40e9a85d90db8d434fc28fbf301214fc8884
