### ISSUE TITLE
Broken localization text.

### ISSUE THREAD

**Issue by YellowInkling** [CriticalFlaw/flawhud#221]
Hi I'm noticed that most of the text is broken in this hud.
![image](https://user-images.githubusercontent.com/74347915/158470726-46f47836-2223-4d04-b689-787f633a556f.png)
![image](https://user-images.githubusercontent.com/74347915/158470750-9faab5b1-91d1-4431-bd58-861a4be04264.png)
![image](https://user-images.githubusercontent.com/74347915/158470783-f34c51ec-c2b4-4b72-99aa-5ee68d90c39a.png)

**Comment by CriticalFlaw** [comment]
Is this happening on a clean install with the latest version from GitHub?

Also, are you trying to play the game in English or some other language?

**Comment by YellowInkling** [comment]
> Is this happening on a clean install with the latest version from GitHub?

I installed it using the TF2 Hud editor
 
> Also, are you trying to play the game in English or some other language?

And I am trying to play the game in English

**Comment by CriticalFlaw** [comment]
Try clicking **Uninstall** in the editor, then **Install** again. I've added some language files in d855fe193d430b734e232a55a6b726434920f410 so hopefully the issue is resolved.

**Comment by YellowInkling** [comment]
I tried that as well as downloading it from Github but it still didn't work

**Comment by CriticalFlaw** [comment]
Odd. What other mods do you have in your tf/custom folder?

**Comment by YellowInkling** [comment]
Mastercomfig and Hitsounds. I tried the hud without the mods but that still didn't work

**Comment by CriticalFlaw** [comment]
Is there a chat_english.txt file in `tf/custom/flawhud/resource`?

**Comment by YellowInkling** [comment]
Yes

**Comment by CriticalFlaw** [comment]
Not sure what else to suggest. It's working fine on my side.

Any suggestions @Tiagoquix ?

**Comment by Tiagoquix** [comment]
> Not sure what else to suggest. It's working fine on my side.
> 
> Any suggestions @Tiagoquix ?

He/she is probably using another mod that modifies the chat_english.txt file.

**Comment by Tiagoquix** [comment]
It works fine on my side too. The problem is something in his/her game.

**Comment by Tiagoquix** [comment]
@YellowInkling Try this: https://help.steampowered.com/en/faqs/view/0C48-FCBD-DA71-93EB

**Comment by CriticalFlaw** [comment]
Hmm try removing all other mods and test again. Though you did say you only have mastercomfig and hitsounds
