### ISSUE TITLE
Backpack strings in Brazilian Portuguese

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/flawhud#223]
Could you slightly increase the size so that the string "Show stock items" ("Exibir itens padrão") doesn't get cut off?

Also, could you slightly increase the size so that the string "Show Marketable Borders Only" ("Bordas em itens comercializáveis") doesn't get cut off?

Don't worry about the first string "Sem bordas da cor [...]" being cut off, as it will change whenever TF2 updates the localization files.

I'm requesting these changes for my language, but they may turn out to be useful for other languages as well. I recommend that you use the default HUD sizes as a reference to be able to make the necessary adjustments.

![image](https://user-images.githubusercontent.com/30274161/162334957-e5b1aa35-0a41-4f21-908e-6da17ede8f4e.png)

**Comment by CriticalFlaw** [comment]
Expanding the dropdowns to accommodate Brazilian would mean I have to then expand it further for other languages, which is impractical and would require redesigning the page further. I think most users will still be able to read the text even if truncated, much like how it is in Russian in a lot of parts throughout the hud.

The checkbox already uses the most of its allotted space, width wise. I thought about using `wrap 1` but then the text will be misaligned.
