### ISSUE TITLE
Crosshair issues

### ISSUE THREAD

**Issue by Green318** [CriticalFlaw/flawhud#224]
I am using your hud editor and it would stay as a small "+" no matter what i did.  could you help me fix this issue please

**Comment by Tiagoquix** [comment]
https://github.com/CriticalFlaw/flawhud#crosshair

**Comment by CriticalFlaw** [comment]
Make sure you're using the latest version of the editor and flawhud as there may be an incompatability issue. If that doesn't work, try to manually set the crosshair you want as instructed in the README linked above. Let me know if that resolves your issue.
