### ISSUE TITLE
Damage colors always defaulting to red.

### ISSUE THREAD

**Issue by AndoniLarz** [CriticalFlaw/flawhud#23]
Hi !

I downloaded the last version from the late march update, and I found that my damage number is now displayed in red. Before that update, it was yellow.
Is it some hud related stuff or a basic tf2 setting stuff ? 
I'd like to get it back to yellow, tried to look in the hud's files and found the ```G_Hit``` value was used but didn't want to mess with the dependencies so I prefered to ask here.

Thank you for your work !

**Comment by CriticalFlaw** [comment]
Damage colors are now being controlled by cvars and cannot be preset in the hud. You'll either have to set the color you want in the Advanced Options and add the following to your autoexec

hud_combattext_red ###
hud_combattext_green ###
hud_combattext_yellow ###

Where ### is your RGB color value

**Comment by AndoniLarz** [comment]
Great, thank you !
