### ISSUE TITLE
[Feature Request] Add 'Reload Hud' to the Sidebar Pins

### ISSUE THREAD

**Issue by ghost** [CriticalFlaw/flawhud#231]
It would be convenient to skip one extra button press and reload instantly. Much more useful than the Favorite Server pin, too.

![Mockup wawawa](https://user-images.githubusercontent.com/73834086/181833455-c24ac4d7-df94-4581-ae85-5f976ad5cfb7.png)

Here's a quick mock-up to show what I mean. Thanks for making a sweet hud :)

**Comment by CriticalFlaw** [comment]
Added in 3df7511a83b495b3f569c097ac0c657434d5c5f2. Thank you for the suggestion.

![image](https://user-images.githubusercontent.com/6818236/181866738-9808b6b0-be56-40a3-ae54-7a3095b057ca.png)

**Comment by CriticalFlaw** [comment]
Fantastic choice of background btw.

**Comment by ghost** [comment]
Thank you!! Snagged it from [this mod](https://gamebanana.com/mods/346727) and threw it in Krita. Here it is if you want it :)

![background_mvm_widescreenfddfdsdsgj](https://user-images.githubusercontent.com/73834086/181875670-f7646eb6-5d5d-4122-a2a7-7852589aa392.png)
