### ISSUE TITLE
Team Score Panel overlaps time panel

### ISSUE THREAD

**Issue by Oldcustard** [CriticalFlaw/flawhud#233]
When enabling the team score panel (for use with casting essentials), the labels overlap the time panel like shown below.

![image](https://user-images.githubusercontent.com/5745583/184538046-b6577c32-be44-4f29-8361-1c737c57c7d7.png)

Using v2022.0401

**Comment by CriticalFlaw** [comment]
Fixed in 9414bf5c946f97468203a5fdd48e67a15626dee7, please retest and let me know if it works.

**Comment by Oldcustard** [comment]
Seems to be fixed. Thank you. However, when updating to the latest, I noticed another issue #234.
