### ISSUE TITLE
Medigun info panels are positioned incorrectly

### ISSUE THREAD

**Issue by Oldcustard** [CriticalFlaw/flawhud#234]
The medigun info panels are incorrectly positioned when using the latest master.
![image](https://user-images.githubusercontent.com/5745583/184612663-ce198f2d-9ec7-4d0c-a8fc-9d3ce54f21c8.png)

On this note - what is the reasoning for this change? Would it be possible to have a configuration option that keeps the red team on the right side of the screen?

**Comment by CriticalFlaw** [comment]
Oh, I forgot about those - will update them shortly.

The reason for the update is that the position of the red player panels is relative to your screen size. So if you used a resolution other than 1920x1080 then the panels would be shown offscreen. This change also makes it easier for me to manage them in the future.

**Comment by CriticalFlaw** [comment]
Fixed in 643e6d5761ca3e3f69256e62869cab11d06e7279
