### ISSUE TITLE
TF2 logo not displaying in sv_pure servers

### ISSUE THREAD

**Issue by mikehawk443** [CriticalFlaw/flawhud#236]
![Zrzut ekranu (679)](https://user-images.githubusercontent.com/111538982/185501366-d87c3751-d98d-4f80-b6cb-63dfc4604307.png)

**Comment by CriticalFlaw** [comment]
I forgot that new materials need to be preloaded to display in sv_pure servers. I'll correct that today.
FYI @Metisz

**Comment by CriticalFlaw** [comment]
Fixed in 66baaed6a44424b3b7438254aac99991e19c562a
