### ISSUE TITLE
Black bars on item skins in 1440p

### ISSUE THREAD

**Issue by nifte** [CriticalFlaw/flawhud#238]
In 1440p resolution, any item in the loadout menu with a skin on it seems to shrink and leave a black bar below its image. I've attached some screenshots with examples.

![screenshot](https://user-images.githubusercontent.com/9247037/187093812-b2eba70b-6854-4a84-a8b2-71c017fa5225.png)
![screenshot2](https://user-images.githubusercontent.com/9247037/187093813-c11927a3-92f2-43a4-bea2-c5ce2c9a844d.png)

**Comment by CriticalFlaw** [comment]
Potentially fixed in e30abe814056d7b50e4810d4e9dc0c7d466bb586. Please test it out and let me know how it is.
