### ISSUE TITLE
Sometimes the red square around the Health Icon when you're on low health stays there after you respawn with full health

### ISSUE THREAD

**Issue by soot716** [CriticalFlaw/flawhud#239]
I'll try finding an instance of it happening soon.

**Comment by Metisz** [comment]
I believe that's a **game bug**, not really fixable for any HUD
![image](https://user-images.githubusercontent.com/47070328/187972289-30d3538f-f5ac-41e5-852f-60f92a4c03be.png)
If you don't want to do the `hud_reloadscheme` thing these have been working for me:
- being overhealed for a moment
- using the GRU on Heavy (or anything that reduces his max HP temporarily)

**Comment by soot716** [comment]
Thank you for the reply, and for the fixes. I really thought it was a bug with the HUD, sorry for the false alarm.
