### ISSUE TITLE
When I turn on streamer mode some of the text is changed into the menu icons

### ISSUE THREAD

**Issue by Onyx997** [CriticalFlaw/flawhud#240]
![image](https://user-images.githubusercontent.com/95724916/189526201-81adf1e0-b530-4bb4-b235-6b047704a75d.png)
Heres the image when I turned on streamer mode

**Comment by CriticalFlaw** [comment]
That's the point of streamer mode. To hide all player names. That's not a bug with this feature.

**Comment by Onyx997** [comment]
Oh alright
