### ISSUE TITLE
Sometimes player health does not turn green when overhealing them.

### ISSUE THREAD

**Issue by Oh-My-Lands** [CriticalFlaw/flawhud#241]
When overhealing a player I expect their health to turn green, and usually it does turn green. But sometimes their health stays white even when they are overhealed.
![normal overheal](https://user-images.githubusercontent.com/114635931/192932882-e3d4cf20-53bd-40c8-bc9e-4d3646b3f9f5.png)
![not normal overheal](https://user-images.githubusercontent.com/114635931/192932895-f97d6736-36f5-4bf2-8364-64933cbda8cf.png)

**Comment by MINIX32** [comment]
Also when respawning your health sometimes stays red

**Comment by CriticalFlaw** [comment]
> Also when respawning your health sometimes stays red

That's a known game bug. There's no fix for it.

**Comment by CriticalFlaw** [comment]
I think this usually occurs when you start healing a player who is already buffed. The way animation works, the value probably has to already be visible to turn green.

Since this is an intermittent issue that's not reflected in https://github.com/CriticalFlaw/flawhud/blob/master/scripts/hudanimations_custom.txt#L2 I doubt this is something that be fixed on my end.

**Comment by Oh-My-Lands** [comment]
> I think this usually occurs when you start healing a player who is already buffed. The way animation works, the value probably has to already be visible to turn green.

I have some examples where the player healed is unbuffed with health visible for a bit before I heal them and their health turns white.

> Since this is an intermittent issue that's not reflected in https://github.com/CriticalFlaw/flawhud/blob/master/scripts/hudanimations_custom.txt#L2 I doubt this is something that be fixed on my end.

ok. Thanks for looking into it anyways :) I love your HUD.

**Comment by CriticalFlaw** [comment]
I'll maintain that this is a game bug related to animations. The way they are set up right now, the health color has to change when the player is buffed. The only thing I can think of is that the animation event `HudHealthBonusPulse` does not get triggered when it is supposed to, causing this bug.

I'm going to close the ticket as this is a game bug, but I will keep an eye on this in case there's ever a foolproof solution to this. Thanks!

![image](https://user-images.githubusercontent.com/6818236/197087235-b5e7f2d5-b0db-43f1-b603-1f9c499c4da6.png)
