### ISSUE TITLE
Spectator text on scoreboard cut off on 2560x1440p display

### ISSUE THREAD

**Issue by nigiriemoji** [CriticalFlaw/flawhud#243]
Hi, my spectator text on the scoreboard is cut off at the bottom. I play on a 2560x1440p monitor.

Also, is there a way to have the scoreboard show 16 players per team instead of just 12 max?

![20221011193146_1](https://user-images.githubusercontent.com/53108354/195658627-624dbf1f-241d-4ac2-a26c-f1a286981149.jpg)

**Comment by CriticalFlaw** [comment]
Fixed in b140383cf116851dcc9cf0ee49d1a19951c78222. Thank you for reporting the issue.
