### ISSUE TITLE
Feature request: hide "equipped" in loadout item selection screen

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/flawhud#250]
![image](https://user-images.githubusercontent.com/30274161/197426995-ab0f5b3b-76aa-4c03-a52b-ecb3fc5b3e11.png)

**Comment by CriticalFlaw** [comment]
Instead of removing that label outright it's better to position it where it won't overlap other icons. Added in 87f0b116e3cf0d7a5dedbc613b0064fe0283db9c.

![image](https://user-images.githubusercontent.com/6818236/197915361-a9f19a5e-3c03-4f6b-aad1-6837ecea1fe5.png)
