### ISSUE TITLE
Class Title not centered in Default Loadout Style config

### ISSUE THREAD

**Issue by Metisz** [CriticalFlaw/flawhud#254]
It's a minor thing, but I doubt it's intentional so I'll put it here

![image](https://user-images.githubusercontent.com/47070328/198873540-c582903a-ea2e-4f43-ad1a-aefd4eca4788.png)

**Comment by CriticalFlaw** [comment]
It needs to be corrected in the editor schema file.

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/CriticalFlaw/TF2HUD.Editor/pull/139
