### ISSUE TITLE
Notification Text is black 

### ISSUE THREAD

**Issue by Metisz** [CriticalFlaw/flawhud#256]
![image](https://user-images.githubusercontent.com/47070328/198879381-0a6e279c-a709-4e89-ad30-e9c677d4b240.png)

**Comment by CriticalFlaw** [comment]
Fixed in 6aa63244fda1bc441f6cba6db76ae05122c8192c. Thank you for reporting!

![image](https://user-images.githubusercontent.com/6818236/198903643-544eea23-9b22-421a-9af2-12c5626c9bc8.png)
