### ISSUE TITLE
TF2 default background is shown when starting up the game

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/flawhud#257]
It should be the HUD's background.

**Comment by CriticalFlaw** [comment]
I think this is due to the recent change where there's no separate _widescreen variant for every background. VMTs for both variants reference to the same file.

I think in one of the Source 1 issue trackers it was said that's it's a loading issue.

The solution would be to add duplicates of each background with _widescreen at the end but that would just bloat the HUD size.

Not sure if there's a better fix for this.

**Comment by Tiagoquix** [comment]
Maybe using symlinks on Windows...? But this requires manual work.

**Comment by CriticalFlaw** [comment]
Maybe it can be done using a BAT file that will also update the HUD like it's done for budhud

**Comment by Tiagoquix** [comment]
Yeah, maybe

**Comment by Tiagoquix** [comment]
I was thinking and personally I am against the fact of requiring more manual actions from the users besides installing the HUD itself. I don't think this is a cool idea: it would be the same principle as installing a game, but requiring the user to download a mod from the developer's official website, rather than including the modification together with the original game.

Considering the fact that we've had these redundant background files for years on the HUD, I don't think it's going to be a problem.

By the way, if we compare, your HUD is smaller in file size than others found in huds.tf, or even the same size, and possibly all HUDs that change the background also repeat this idea of having redundant background files to correct this error from Valve.

**Comment by CriticalFlaw** [comment]
I think this is better suited for an updater that can come included with the HUD like budhud. I'm not a fan of adding redundant files in the download for an issue only present for a couple of seconds on game launch only. If this was recurring like it would always display on map loads then that would be more justifiable.

**Comment by CriticalFlaw** [comment]
Moving this request over to https://github.com/CriticalFlaw/flawhud/issues/271

**Comment by Tiagoquix** [comment]
Considering #271 has been closed, what about this problem?

**Comment by CriticalFlaw** [comment]
Not a priority considering it's only shown on startup.
