### ISSUE TITLE
"view entire backpack" while doing halloween transmute has messed up layout.

### ISSUE THREAD

**Issue by Platina6978** [CriticalFlaw/flawhud#258]
Title. Only had this issue after updating to the newest version. I play on 1920*1080 resolution, if that helps.
![20221031102213_1](https://user-images.githubusercontent.com/71837773/198975336-0108d9bf-5db3-42e8-b646-c0cae8db4a89.jpg)

**Comment by CriticalFlaw** [comment]
Does this happen if you do a clean reinstall with the version directly from GitHub?

https://github.com/CriticalFlaw/flawhud/archive/refs/heads/master.zip

If so then I may have screwed up the package deployed to huds or wherever you downloaded it.

**Comment by Platina6978** [comment]
Seems like you were quicker to fix it than I was to reply. Yes I did get it straight from github here originally. Anyway, thanks!

**Comment by CriticalFlaw** [comment]
No problem. I had another user on Discord with the same issue and they were able to help me reproduce the issue. Thank you!
