### ISSUE TITLE
Damage numbers is too obstructing

### ISSUE THREAD

**Issue by ThatGreenBlur** [CriticalFlaw/flawhud#259]
it makes the game unplayable because when im firing from mid range to multiple people it gets really hard to track or see them, i suggest making it 50% or 25% smaller. (im firing at a heavy and soldier in this picture)
![hitnumbersizetoolarge](https://user-images.githubusercontent.com/115673550/199150979-5b00e3bf-5bc8-4095-be34-57d66b288170.png)

**Comment by Tiagoquix** [comment]
I personally disagree. They're fine to me.

**Comment by Platina6978** [comment]
Going to agree with Tiagoquix here, never really had a problem with the size of the damage numbers. Of course it does come down to personal preference too.

**Comment by ThatGreenBlur** [comment]
i found out the damage numbers seems to be fine on close range but when shooting multiple people on mid range the damage numbers gets really close to the target and makes it harder to see, decreasing the size could help with that but i think the issue is with the location it appears
![damagenumberlocation](https://user-images.githubusercontent.com/115673550/199212017-9f72207c-05f5-4b42-a611-9c1e9b2733ad.png)

**Comment by CriticalFlaw** [comment]
I do not get a sense that there's a strong consensus that the damage number are too large, so a customization option via the editor I think would be the best way to go.

To do it manually, you can navigate to `flawhud/resource/ui/huddamageaccount.res` and change the value of `delta_item_font` and `delta_item_font_big` to **FontBold14Outline**. This is the next smallest font variant that has an outline - depending on how it looks in game, it can be tweaked.

https://github.com/CriticalFlaw/flawhud/blob/master/resource/ui/huddamageaccount.res#L12

**Comment by ThatGreenBlur** [comment]
tysm for the consideration! yea i think this should be another tf2 hud editor customization, also thanks for telling me a way to do it manually

**Comment by ThatGreenBlur** [comment]
the damage number blocking my view is also because of the damage number's location with mid range, is that something changeable?

**Comment by CriticalFlaw** [comment]
Implemented in https://github.com/CriticalFlaw/TF2HUD.Editor/commit/a7d7439b1302548fc6b89f3862f4b01aa76c5d15

You should receive a notification to update the schema next time you open the editor. Cheers.
