### ISSUE TITLE
New toggle anti-aliasing with mat_aaquality

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/flawhud#260]
> Same feature from the HUD Tools menu will now do a hard refresh using toggle mat_aaquality.

I personally disagree. There is no clear indication that the button from the HUD tools menu will do a different thing when compared to the Reload HUD button that is shown when pressing ESC.

I would be OK with the feature if the button was like "Reload HUD (+)" (it indicates the plus sign would mean something "more").

**Comment by CriticalFlaw** [comment]
I would probably use the following:
- **Refresh HUD** - soft, `hud_reloadscheme` only.
- **Reload HUD** - hard, `hud_reloadscheme` with `toggle mat_aaquality`.

**Comment by Tiagoquix** [comment]
I personally prefer no `toggle mat_aaquality` at all, but whatever. If we choose to keep it, then yes, I agree with your idea.

I can provide the localization for PT-BR.

**Comment by Tiagoquix** [comment]
Considering we're going to use both of them, you would need to run the JarateKing's script to replace all chat_ files, except for brazilian and french. But, like I said, I personally prefer no toggle at all.

**Comment by CriticalFlaw** [comment]
It's an optional feature you don't have to use if you don't want to. The `hud_reloadscheme` will fix most of user's common issues and it's more readily available than the one with the toggle, which is more handy when HUD editing. Feel free to submit a change

**Comment by Tiagoquix** [comment]
Personally, I think I prefer "Reload HUD" (instead of refresh) and "Restart HUD". I think it's more appropriate.

Because for my language, at least, "Atualizar" (refresh) is the same word for "update", so that's not so good.

**Comment by CriticalFlaw** [comment]
In English context Reload and Refresh are more appropriate. It does not need to match in other languages so word it in a way that makes the most sense in your language.
