### ISSUE TITLE
Ubercharge bar blocks top info of target id

### ISSUE THREAD

**Issue by ThatGreenBlur** [CriticalFlaw/flawhud#263]
blocks info such as: ammo, disguise, and class icon especially when the ubercharge is full and opaque

![20221104120847_1](https://user-images.githubusercontent.com/115673550/199890963-525bed59-a362-4400-9728-c0a9cf327c5e.jpg)

**Comment by CriticalFlaw** [comment]
Download the latest version. This has been quietly fixed a few days ago

**Comment by ThatGreenBlur** [comment]
strange, i just reinstalled flawhud on tf2 hud editor hours ago

**Comment by ThatGreenBlur** [comment]
latest hud schema version

**Comment by CriticalFlaw** [comment]
Hmm let me double check and get back to you later today when I'm at my PC.

**Comment by ThatGreenBlur** [comment]
aight, ill double check too rn with itemtest bots with latest github flawhud

**Comment by ThatGreenBlur** [comment]
?????? this is strange, i guess ill try it with flawhud from tf2 hud editor then
![image](https://user-images.githubusercontent.com/115673550/199969646-95ceaba9-3db5-489a-8e0c-33361ebb8938.png)

**Comment by ThatGreenBlur** [comment]
confirmed, issue from installing flawhud from tf2 hud editor
![image](https://user-images.githubusercontent.com/115673550/199971790-d5b218ad-eb2b-44ea-8011-d4165173f498.png)

**Comment by CriticalFlaw** [comment]
Cool. Will take a look today. Thank you for reporting and testing

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/CriticalFlaw/TF2HUD.Editor/commit/30ea9613038fc007208ffd86d9c5415466779612. The change was to make the vertical position of the TargetID in the schema match the live HUD version. Thanks again for reporting.
