### ISSUE TITLE
[flawhud] Charge meters are misplaced and still using wrong colors

### ISSUE THREAD

**Issue by Metisz** [CriticalFlaw/flawhud#265]
![image](https://user-images.githubusercontent.com/47070328/200142038-a19b3a62-c906-4b88-9013-5b8cca54482c.png)
![image](https://user-images.githubusercontent.com/47070328/200142039-717a0eb9-62ae-48cb-899e-1da6f44129c6.png)

They even overlap (visible because the shield's bar is a different color (along with the other bars) and is wider than the loose cannon's)
![image](https://user-images.githubusercontent.com/47070328/200142064-c4234183-ada5-4ad1-a246-a80ee1397fd8.png)

**Comment by Metisz** [comment]
@CriticalFlaw I managed to get Demo's bars to be at the right place (the white is the shield charge)
![image](https://user-images.githubusercontent.com/47070328/200144188-c1cb70d6-c15d-4305-b967-fbc6760bad03.png)
![image](https://user-images.githubusercontent.com/47070328/200144199-a828a4a9-ce42-4ac4-951d-9df64e8f2e9a.png)

Stuff left to do:
- [x] Figure out how to implement it into the `flawhud.json` because I fiddled with a **L O T** of numbers
- [x] Find why other than the stickybomb launcher's and the bows' meters every bar is white instead of TanLight
- [x] Fix the Razorback / Jarate bar from overlapping the bows' 

![image](https://user-images.githubusercontent.com/47070328/200144309-ea667268-6348-45c6-a847-7eadc33df051.png)

**Comment by CriticalFlaw** [comment]
> Figure out how to implement it into the flawhud.json because I fiddled with a L O T of numbers

I can add that in if you create a PR for the changes to flawhud. I like how it look in your screenshot.

> Find why other than the stickybomb launcher's and the bows' meters every bar is white instead of TanLight

It's hardcoded by the game. See: https://github.com/ValveSoftware/Source-1-Games/issues/2498

> Fix the Razorback / Jarate bar from overlapping the bows'

The demoman/bow charge meter will need to be raised to be above the jarate meter (huditemeffectmeter.res) it will leave a gap if the player does not have a second item with a meter but it's something I think we can all live with.

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/CriticalFlaw/flawhud/pull/266 by @Metisz
