### ISSUE TITLE
"NEW!" label does not match the shape of the page number in the inventory

### ISSUE THREAD

**Issue by Platina6978** [CriticalFlaw/flawhud#267]
Title, see screenshot added below. From what I remember, the "NEW!' label would perfectly match the size and shape of the inventory's page number underneath. Regardless I think that would look prettier!

![20221106234155_1](https://user-images.githubusercontent.com/71837773/200199434-e220a2aa-c8c8-4c4b-944c-d2ed3484b155.jpg)

**Comment by CriticalFlaw** [comment]
Fixed in f6cec959a87656a9397bc8bded92c22ae3807cb5. Please retest and let me know if the issue persists.

**Comment by CriticalFlaw** [comment]
Closing as fixed.
