### ISSUE TITLE
Changes to chat_ files and closecaption_brazilian

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/flawhud#268]
Hey! I wanna know if I can make a pull request to submit these changes:

1. Remove `FH_search` from all `chat_` files. The reason is that we have `Store_NameFilterLabel` (from `tf\resource\tf_english.txt`) at our disposal, which is the exact same as `FH_search` ("`Search:`"), plus it is localized by official translators, so there's more parts of the HUD translated instead of having to force English and realing on community-contributed translations. (Currently, this HUD only has Brazilian Portuguese and French completely translated.)
2. Edit `resource/ui/econ/backpackpanel.res` to accommodate the change above.
3. Edit Brazilian closed captions to accommodate minor changes the Brazilian translation team made to MvM-related texts.
4. Try to fix [this](https://user-images.githubusercontent.com/30274161/200311362-cc28b2a9-b517-46ad-a061-3279b6e1f1a8.png) by myself. Only happens when using Code Pro fonts. Originally, I reported it in #223, and it would not be fixed because it would overlap with the border option. However, since the border option is now at the top right corner, that shouldn't be a problem anymore.

Thanks for the attention!

**Comment by CriticalFlaw** [comment]
Items 1-3 can be bundled as a single PR. I'd keep #4 separate and we can collaborate on the best way to fix it. Thanks.

**Comment by Tiagoquix** [comment]
I think we can remove all of the empty closecaption strings. They aren't necessary.

Yes, they do give an error in the console, but we can disable the error warnings by using [this](https://github.com/mastercomfig/mastercomfig/blob/develop/config/mastercomfig/cfg/comfig/comfig.cfg#L1320).

**Comment by CriticalFlaw** [comment]
Closing. All listed changes implemented in https://github.com/CriticalFlaw/flawhud/pull/269 asnd https://github.com/CriticalFlaw/flawhud/pull/270 by @Tiagoquix . Thanks
