### ISSUE TITLE
Create a batch file for updating the HUD.

### ISSUE THREAD

**Issue by CriticalFlaw** [CriticalFlaw/flawhud#271]
Not unlike what was done for budhud: https://github.com/rbjaxter/budhud/blob/master/budhud%20Updater.ps1

Required features:
- [ ] Update the HUD to the latest GitHub version - https://github.com/CriticalFlaw/flawhud/archive/refs/heads/master.zip
- [ ] Create redundant _widescreen variants of background images (As reported in #257)
- [ ] Links and useful information.

**Comment by Tiagoquix** [comment]
Personally, I'm against the idea of creating an automatic updater separately. I prefer this to be included in the TF2 HUD Editor.

Also, automatic updates do not preserve manual custom changes made by the user.

**Comment by CriticalFlaw** [comment]
Hmm maybe the editor can run custom scripts.

**Comment by CriticalFlaw** [comment]
Closing for now. May be an idea for the editor in the future.
