### ISSUE TITLE
Can't see "Start Search" text when hovering over it

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/flawhud#272]
![image](https://user-images.githubusercontent.com/30274161/202543532-a779550e-44f9-4200-93c6-2c4709a94c20.png)
![image](https://user-images.githubusercontent.com/30274161/202543559-f60b3f72-d619-4775-9107-873ca55d3655.png)

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/CriticalFlaw/flawhud/pull/275 by @Metisz. Thank you.
