### ISSUE TITLE
Overheal(ed) color is a little too bright

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/flawhud#273]
![image](https://user-images.githubusercontent.com/30274161/202545838-f29a175b-233c-4741-88b3-0e95148ae9cf.png)

**Comment by CriticalFlaw** [comment]
Added a new color type specifically for the health box. The new color `OverhealBox` is ~25% darker than the base `Overheal`.

![image](https://user-images.githubusercontent.com/6818236/202886504-f97bdc26-38e9-4cac-8f52-0b1674cba6d9.png)

**Comment by Tiagoquix** [comment]
Even with "//" at the beginning, is the line read by the game?

**Comment by CriticalFlaw** [comment]
> Even with "//" at the beginning, is the line read by the game?

No
