### ISSUE TITLE
Change the Mode Selection images

### ISSUE THREAD

**Issue by Metisz** [CriticalFlaw/flawhud#274]
I think they shouldn't be placed this low (and maybe it's even a bit to the left but I'm unsure about that)
![image](https://user-images.githubusercontent.com/47070328/202735045-f573dbba-efff-4955-ae43-b1fd29d63eba.png)

**Comment by Metisz** [comment]
To be more precise there is this clear line where they cut off 
![image](https://user-images.githubusercontent.com/47070328/202755323-c49c1fec-7185-452a-8c1f-3cd5c759fb53.png)

**Comment by Tiagoquix** [comment]
I'm not sure, but I think it's intentional.

**Comment by CriticalFlaw** [comment]
It was intentional because the text was aligned to the top to not clash with the background

**Comment by CriticalFlaw** [comment]
Also those images are edited to look the way they do and are located in `flawhud/materials/vgui/main_menu/`.

If you remove them you'll see them like this.

![20221119235443_1](https://user-images.githubusercontent.com/6818236/202886333-f51172b2-c7aa-4e73-8bd2-9f3ca12baaac.jpg)

Which imo looks awful. So unless someone wants to go and re-edit those images and see if they look better, there's no need to change this.

**Comment by Tiagoquix** [comment]
> Also those images are edited to look the way they do and are located in `flawhud/materials/vgui/main_menu/`.
> 
> If you remove them you'll see them like this.
> 
> ![20221119235443_1](https://user-images.githubusercontent.com/6818236/202886333-f51172b2-c7aa-4e73-8bd2-9f3ca12baaac.jpg)
> 
> Which imo looks awful. So unless someone wants to go and re-edit those images and see if they look better, there's no need to change this.

They look good to me, but I prefer the current version, which gives a "feel" of darkness.

**Comment by Tiagoquix** [comment]
> Also those images are edited to look the way they do and are located in `flawhud/materials/vgui/main_menu/`.
> 
> If you remove them you'll see them like this.
> 
> ![20221119235443_1](https://user-images.githubusercontent.com/6818236/202886333-f51172b2-c7aa-4e73-8bd2-9f3ca12baaac.jpg)
> 
> Which imo looks awful. So unless someone wants to go and re-edit those images and see if they look better, there's no need to change this.

How about four-sided vignette images instead of the current edited images?

Example: https://www.pngkey.com/png/full/182-1823074_vignette-1-dark-light-effect-png.png

**Comment by CriticalFlaw** [comment]
Sure. I'm open to changing it if the suggestion looks better.

**Comment by Tiagoquix** [comment]
All right.

To clarify, I mean: keep the mode selection background images as they are, but instead of having a black overlay on the top as it is, switch to a four-sided vignette for each image to see how it looks.

**Comment by Metisz** [comment]
> All right.
> 
> To clarify, I mean: keep the mode selection background images as they are, but instead of having a black overlay on the top as it is, switch to a four-sided vignette for each image to see how it looks.

I'm thinking of making either minimalist ones with just logos or simplified silhouettes of the current ones
the label is more important after all

**Comment by Metisz** [comment]
Regarding that, what file is responsible for all the backgrounds to have a darkening filter? Can't find that in `matchmakingplaylist.res`

**Comment by Metisz** [comment]
In the meantime I took some images for testing and for potential replacement
only thing is that the Community and Casual images are from community made animations (Team Fortress 3 and TF2 vs Overwatch 2) so putting those in without asking would be troubling
![asd](https://user-images.githubusercontent.com/47070328/203997363-c7ac6e91-bf46-4ac1-910b-3dd40f8ff2a4.PNG)

alternatively i could just slap in logos like this one and call it """minimalistic"""
![asd](https://user-images.githubusercontent.com/47070328/203997538-14675764-169e-4972-a222-415b8897a80b.PNG)

lmk your thoughts

**Comment by Tiagoquix** [comment]
Minimalist logos: I don't like the idea, I think it's something so simple to the point of taking the HUD's charm away.

New images (+ those of community SFMs): I love them! I think they could be implemented, but of course, with authorization.

As for adding silhouettes: depending on how it looks, it might look cool.

> Regarding that, what file is responsible for all the backgrounds to have a darkening filter? Can't find that in

I believe they are edited from the .vtf file itself to look this way (i.e. the image already has the filter applied, there's no post-processing effects coming from the HUD).

**Comment by CriticalFlaw** [comment]
If you open those image files in VTFEdit (or Paint.NET with a VTF plugin which is what I use) you'll notice that parts of the image are actually transparent. In game there's black background to the image that makes it look like it's fading into darkness.

When I opened those images again for the ticket, I remembered how much of a pain in the ass they were to edit hence why I'd rather someone else do it 😋 

The alternatives look pretty good, unless there are other options for consideration, we can give those a trial run and see what people think, with author's permission of course.

**Comment by Metisz** [comment]
> The alternatives look pretty good, unless there are other options for consideration, we can give those a trial run and see what people think, with author's permission of course.

I'll keep looking for images to replace the ones that'd need permission

**Comment by Metisz** [comment]
Using only official artwork 
What do you think?
![image](https://user-images.githubusercontent.com/47070328/204090332-f005c24c-2a81-48f2-abaa-0906d78ba972.png)

**Comment by Tiagoquix** [comment]
> Using only official artwork What do you think? ![image](https://user-images.githubusercontent.com/47070328/204090332-f005c24c-2a81-48f2-abaa-0906d78ba972.png)

Cool!

**Comment by CriticalFlaw** [comment]
After sleeping on it for a few days, I like them too except for maybe the Community Servers image I'd keep that as-is - it feels more fitting than saxton hale. If you can create a PR for this I'll add it in. Cheers.

**Comment by Metisz** [comment]
> except for maybe the Community Servers image I'd keep that as-is

That'll be easy because that image is just taken from Meet the Spy
Will fiddle with the positioning of it

**Comment by CriticalFlaw** [comment]
Added in https://github.com/CriticalFlaw/flawhud/pull/281. Thanks @Metisz
