### ISSUE TITLE
Demoman shield charge is completely in the wrong position (Centered HUD)

### ISSUE THREAD

**Issue by Dupiter-AU** [CriticalFlaw/flawhud#276]
Compared to other item meters, the shield charge is on the right hand side of the screen for the centered HUD. From what I've found this only occurs with Shields.
![Screenshot_20221119_151725](https://user-images.githubusercontent.com/82429716/202835607-4a151869-ab56-4da0-aaaf-c9cd41481993.png)
I tried fixing this myself but I couldn't find the right file.

**Comment by Metisz** [comment]
Are you sure you're using the latest version? I did a reinstall on HudEditor and it's fine for me
If you are, try to change the setting to Cornered and then back to Centered

![image](https://user-images.githubusercontent.com/47070328/202847650-39b625c5-fbee-41ae-a335-76928398f970.png)

**Comment by Dupiter-AU** [comment]
I'm using the [2022.1112 version](https://github.com/CriticalFlaw/flawhud/releases/tag/2022.1112). I don't think I would be able to use the TF2 HudEditor as I am using Linux and the last time I tried to use it it wouldn't open.

**Comment by CriticalFlaw** [comment]
@Dupiter-AU I've updated the centered layout upload on the [2022.1112 version](https://github.com/CriticalFlaw/flawhud/releases/tag/2022.1112) release page. The previous version was missing @Metisz' fixes.

**Comment by Dupiter-AU** [comment]
Yes this is now fixed. Thanks for the help!

On a side note, the Vaccinator's charge meter is a bit bugged as shown below, so I'll make another issue for that

![Screenshot_20221120_172048](https://user-images.githubusercontent.com/82429716/202890672-0457aba6-74b5-4565-9aa2-2b69d8a53f89.png)

**Comment by Dupiter-AU** [comment]
[](url)
