### ISSUE TITLE
Vaccinator Bubble charge off-centered and corners are not correctly rendered

### ISSUE THREAD

**Issue by Dupiter-AU** [CriticalFlaw/flawhud#277]
As shown in the screenshot below, the Vaccinator's bubble charges are not correctly placed inside the border, and the border does not correctly fit the master region.

![Screenshot_20221120_172048](https://user-images.githubusercontent.com/82429716/202890712-4a7538ac-5c9a-4879-aebc-6a080ccfea5a.png)

My temporary solution to this problem was to change the xpos value in `hudmediccharge.res` to -2 as opposed to -3. Not sure if this qualifies as a fix, but it works for me.

![Screenshot_20221120_172342](https://user-images.githubusercontent.com/82429716/202890769-2b08f0cd-536c-41c3-b8f3-9c898dfbd993.png)

EDIT: This change makes the bubble charges more centered as shown:

![Screenshot_20221120_172548](https://user-images.githubusercontent.com/82429716/202890827-2b17bf10-9328-4391-b567-8455f85b0c28.png)

Not sure what causes the broken border, I still haven't found the correct value for that yet

**Comment by Tiagoquix** [comment]
Taking advantage of this issue, I would like to suggest a reduction to the size of the charge bars when using the centered HUD. I think they're too big.

**Comment by CriticalFlaw** [comment]
Reduced the size of the vaccinator meter when using the centered layout. The bars are also centered. This change has to be applied through the editor. Thanks.
https://github.com/CriticalFlaw/TF2HUD.Editor/commit/100eac6474ff7fbb729be4187285bf674086765d

![20221120144937_1](https://user-images.githubusercontent.com/6818236/202922946-650ab32a-92c2-42bd-b41c-b34e11460811.jpg)
