### ISSUE TITLE
[Suggestion] Put Extra options next to the other panels

### ISSUE THREAD

**Issue by Metisz** [CriticalFlaw/flawhud#278]
**I can likely do it because I did something similar for a friend of mine, but I want to know what you guys think about the idea**

![image](https://user-images.githubusercontent.com/47070328/202907490-c6b72cf1-7484-463a-9143-9e4b27d20f54.png)

**Comment by CriticalFlaw** [comment]
I had tried it before but it made everything "too heavy" to one side. Some of those buttons also open panels like MOTD and Tools so it makes everything look unbalanced

**Comment by Tiagoquix** [comment]
I disagree with the OP. I prefer the current version.

**Comment by Metisz** [comment]
What if I made it an option in HudEditor?

**Comment by Tiagoquix** [comment]
> What if I made it an option in HudEditor?

I don't see any problem with that.

**Comment by CriticalFlaw** [comment]
I think it's too niche of a customization to be added to the editor.

**Comment by Metisz** [comment]
Then I don't think there's much more to discuss, closing this
