### ISSUE TITLE
Expand HUD Tools Panel

### ISSUE THREAD

**Issue by CriticalFlaw** [CriticalFlaw/flawhud#279]
### New Additions (not final)
- [x] Voice Chat Volume (slider)
- [x] Viewmodel (slider)
- [x] Minimal Viewmodels (checkbox)

### Changes
- [x] Streamer Mode to a checkbox.
- [x] Match HUD to a checkbox.
- [x] Captions to a checkbox.
- [x] Voice Chat to a checkbox.
- [x] Net Graph to a checkbox.

![image](https://user-images.githubusercontent.com/6818236/202922224-f6a3f8c1-0bc3-46eb-a1db-afabf7687d2d.png)

**Comment by Tiagoquix** [comment]
What new changes and/or buttons do you intend to implement?

**Comment by CriticalFlaw** [comment]
Not sure yet. I've seen a number of other huds add additional options, so I'll see which ones are a good fit

**Comment by CriticalFlaw** [comment]
Tracking here: https://github.com/CriticalFlaw/flawhud/tree/feature/279

**Comment by CriticalFlaw** [comment]
All the elements are in place and connected. Just need testing.

The checkboxes don't remember the initial set value of a cvar. For example, if you start the game with min. viewmodels enabled - the checkbox will be toggled off by default. Not sure if there's a way around this or if people will care.

**Comment by Metisz** [comment]
> The checkboxes don't remember the initial set value of a cvar.

It also resets when reloading the HUD
It'll still work in an inverse way though (aka there can be cases where the box being ticket does the opposite of what it would initially)

**Comment by CriticalFlaw** [comment]
Maybe be safer to just keep them as buttons then. Less confusing
