### ISSUE TITLE
The ammo counter breaks when trying to display the number 40

### ISSUE THREAD

**Issue by MechancicalMechanism** [CriticalFlaw/flawhud#280]
![hl2_aCYybdn3ll](https://user-images.githubusercontent.com/44928332/204081897-8f19c1b9-7867-4635-863d-ea9138b260f7.png)

This is most present with the Syringe Gun. The number renders correctly starting with 39, but it always breaks at 40.

My resolution is 1980x1080, I don't use minimal HUD, I have no mods in the attached screenshot, and I'm on the latest version posted to huds.tf.

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/CriticalFlaw/flawhud/commit/722b3f2192959116ef9b7103f51aeb08fa607167 Thanks.
![20221128232320_1](https://user-images.githubusercontent.com/6818236/204438462-81955114-0a9b-4063-b1d7-7f4829922a37.jpg)
