### ISSUE TITLE
Counter for stickies active covers healer text on 1440p

### ISSUE THREAD

**Issue by nigiriemoji** [CriticalFlaw/flawhud#285]
2560x1440p display. Reinstalled flawhud as of today
![20221210231923_1](https://user-images.githubusercontent.com/53108354/206898308-949dff8d-c0eb-42c5-8834-3363a2e2abe4.jpg)

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/CriticalFlaw/TF2HUD.Editor/commit/ae56cf744df8ad44c24ecb7f4e7af7c4d0d2dfd3. Will reupload to huds.tf and GitHub shortly. Thank you for reporting.
