### ISSUE TITLE
Overtime text covered by 2nd timer (unknown)

### ISSUE THREAD

**Issue by nigiriemoji** [CriticalFlaw/flawhud#286]
Overtime text is not center and covered by a 2nd timer that doesn't seem to be related to the actual timer. What is this 2nd timer?

![20221211022004_1](https://user-images.githubusercontent.com/53108354/206898327-6c93fb04-85eb-49cd-bb10-c273a9b32db7.jpg)

**Comment by CriticalFlaw** [comment]
It's the server time before the next map change.

Because the same timer is shown on the scoreboard, I don't think it's worth having it there when it interferes with other text like that.

**Comment by CriticalFlaw** [comment]
Fixed in 07be8514a600fa2b7bbda96cec5752a5a634bef4. Cheers
