### ISSUE TITLE
Coloured Text Health Number snot Working Properly

### ISSUE THREAD

**Issue by WishMount** [CriticalFlaw/flawhud#288]
Hey mate, small issue! I had my health numbers set to the coloured text config and was working fine, but now I'm stuck with the weird black background around/behind the health numbers that should be appearing with the default health config and I can't seem for the life of me to get rid of it! Any suggestions?

It's quite distracting and I'd rather it just look like the ammo text with just text without a background. 
![20230115131827_1](https://user-images.githubusercontent.com/122709014/212519579-32a08a2f-6976-4d45-8bae-4ff00a1a7dbd.jpg)
As you can see I have this black box, but below you can see that I have coloured text anabled, that used to just have text with no over/underlay
![HUD](https://user-images.githubusercontent.com/122709014/212519648-a0cf36b9-e2b4-41de-b781-52e5a80d8ca7.PNG)
![20230115131835_1](https://user-images.githubusercontent.com/122709014/212519657-ea71a600-76fc-4f72-bfc1-533cabe8269f.jpg)

**Comment by CriticalFlaw** [comment]
Does `hud_reloadscheme` (or HUD Refresh) remove it?

**Comment by WishMount** [comment]
No good! here's what comes up afterward
] hud_reloadscheme
--- Missing Vgui material vgui/TanLi

Not sure if this is related to the issue but still persists after I laod in. I've reinstalled, tried removing TF2 editor and using flawhud normally then trying again! So weird.

**Comment by CriticalFlaw** [comment]
Noted, will investigate. Thanks.

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/CriticalFlaw/TF2HUD.Editor/commit/ae3a7dcc0b53224b503831c108cb5346a6ec8351. You'll need to download the latest schema update to get the fix, then reapply the changes.
