### ISSUE TITLE
Overlapping bar and arrow when moving items in inventory

### ISSUE THREAD

**Issue by thejaviertc** [CriticalFlaw/flawhud#290]
When you move an item in the inventory, another bar appears on the sides that does not fill the one that is already there. The same goes for the arrow.

https://user-images.githubusercontent.com/45662206/215273535-05c119d0-6ad2-4249-8fd8-bfe57bfcb813.mp4

Maybe is difficult to see it in the video but part of the bar gets darker (because there is another one appearing)

**Comment by CriticalFlaw** [comment]
Good catch. Will check it out today

**Comment by CriticalFlaw** [comment]
Fixed in eb8b49c6207ac7a766200ad88cfe7c7fc33c60d0. Sorry for the delay.
