### ISSUE TITLE
[Request/Suggestion] Chat Box Placement - Middle

### ISSUE THREAD

**Issue by Mister36MN** [CriticalFlaw/flawhud#291]
I suppose it might be a question of whether this is even possible within TF2/Huds, but I would love if we could place the chat box in the middle of the screen, rather than the default top or the original TF2 bottom. 

Is this something that would be done on the HUD editor side, the HUD itself, or not able to be done?

**Comment by CriticalFlaw** [comment]
This is already an option in the editor.

![image](https://user-images.githubusercontent.com/6818236/218002808-29a6c0e7-2b4f-415b-ba69-cac24f2b9242.png)

**Comment by Mister36MN** [comment]
Yes, that lowers it to the near bottom of the screen, what I was looking for specifically was something inbetween the top and bottom.

**Comment by CriticalFlaw** [comment]
For that you'll need to go to `resource/ui/basechat.res` - find HudChat and change the ypos value to something like c0 until you get the desired effect.

The way it's setup in the editor takes the achievement tracker and Engineer's buildings into consideration so it cannot be edited to keep the chat aligned to center. The only other option is to adjust it manually.

**Comment by Mister36MN** [comment]
That's a good point. With that info I was able to move it down to a much better spot. (For anyone seeing this, the ypos on "hudchat" needs to be higher for it to go lower, 0 is at the top)
