### ISSUE TITLE
Custom Backgrounds Not Working With or Without Loading Screen Stats

### ISSUE THREAD

**Issue by Silexos** [CriticalFlaw/flawhud#292]
I'm unsure if this is an issue with the hud or the editor but when utilizing the custom background function of the editor the main menu will not use the custom image. This occurs whether the 'show on map load' is ticked or not, though interestingly when ticked the custom image will show on the loading screen. When manually dragging the files to a '_disabled' folder in the 'materials' folder and replacing it with my own .vpk, it would still have this issue.

![20230203151815_1](https://user-images.githubusercontent.com/85089160/216729084-d57d577d-9c59-42b4-9968-5f39e6eb93c1.jpg)

**Comment by CriticalFlaw** [comment]
Tried reproducing this issue but was not able to. The image would show on both the main menu and loading screen - maybe an issue that was resolved in the yet unreleased version?

![20230220224108_1](https://user-images.githubusercontent.com/6818236/220242064-ed401978-f869-4047-adca-7e2f87fdeae3.jpg)

**Comment by Silexos** [comment]
I tried again with a fresh install of the most recent versions of the hud-editor and flawhud, and it still would not use the custom background. Though this time the editor would not create a custom background at all. Maybe it is my end?

**Comment by CriticalFlaw** [comment]
Could you please check with the latest version of the editor (3.0)?

**Comment by Silexos** [comment]
Just tested it by both the editor and dropping my own .vtf into the materials folder and it works perfectly. Thank you for the help!
