### ISSUE TITLE
Add centered uber UI as a HUD option

### ISSUE THREAD

**Issue by Treeways** [CriticalFlaw/flawhud#294]
I love the minimalism of the UI in general, but I do wish the health and uber meters were in the middle on newer versions. For instance, ToonHUD has both this mode and Centered Mode as an option in the HUD settings.

![image](https://user-images.githubusercontent.com/56928485/217659015-709de24f-724e-4d40-a6af-fe61825d562f.png)
![image](https://user-images.githubusercontent.com/56928485/217659601-fded94ca-c63f-4085-b8c6-5a95a5682f14.png)

**Comment by CriticalFlaw** [comment]
The only way to make this work from within the HUD is to use minmode which is already being used by streamer mode.

The only other way to do it is through the editor. Release pages have both versions available so I don't think there's another easy way at this time: https://github.com/CriticalFlaw/flawhud/releases/latest

**Comment by CriticalFlaw** [comment]
Closing as centered layout is offered on the release page and as a customization option in the editor.
