### ISSUE TITLE
Target name and demoman's shield charge meter overlap

### ISSUE THREAD

**Issue by Platina6978** [CriticalFlaw/flawhud#295]
See picture for clarification, using latest release.
![hud bug](https://user-images.githubusercontent.com/71837773/221320299-7c6033d2-66a5-42f9-ad5b-42eb0baa5164.jpg)

**Comment by CriticalFlaw** [comment]
This was fixed in https://github.com/CriticalFlaw/flawhud/issues/289

Try download the latest version from here: https://github.com/CriticalFlaw/flawhud/archive/refs/heads/master.zip

**Comment by Platina6978** [comment]
Oh it was indeed, my bad I tend to stick to full releases only. Closing!

**Comment by CriticalFlaw** [comment]
No worries. I should update the release soon. :)
