### ISSUE TITLE
Certain hud elements being cut off/out of place on 1440p resolution

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/flawhud#296]
![image](https://user-images.githubusercontent.com/123919000/221941950-ca07f14e-97fc-4b68-b30c-edb24c8826c8.png)

![image](https://user-images.githubusercontent.com/123919000/221942075-b0d53595-c9cf-48d8-b3b4-886c295c9a0b.png)

![image](https://user-images.githubusercontent.com/123919000/221942420-a985ecd6-cb03-4118-8f55-00e6cba8545f.png)

Issue on the first image is while using Code Pro fonts using the hud editor, the Domination and Headshots stats are cut off on 1440p resolution, 1080p is fine

The issue on the 2nd and 3rd images is on the stats screen, the Most Backstabs is slightly out of place and is going outside of the box on 1440p resolution and the issue is present on both the normal and code pro fonts.

**Comment by CriticalFlaw** [comment]
Fixed in 76b496ec7d009cc7c3c307346b01946f7dde0154. Forgot to take screenshot of the Stats screen but here's the scoreboard. Thank you for reporting.

![20230301220135_1](https://user-images.githubusercontent.com/6818236/222320296-3dd9e8ce-43f1-4d62-8260-02c451a04d9a.jpg)
