### ISSUE TITLE
Issues with killstreak fabricators

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/flawhud#297]
![image](https://user-images.githubusercontent.com/123919000/222935283-824d558a-62c5-4faa-b4e1-0f82e77e0594.png)

Two issues spotted here,

First issue is that the little arrow buttons that are used to go through the pages of items is overlapping with where the items are

Second issue is the box where you have to put either a killstreak weapon or a specialized killstreak weapon into is a completely blank box with no indication of what to put in there

**Comment by CriticalFlaw** [comment]
Second issue is possibly game-related because the HUD does not control individual boxes only the whole section.

First one will be fixed soon. Thank you for reporting.

**Comment by Presto06** [comment]
> Second issue is possibly game-related because the HUD does not control individual boxes only the whole section.
> 
> First one will be fixed soon. Thank you for reporting.

![image](https://user-images.githubusercontent.com/123919000/222962437-3057dd68-f623-4fc7-86e0-3e0c703facfb.png)

![image](https://user-images.githubusercontent.com/123919000/222962537-c5b2def4-f223-41db-afe1-a4ec283d904d.png)

Interestingly enough, the default hud is completely fine and so are other custom huds such as budhud, which makes me think it is an issue with the hud rather than a gameplay issue.

**Comment by CriticalFlaw** [comment]
Fixed in 3e76bd6958cea6916d779eba63c0d0aa7d9332a7. Thank you for reporting.

![20230305100738_1](https://user-images.githubusercontent.com/6818236/222968729-90a6474f-7d53-43e1-8e41-f1da0c38ecf9.jpg)

**Comment by CriticalFlaw** [comment]
Regarding the other issue - looking at the hierarcy, the item panel is there but for some reason is not being rendered. The HUD file for this page does not control individual boxes so it may be a just a game bug after all.

![image](https://user-images.githubusercontent.com/6818236/222968839-9650aa64-c2fe-4200-a60a-8a8622aa120b.png)

**Comment by Presto06** [comment]
> tem panel is there but for some reason is not being rendered. The HUD file for this page does not control individual boxes so it may be a just a game bug

Ah alright then, no problem thanks for looking into it
