### ISSUE TITLE
Change the file names to lowercase for Linux

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/flawhud#298]
flawhud-master/materials/vgui/maps/menu_thumb_Missing.vmt
flawhud-master/resource/fonts/CodeProBold.otf
flawhud-master/resource/fonts/CodeProLC.otf
flawhud-master/resource/fonts/TF2Crosshairs.ttf
flawhud-master/resource/fonts/TF2Icons.ttf
flawhud-master/scripts/TF2Crosshairs.png

**Comment by CriticalFlaw** [comment]
Can you verify if this file name case is causing those fonts to not display when on Linux?

I know this was an issue with the hud files themselves, so they were all changed to lowercase years ago. But I would like to know if the same thing applies to non `.res` files first.

**Comment by impale1** [comment]
It turns out they work with capital letters, could you write to JarateKing about it? (just remember that the name of the hud must be lowercase, otherwise it won't work at all, for example, this was the case with the TF2HUD.Fixes-main folder)

**Comment by CriticalFlaw** [comment]
iirc that's only an issue with the .res files themselves and the root hud directory (had to rename the repo from FlawHUD to flawhud for that reason). I'm sure JarateKing is aware of this abnormality - until someone flags this as a real issue I think we can leave things as they are. What say you?

**Comment by impale1** [comment]
Leave it as it is and ask JarateKing to add "`.res` files and hud name must be in lower case" to his tutorial.

**Comment by impale1** [comment]
Yes, he wrote "all files" in the tutorial, but people might think that files only inside the hud folder should be in lowercase, forgetting that the name of the hud folder itself contains uppercase letters

**Comment by impale1** [comment]
If you want to change the names to lowercase, I checked, they work after renaming

**Comment by CriticalFlaw** [comment]
Good to know. Closing without further action. Thanks for looking into this though.
