### ISSUE TITLE
[Request] Add player model to the scoreboard

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/flawhud#299]
![scoreboard thingy](https://user-images.githubusercontent.com/123919000/225282279-ba6f9271-0c22-424b-a734-6abbbafcac51.jpg)

example image above

perhaps add an option in the hud editor so you can see different players 3d models and cosmetics on the scoreboard

i personally find it useful to identify different players by their cosmetics or to spot bots a bit easier

**Comment by CriticalFlaw** [comment]
Thank you for the suggestion. I'll take a look and add this as an editor option and/or part of the default HUD.

**Comment by CriticalFlaw** [comment]
Added in d62ec604acb60684265644db9a2604176cc1a837. Thank you for the request!

![20230321201857_1](https://user-images.githubusercontent.com/6818236/226770447-7cf3cf7a-8306-4eae-ac36-471bcb6e235d.jpg)

![20230321201854_1](https://user-images.githubusercontent.com/6818236/226770446-43775421-2597-431f-89cd-0e9444d3bbef.jpg)
