### ISSUE TITLE
Cursor Problem

### ISSUE THREAD

**Issue by 23SRLITheGamer** [CriticalFlaw/FlawHUD#3]
When the match ends, at the scoreboard part, my cursor is invisible the only way to see my cursor and bring it back is by pressing esc (doesn't work all the time). Can someone help me?

**Comment by 23SRLITheGamer** [comment]
![20160924224609_1](https://cloud.githubusercontent.com/assets/16334980/18809321/e483f640-82aa-11e6-8a3e-cc0495182b16.jpg)

**Comment by CriticalFlaw** [comment]
This should be fixed in the latest update (v2016.09.28)
