### ISSUE TITLE
Numbers above HP overlap

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/flawhud#300]
![image](https://user-images.githubusercontent.com/123919000/225881651-d91bc012-f8a7-473b-a34f-22a0de53b512.png)

The damage and health restored numbers above your hp overlap with one another which is mainly noticeable while using snowball weapons like the black box/kunai. It also seems to effect the concheror

This bug is happening on centered mode not sure about cornered mode

**Comment by CriticalFlaw** [comment]
This was updated recently on the cornered-mode. Need to update centered via the editor.

**Comment by CriticalFlaw** [comment]
Fixed in [3bde9549c135d1ee0a7ad0ede5a882d5d6b3cc4d](https://github.com/CriticalFlaw/TF2HUD.Editor/commit/3bde9549c135d1ee0a7ad0ede5a882d5d6b3cc4d). Thank you for reporting.
![20230321200352_1](https://user-images.githubusercontent.com/6818236/226768820-60d49d11-b8b7-4030-95e3-1c3d0814ab6c.jpg)
