### ISSUE TITLE
Stats are completely missing on the scoreboard after recent update

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/flawhud#301]
![image](https://user-images.githubusercontent.com/123919000/226991216-f17668d1-9c87-4492-94d4-698949c22ee0.png)

I like the new player model but now the stats where you see your kills and such are completely missing for me even after multiple reinstalls which is a crucial gameplay feature

**Comment by CriticalFlaw** [comment]
Fixed in the HUD Editor via 221885aa55dc5143246b824aa5a9cac87955dd91. You should receive a notification for a schema update. You may need to reinstall flawhud from the app to see the fix. Thank you for reporting.
