### ISSUE TITLE
New workshop tags missing from the importer UI

### ISSUE THREAD

**Issue by wurlmon** [CriticalFlaw/flawhud#302]
Since the 1st of March update, Valve has added two new Workshop Tags: Community fix and Summer. However, this HUD has these missing.
![showcase](https://user-images.githubusercontent.com/107316270/227136575-4a3ebcaa-9404-4b59-8cda-69aa2d8ac9c8.png)

**Comment by CriticalFlaw** [comment]
The new tags have been added in this commit https://github.com/CriticalFlaw/flawhud/commit/e0b97f642026b9d41dd26b9f172e5cdf0bf2341a.

It's just not included in the latest release. If you download from GitHub directly (https://github.com/CriticalFlaw/flawhud/archive/refs/heads/master.zip) or through the editor. You'll get this change.

The rest will need to wait for the next release.

**Comment by CriticalFlaw** [comment]
Closing as this has already been added, just not published as a release yet.
