### ISSUE TITLE
3D model of the player is enlarged in the scoreboard

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/flawhud#303]
https://github.com/CriticalFlaw/flawhud/issues/299#issuecomment-1478755584
In that comment you showed the new 3D model of the player on the scoreboard, on my side it increases in size instead of staying in one place.
* Operating system - Fedora Linux 37 (Workstation Edition)
* Resolution - 1920x1080

![1](https://user-images.githubusercontent.com/117596825/227696726-e5eab23b-d40b-4eda-851f-24b14a02f591.jpg)
![2](https://user-images.githubusercontent.com/117596825/227696722-d4378e37-db99-4a0a-bdd9-3cf84d9e7ca9.jpg)

**Comment by CriticalFlaw** [comment]
Intentional change made yesterday: https://github.com/CriticalFlaw/flawhud/commit/12827391a6d4fd945e7410257501269b3aa6def5

**Comment by impale1** [comment]
I will say it looked great, but if it's an intentional change, fine.
