### ISSUE TITLE
Skins in the mvm upgrade menu are cut off

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/flawhud#304]
* Operating system - Fedora Linux 37 (Workstation Edition)
* Resolution - 1920x1080
![bme](https://user-images.githubusercontent.com/117596825/227998774-1dce0c59-cbe8-4940-984c-dc8411f70821.png)

**Comment by CriticalFlaw** [comment]
Repositioning the images isn't possible from that HUD file and I don't think it would be worth the effort. Instead what I did is make the line thinner to give the item box more space which should be okay for this.

**Comment by impale1** [comment]
@CriticalFlaw Reopen this issue
![1](https://user-images.githubusercontent.com/117596825/229148764-71a964e7-a845-4e42-9215-8c8311c84141.png)
In the default hud it works fine
![2](https://user-images.githubusercontent.com/117596825/229148784-c20db896-6f6c-4f6c-bda2-300bf9c68a28.png)
