### ISSUE TITLE
Another hp numbers on the back of the main hp

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/flawhud#305]
* Operating system - Fedora Linux 37 (Workstation Edition)
* Resolution - 1920x1080
* Code Pro Fonts are used
![uuuuuuuuuuuf22](https://user-images.githubusercontent.com/117596825/228034965-23a5694e-29b0-4ef3-bb56-6ef8f0933263.jpg)

**Comment by CriticalFlaw** [comment]
There was a missing font definition for Code Pro fonts in `flawhud/resource/scheme/clientscheme_fonts_pro.res` - should be fixed now. You will need to reinstall flawhud to receive the fix. Thanks
