### ISSUE TITLE
Notification box is not colored correctly

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/flawhud#307]
![image](https://user-images.githubusercontent.com/123919000/228401158-2ca0a0af-7925-4f05-a3f1-3162573f6d7f.png)

Not sure if this is a bug or it is supposed to be this way but the notification box for new strange levels and stuff like that is white which goes against the rest of the hud with it being dark themed at all

I think it would probably look better being a black box with white text, that is if this is intentional

**Comment by CriticalFlaw** [comment]
This was a temporary change because I could not find what controlle the color of the "Your Shortstop...." text. It would be dark on a dark background and not visible at all. Took me a while to find it (had to look up Team Comtress) but eventually did and it should be fixed now. Thanks
