### ISSUE TITLE
Skins in the "war paint redemption" window are stretched

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/flawhud#308]
* Operating system - Fedora Linux 37 (Workstation Edition)
* Resolution - 1920x1080
![hshs](https://user-images.githubusercontent.com/117596825/228820498-cc26e2d7-4263-42b7-a845-8832ca6c7dcb.jpg)

**Comment by CriticalFlaw** [comment]
Tweaked the look of the war paint panel to help make the item panel look less compressed. Also fixed text misplacement when clicking the redeem button.
![20230330194242_1](https://user-images.githubusercontent.com/6818236/228988553-2aa92daa-17b3-49b9-aa63-439ded83a4e1.jpg)
