### ISSUE TITLE
The badge at the end of the match summary scoreboard touches the end of the screen

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/flawhud#309]
Operating system - Fedora Linux 37 (Workstation Edition)
Resolution - 1920x1080
![2](https://user-images.githubusercontent.com/117596825/228912886-0017ad3a-0901-4037-8520-116e523aeb22.jpg)
![1](https://user-images.githubusercontent.com/117596825/228912894-de5872ed-b580-4473-bd9d-f189f9572c5b.jpg)

**Comment by CriticalFlaw** [comment]
Closing as not notable
