### ISSUE TITLE
Spy disguise target hp misplaced

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/flawhud#310]
![image](https://user-images.githubusercontent.com/123919000/229026844-ebd10d61-9bf2-44f6-a0c6-4268bb907bf2.png)

**Comment by CriticalFlaw** [comment]
Editor schema needs to be updated

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/CriticalFlaw/TF2HUD.Editor/commit/b11a4400a846867f89b1d7f8546a36255d764493. You will need to reinstall flawhud from the editor then reapply the customizations
