### ISSUE TITLE
The gear is a bit cut off

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/flawhud#312]
Operating system - Fedora Linux 37 (Workstation Edition)
Resolution - 1920x1080
![66](https://user-images.githubusercontent.com/117596825/229137826-83c70311-e05d-4457-890c-56cc174dcc1a.png)

**Comment by CriticalFlaw** [comment]
![image](https://user-images.githubusercontent.com/6818236/229297299-6e73eded-dc10-4a7d-a24a-135a4cdd4b8d.png)

This is likely because non-Windows OS can render fonts slightly differently. Looks fine on my side with all resolutions.
