### ISSUE TITLE
Pass time bar has no texture

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/flawhud#313]
Operating system - Fedora Linux 37 (Workstation Edition)
Resolution - 1920x1080
![pass](https://user-images.githubusercontent.com/117596825/229193879-a06e44a2-cc5c-48bc-81eb-8add159548c6.png)

**Comment by CriticalFlaw** [comment]
Issue with the game not loading the texture in time. Not HUD related.

**Comment by impale1** [comment]
Fixed in https://github.com/CriticalFlaw/flawhud/commit/8b7b1467dd90eac0f2afa14cde31711f2f044afc
