### ISSUE TITLE
Vaccinator uber bar off-center on 1440p

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/flawhud#314]
1080P:

![image](https://user-images.githubusercontent.com/123919000/229275045-6eaf02dc-54b8-42b4-96f1-bdd521710ff5.png)

1440P:

![image](https://user-images.githubusercontent.com/123919000/229275054-ef50ae58-3ff1-41d0-8467-119299cf664e.png)

A minor annoyance, the vaccinator ubercharge bar is slightly off center on 1440p

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/CriticalFlaw/TF2HUD.Editor/commit/8fa95a22701986185414ed5af208dc7dbeddf356. Thanks for reporting.

![20230401113025_1](https://user-images.githubusercontent.com/6818236/229298603-fe1b4e71-7f15-4ecd-b504-e12f7148b815.jpg)
