### ISSUE TITLE
Alert text is unreadable

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/flawhud#315]
![image](https://user-images.githubusercontent.com/123919000/229282518-b537aa8e-0e35-42b6-b48e-e81ef1ccf9e3.png)

The text for pending alerts is unreadable since its black text on a black background, iirc there was a white background behind the text buts its gone now for some reason

**Comment by CriticalFlaw** [comment]
Fixed in d2d6aa308f7c7dcefa9f2186769a8f260fc1d7ce. Thank you for reporting.
![image](https://user-images.githubusercontent.com/6818236/229297806-526106a9-2076-469b-9fa3-554bc81d86a0.png)
