### ISSUE TITLE
Inspected weapons in backpack are off-center

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/flawhud#316]
https://user-images.githubusercontent.com/123919000/229339227-6b562a82-ab62-4818-aa80-b5e4b7e73db5.mp4

Unsure if this is a gameplay issue or an issue with the hud but ill report it anyways

If you inspect a weapon through the backpack the weapon being shown is off-center

**Comment by Presto06** [comment]
I found out that position of the weapons during inspect shares the same spot as in the war paint menu so if its not possible to seperate the spots of the weapons in both menus it may be best to leave it be since the war paint menu is way more used than the inspect weapon feature

**Comment by CriticalFlaw** [comment]
> I found out that position of the weapons during inspect shares the same spot as in the war paint menu so if its not possible to seperate the spots of the weapons in both menus it may be best to leave it be since the war paint menu is way more used than the inspect weapon feature

That's correct. In the default HUD it's less noticeable because the item model and the war paint panels are vertically stacked, where as here it's horizontal. I don't mind the change and like you said, majority of people won't even go to that screen anyway.
