### ISSUE TITLE
Arena notification panel has cutoff text

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/flawhud#317]
![image](https://user-images.githubusercontent.com/123919000/229347252-ce960679-53de-4dec-8505-cc6a24209800.png)

The  box that appears while playing arena mode or any of its community variations (deathrun, saxton hale) is currently broken,  most of the text is cut off

**Comment by CriticalFlaw** [comment]
Fixed in 4e2ed69487108492e15443a4ee7ca1b4bbf50d68. Thank you for reporting.
![20230402103012_1](https://user-images.githubusercontent.com/6818236/229359437-187d20c6-fc1d-499e-85f1-35d13a0747e1.jpg)
