### ISSUE TITLE
Change the font of description/name tags inputs

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/flawhud#319]
This is kinda hard to explain but

![image](https://user-images.githubusercontent.com/123919000/230452066-84a102d6-08d4-4e19-bf4a-e43c76ae48a5.png)

(This screenshot is from the default hud, I have no footage of it on flawhud and I dont have any name/description tags on hand)

This box here where you input a new item name or a new item description with name tags is using the tf2 build font which is all uppercase so its hard to see whether you are putting in lower case or upper case characters I would change it to tf2 secondary font

**Comment by CriticalFlaw** [comment]
Reverted font change in f01da8c2ecb8db8d499a0363b5b3928b788b759f.

![20230408143727_1](https://user-images.githubusercontent.com/6818236/230737596-9e9da99d-be14-4d19-bc75-5b29062952d1.jpg)
