### ISSUE TITLE
Slight cutoffs on the MVM failed screen

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/flawhud#321]
![image](https://user-images.githubusercontent.com/123919000/230734522-efe6686c-70ed-4193-b30f-609f53b84cd8.png)

On this screen the mission summary text is sorta overlapping with the credit collection and credit use text and where it says mann co. anti robot tips its slightly cut off

May be a issue with my resolution 1440p but I am not sure I havent tried other resolutions

**Comment by CriticalFlaw** [comment]
Didn't capture a screenshot but the header text position is slightly higher and wide to match the "Wave X Failed" text. Thanks
