### ISSUE TITLE
Spectator text highlighted before joining a team

### ISSUE THREAD

**Issue by nigiriemoji** [CriticalFlaw/flawhud#324]
Hi I noticed when I'm just checking out the scoreboard in the team selection screen that the spectator text is highlighted. I press tab to see scoreboard

This is windows 11, 2560x1440 display

![20230428214834_1](https://user-images.githubusercontent.com/53108354/235287392-dcae0637-196b-42be-8802-64e13760fcbc.jpg)
![20230428214842_1](https://user-images.githubusercontent.com/53108354/235287391-a422d755-e4be-4a97-82bc-901514a88334.jpg)

**Comment by nigiriemoji** [comment]
Additional pic
![20230429235050_1](https://user-images.githubusercontent.com/53108354/235339906-02d25a56-84b4-4694-b320-bdfa84026e2d.jpg)

**Comment by CriticalFlaw** [comment]
I'm not able to reproduce this on the latest version. Joined a server, went to the team selection page then pressed tab. Tried it also with other bots on the team.

Next time you encounter this, see if `hud_reloadscheme` fixes it.
![20230430223148_1](https://user-images.githubusercontent.com/6818236/235393434-57e2e5fb-d3b2-48dd-af42-7cc314c9f5ff.jpg)
![20230430223149_1](https://user-images.githubusercontent.com/6818236/235393438-bff64cd9-1ee3-48a3-9cf3-9e48d438ddf8.jpg)

**Comment by CriticalFlaw** [comment]
Closing after no response. See above investigation.

**Comment by impale1** [comment]
The same thing can be done in this way:
1. Open mvm upgrade menu
2. Open scoreboard
![440_20230915195616_1](https://github.com/CriticalFlaw/flawhud/assets/117596825/60a1e265-e12c-4433-9d3b-cc490137cd31)

**Comment by CriticalFlaw** [comment]
That sounds like a game bug. As in you're not supposed to be able to open both
