### ISSUE TITLE
Medigun bar off center on centered mode

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/flawhud#325]
![ee](https://user-images.githubusercontent.com/123919000/235504981-96077421-f5c8-40d6-b25f-a32a2c64fe7b.png)

Medigun bar off center on centered mode

**Comment by CriticalFlaw** [comment]
Fixed in the editor here: [b3091f5b35f2ddd4da1bbfd1cd99891350f271d0](https://github.com/CriticalFlaw/TF2HUD.Editor/commit/b3091f5b35f2ddd4da1bbfd1cd99891350f271d0)

Will be included in the next release, whenever that is.
