### ISSUE TITLE
Loadout player model breaks when playing on macOS

### ISSUE THREAD

**Issue by ricardobane** [CriticalFlaw/flawhud#329]
Hello, I play on Mac. Every time I rotate the character in the "item" section the pov change.

![fix](https://user-images.githubusercontent.com/114844957/236737840-b7ca7e39-9ecb-4181-8143-ca8b3026e128.png)

**Comment by CriticalFlaw** [comment]
Likely a game issue. Cannot be fixed with HUD files.
