### ISSUE TITLE
Inconsistence with Close Game menu

### ISSUE THREAD

**Issue by thejaviertc** [CriticalFlaw/flawhud#333]
When you click the Close Game button, the text that displays is not centered:
![imagen](https://github.com/CriticalFlaw/flawhud/assets/45662206/78a543b3-e168-4cb8-af96-da7e350ba62b)

Other similar menus are centered, like the Exit Match:
![imagen](https://github.com/CriticalFlaw/flawhud/assets/45662206/8d9666e8-7459-4be2-bcf7-6a22819a5f0f)

**Comment by CriticalFlaw** [comment]
This has something to do with how panels are set up to share the same file. How does it look on default?

**Comment by thejaviertc** [comment]
> This has something to do with how panels are set up to share the same file. How does it look on default?

Do you mean the default hud? If is that's it, it looks centered.

![imagen](https://github.com/CriticalFlaw/flawhud/assets/45662206/9f7dac6a-cc59-4bc5-bb0f-e147e751082e)

**Comment by CriticalFlaw** [comment]
I vaguley recall that panel being tied to something else, where if you modify one the other gets messed up. Otherwise I feel like it would have been fixed by now.

**Comment by CriticalFlaw** [comment]
This panel is somehow tied to the confirmation dialog shown before applying a war paint. I've tried getting the two to display properly but either the quit dialog appears slanted to the left or the war paint dialog is cut off. This is too minor to invest too much more time into it imo
