### ISSUE TITLE
Voice chat not working correctly 

### ISSUE THREAD

**Issue by BradCrays** [CriticalFlaw/flawhud#334]
I just downloaded Flawhud and I did all of the steps correctly to downloading it. I launched TF2 and the hud worked fine. All of the UI and functions like reloading the hud, changing dmg color ect. were working. But when someone started to chat in the voice chat it was very loud and distorted and I couldn't make anything out of what they were saying. But when I uninstalled the mod however, it worked fine the voice chat worked normally. So please can you fix this bug as soon as possible. And if there is already a fix please tell me in any way. And as always, thank you!

**Comment by CriticalFlaw** [comment]
HUD files do not change the quality or volume of the game audio. You can check the volume slider in the HUD Tools menu (wrench icon on the right hand side of the main menu) or also check your other mods.

These are the only cvars that are executed when launching the game with this HUD but I don't see anything that could cause audio issues. https://github.com/CriticalFlaw/flawhud/blob/master/cfg/valve.rc
