### ISSUE TITLE
Weapons description/stats view not fully showing on killcam freeze shot

### ISSUE THREAD

**Issue by nigiriemoji** [CriticalFlaw/flawhud#335]
After getting killed by someone you get a killcam view of the person who killed you. The bottom right section shows a weapon and it's stats/description with it. But sometimes the textbox is too big and a bottom portion of the weapons textbox is now off screen. I'd say it's about 33% of the weapons textbox off screen.
I'm unfortunately unable to screenshot this, it goes away too fast for me to react.

I use 2560x1440p resolution

**Comment by CriticalFlaw** [comment]
After some testing it turns out to be a game bug that is fixed with `hud_reloadscheme` or using the Refresh HUD button on the main menu. It forces the item panel to use the intended ypos value. Thank you for reporting the issue but there's nothing to be changed on this side.

**Comment by nigiriemoji** [comment]
I see. Thanks for the explanation. I guess I will probably have to bind that command to run it whenever I see the issue, or maybe have it auto run at game launch

**Comment by CriticalFlaw** [comment]
I have it bound because it always comes in handy for quick-fixes. Cheers.
