### ISSUE TITLE
Ubercharge meter covers some text on 2560x1440

### ISSUE THREAD

**Issue by nigiriemoji** [CriticalFlaw/flawhud#336]
Hello I did a reinstall of flawhud via the tf2 hud editor today and when healing others as medic, my teammate's ammo counter is covered by the ubercharge meter and some of the weapon name text.

I use a 2560x1440 resolution

Below are a few examples + my tf2 hud editor settings for flawhud.

![20230603204645_1](https://github.com/CriticalFlaw/flawhud/assets/53108354/a6b4eb5a-a14f-490e-a528-ecde818277b0)
![20230603205219_1](https://github.com/CriticalFlaw/flawhud/assets/53108354/08e56795-bd3a-40a6-a83a-0ff1437c7c96)
![20230603205216_1](https://github.com/CriticalFlaw/flawhud/assets/53108354/83f15e16-2e19-474d-baf5-b171d1b514f1)
![20230603205211_1](https://github.com/CriticalFlaw/flawhud/assets/53108354/6a9207fd-be19-4b41-9106-9f49b9dbaf2a)
![20230603205203_1](https://github.com/CriticalFlaw/flawhud/assets/53108354/066fd25c-5efa-4f45-a149-9c6cd5dd7e86)
![20230603204656_1](https://github.com/CriticalFlaw/flawhud/assets/53108354/8d97e6c3-cb0a-4808-8559-4bffa483b713)
![image](https://github.com/CriticalFlaw/flawhud/assets/53108354/526c7715-3dfb-475e-a4ad-c8cae0ababf2)

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/CriticalFlaw/TF2HUD.Editor/commit/0aac21dbddae037e7caab9e23961c9a7873a24c0. Download the latest schema update and try again please.
