### ISSUE TITLE
Vaccinator meter misplaced after recent layout changes

### ISSUE THREAD

**Issue by h9lk** [CriticalFlaw/flawhud#337]
After so many years?! - Always!!! :smiling_face_with_three_hearts:

after the latest version v2023.0402 experience display broke (1920x1080 16:9)
![20230606174401_1](https://github.com/CriticalFlaw/flawhud/assets/32390006/edb988e5-90e9-4ba9-b8de-065a61348044)

and vacc
![20230606190240_1](https://github.com/CriticalFlaw/flawhud/assets/32390006/0dcea9a7-3839-4e81-ae14-629926d78cf5)

tried reinstalling hud and reloading hud circuit

**Comment by CriticalFlaw** [comment]
The vaccinator meter is fixed here: 0dc899fdd597968172dd0a25c48366499eaee43e

I don't see what the issue is in the first screenshot

**Comment by h9lk** [comment]
> The vaccinator meter is fixed here: [0dc899f](https://github.com/CriticalFlaw/flawhud/commit/0dc899fdd597968172dd0a25c48366499eaee43e)
> 
> I don't see what the issue is in the first screenshot

before update strip experience was like this
![image](https://github.com/CriticalFlaw/flawhud/assets/32390006/ea5dd382-b52b-4ba2-b93c-8ced91313ff3)

**Comment by CriticalFlaw** [comment]
It moved because of how the HUD files are interlocked with other UI elements - like part of that panel is used for matchmaking stats. It's not broken.
