### ISSUE TITLE
Thermal Thruster Charges overlap with Phlog Mmph bar

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/flawhud#338]
![image](https://github.com/CriticalFlaw/flawhud/assets/123919000/767ffe88-8d67-4841-9e31-8fec3fc8ee54)

**Comment by CriticalFlaw** [comment]
Fixed in ffd92d5a6a0df5d9c1f2027b3f4cca4d8bd038d4. Thanks for reporting.

**Comment by impale1** [comment]
again
![440_20231005162614_1](https://github.com/CriticalFlaw/flawhud/assets/117596825/e0d3fef0-0a1e-4af4-857e-b33cfadb3122)

**Comment by CriticalFlaw** [comment]
Corrected now. Thanks
