### ISSUE TITLE
Bottom of ammo box is flat

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/flawhud#339]
![image](https://github.com/CriticalFlaw/flawhud/assets/123919000/a1fb3474-89a1-45dc-b198-773562478125)

The bottom of the black shadow box behind the Ammo is completely flat while the box behind the HP is rounded, Slight inconsistency

**Comment by CriticalFlaw** [comment]
Fixed in ffd92d5a6a0df5d9c1f2027b3f4cca4d8bd038d4. Thanks for reporting.
