### ISSUE TITLE
New Background Wallpaper

### ISSUE THREAD

**Issue by CriticalFlaw** [CriticalFlaw/flawhud#34]

**Comment by CriticalFlaw** [comment]
Completed in https://github.com/CriticalFlaw/flawhud/pull/37/commits/0b45c6031ba13170852636fe2185a5e65f31bbe5

**Comment by Tiagoquix** [comment]
What file redirects the HUD to use `background_upward_widescreen` instead of `background_upward`?

**Comment by CriticalFlaw** [comment]
It's in the source code for when using certain resolution.
