### ISSUE TITLE
Overlapping bow and jarate charge bar

### ISSUE THREAD

**Issue by thejaviertc** [CriticalFlaw/flawhud#341]
When you use the bow and jarate, the charge bars overlap

![imagen](https://github.com/CriticalFlaw/flawhud/assets/45662206/abe186bb-df91-43db-960f-37aa2dee45e2)

**Comment by CriticalFlaw** [comment]
Fixed in ed37348d2003f45859bff2df93fba0b3b93e88fa. Thanks!
