### ISSUE TITLE
(Suggestion) Add shadow behind HP gained text above the health

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/flawhud#342]
![image](https://github.com/CriticalFlaw/flawhud/assets/123919000/da5d08d3-adca-4af6-a1f2-d64896f84fde)

The damage value has a shadow but the HP gained does not which is just another slight inconsistency

**Comment by CriticalFlaw** [comment]
I'll check but it may not be possible because of how health gained does not function the same way as damage dealt

**Comment by CriticalFlaw** [comment]
Adding a dropdown is not possible. Closing.
