### ISSUE TITLE
Medigun Target ID Ammo Issue

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/flawhud#343]
![image](https://github.com/CriticalFlaw/flawhud/assets/123919000/70ac7371-461b-4d51-bee6-b4c5ea789771)

There's a big awkward space between the targets ammo count and the ammo icon, and I doubt this is intentional

**Comment by CriticalFlaw** [comment]
Slightly adjusted in ed37348d2003f45859bff2df93fba0b3b93e88fa
