### ISSUE TITLE
Engineer Metal Counter overlaps name of medic that's healing me (2560x1440)

### ISSUE THREAD

**Issue by nigiriemoji** [CriticalFlaw/flawhud#346]
Hi I use latest flawhud on 2560x1440 display. The engineer metal number covers the healed by box on the hud.
Thanks always for getting to the issues!

![20230610232956_1](https://github.com/CriticalFlaw/flawhud/assets/53108354/4d6dc6cd-a154-46d0-ada2-5f198d69d688)

**Comment by CriticalFlaw** [comment]
This looks to be an issue with the editor because in the live version the metal counter is already lowered.

**Comment by nigiriemoji** [comment]
Here's my tf2 hud editor settings for reference

![image](https://github.com/CriticalFlaw/flawhud/assets/53108354/5d28608b-9c53-4464-b685-b14a2bb9edad)

**Comment by CriticalFlaw** [comment]
I'm not able to replicate the issue on my end. Can you do a reinstall of flawhud on your end and reapply the customizations?

**Comment by nigiriemoji** [comment]
seems to be fine after doing that, thanks
