### ISSUE TITLE
Vaccinator Uber icons cut off

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/flawhud#348]
![image](https://github.com/CriticalFlaw/flawhud/assets/123919000/fb6bbcb0-88c9-4676-814a-39a5645cf3db)

The icons for the vaccinator are cut off

**Comment by CriticalFlaw** [comment]
Fixed in edb8dae2b925c42a1aa7590958d14f8a2f8fde6b. I had to move the icon to the side to accomodate the MvM shield meter. Thank you for reporting the issue.
![20230715002928_1](https://github.com/CriticalFlaw/flawhud/assets/6818236/cbb9688d-0772-4b66-bab3-19a31d571b68)
