### ISSUE TITLE
Latest build Overlaps with some of VScript VSH's HUD elements

### ISSUE THREAD

**Issue by HueyCan** [CriticalFlaw/flawhud#349]
Using the centered version of Flawhud will have some HUD elements be covered up by the HUD used in VScript VSH

v2023.0610
![2023 0610_centered](https://github.com/CriticalFlaw/flawhud/assets/31521545/a8566386-bc3d-4d37-91a7-a5c4609ee271)

The last version did not have this issue though

v2023.0402
![2023 0402_centered](https://github.com/CriticalFlaw/flawhud/assets/31521545/fee0ec8d-1867-4a3c-8562-07471b55a01b)

There's also the heal target UI being covered up when using the cornered version
![2023 0610_cornered](https://github.com/CriticalFlaw/flawhud/assets/31521545/9574c9c9-7876-48fe-ab2d-76ac3b88f96f)

Even though there's a file inside the map named "vsh_hud.res", packed map content currently isn't modifiable so the position of VScript VSH's UI elements isn't changeable at the moment

**Comment by CriticalFlaw** [comment]
I don't plan on moving HUD elements around for just one gamode. Best hope is that the baked-in VSH hud elements become modifable.

**Comment by CriticalFlaw** [comment]
I honestly don't understand why they put the player mode counter at the bottom of the screen whereas in arena its at the top.

**Comment by CriticalFlaw** [comment]
Closing because this should be corrected with the HUD elements baked into the map and moved to the top of the screen.
