### ISSUE TITLE
Add badges to winpanel.res

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/flawhud#350]
After the recent flawhud updates, there is enough room to add the badges back in
![flawhud](https://github.com/CriticalFlaw/flawhud/assets/117596825/6370ce1e-722b-4c92-9992-cb6e81c895ea)
![default](https://github.com/CriticalFlaw/flawhud/assets/117596825/6c7da896-0a1d-40c3-97b7-06fb48e341c0)

**Comment by CriticalFlaw** [comment]
The winpanel size has not changed in many years. The reason they are omitted is because they leave a gap when playing on non-valve servers - this is an intentional design change.
