### ISSUE TITLE
Disguising overlaps the playermodel, health and weapon name over the Achievements progress

### ISSUE THREAD

**Issue by VanDurBeak** [CriticalFlaw/flawhud#351]
![Screenshot (63)](https://github.com/CriticalFlaw/flawhud/assets/72037706/13ae2fb6-22d9-4676-a204-c69a5ca54ddc)

Encountered this right after upgrading to v2023.0610

**Comment by CriticalFlaw** [comment]
Fixed in d97f071caa7798820165c99fd726393a73332250. Redesigned the disguise panel and moved the MvM cash meter as they would overlap on lower resolutions. Thank you for reporting.

![image](https://github.com/CriticalFlaw/flawhud/assets/6818236/070676b1-2889-407a-8182-4aa8dedd4b4b)
