### ISSUE TITLE
Scoreboard badges stay on screen when scrolling through player names

### ISSUE THREAD

**Issue by VanDurBeak** [CriticalFlaw/flawhud#352]
![Screenshot (62)](https://github.com/CriticalFlaw/flawhud/assets/72037706/8f714ac7-659d-450b-b74b-d17ebe350b59)

**Comment by CriticalFlaw** [comment]
Does this happen on the default hud?

**Comment by VanDurBeak** [comment]
Okay I see now. I tested it on a default HUD and it is an actual bug with the game.
