### ISSUE TITLE
Killstreaks numbers cut-off at very high values

### ISSUE THREAD

**Issue by Platina6978** [CriticalFlaw/flawhud#354]
See attached screenshot, I've noticed that the counter for the killstreak number gets cut-off on the right side when this number gets too high (2 digit seems fine, 3 digit seems to cause issues).
Using centred version of the HUD.
![20230723213935_1](https://github.com/CriticalFlaw/flawhud/assets/71837773/78c8e84b-c2c1-4394-94a0-6d0adec0bf41)

**Comment by CriticalFlaw** [comment]
Should be an easy change. Will add it in, thanks.

**Comment by CriticalFlaw** [comment]
Fixed in 231ff91342683c7ed5565adeb065f7474002f7ba. Thank you for reporting.
