### ISSUE TITLE
Saxton Hale health numbers cut-off when has high values

### ISSUE THREAD

**Issue by thejaviertc** [CriticalFlaw/flawhud#355]
Botton left health, not the top centered one.

![imagen](https://github.com/CriticalFlaw/flawhud/assets/45662206/5c85fee5-81cb-4d56-a1fa-432841ec5bc0)

**Comment by CriticalFlaw** [comment]
The best I could do is slightly lower the size of the font used for health and ammo, but that probably won't fully solve the issue unless the size is reduced significantly or I greaterly expand the bounding boxes.

**Comment by CriticalFlaw** [comment]
I'm in general not big on making big changes to accomodate one game mode, esspecially if there's a chance it won't be around forever.
