### ISSUE TITLE
Textbox position too high + White Background Health/Ammo Counter (2560x1440)

### ISSUE THREAD

**Issue by nigiriemoji** [CriticalFlaw/flawhud#356]
Hello,

I did a reinstall and reset changes and reapplied my changes to latest flawhud via the latest update of tf2 hud editor (latest as the last 15 minutes). I currently have 2 issues that is different from the previous update. I use flawhud on a 2560x1440 display

1. Lower Text Box currently brings the textbox center, not like the lower 1/3rd of the screen as it was prior. I also included screenshot of the textbox when lower option is OFF. It feels very high for a normal textbox, unsure
2. Health and Ammo meter white background. I did a reset of my tf2 hud settings for flawhud, then reselected them again and applied. I didn't touch any of the colors on the left side of the menu

This one is how it is now
![20230729203924_1](https://github.com/CriticalFlaw/flawhud/assets/53108354/26d8b65c-8424-4c50-86ab-88aa4eb4d335)

How it looks with Lower Text Box OFF
![20230729204439_1](https://github.com/CriticalFlaw/flawhud/assets/53108354/3c072066-4d18-4730-be47-97d52f755f13)

Where the previous version textbox location is
![20230717173403_1](https://github.com/CriticalFlaw/flawhud/assets/53108354/b805730a-8e9b-47d8-ac25-30ede8f486a6)

**Comment by CriticalFlaw** [comment]
In the editor, switch the download from `stable` to the `dev`.

The editor schema is for a version of flawhud that's releasing tomorrow (2023.0730)

**Comment by nigiriemoji** [comment]
Confirming that it the white box went away on the dev build. Will update sometime tomorrow and try on stable build afterwards!

I have some slight overlap in the when aiming at a teammate or engi building
![20230729220027_1](https://github.com/CriticalFlaw/flawhud/assets/53108354/65fc787d-5980-49fa-86e8-2b67e5cf8981)

Also, on the dev build the voice speaker icon isn't quite center height in the rectangle
![20230729220542_1](https://github.com/CriticalFlaw/flawhud/assets/53108354/d2bcebb3-5057-4e58-b662-e24ca03645e3)

**Comment by CriticalFlaw** [comment]
#1 I may still revise in the future, but the reason for its new position has to do with the inclusion of the achievement tracker which your screenshot does not show.

![20230730093741_1](https://github.com/CriticalFlaw/flawhud/assets/6818236/63d68147-ec03-4484-a594-001412125011)

All three need to co-exist and the previous layout overlapped with the character portraits, so I'm giving this one a try for now.

#2 should now be resolved. The editor was not pointing to the latest released version of flawhud (2023.0730). I'd advised doing a clean reinstall of the HUD after you receive the schema update notification.

The target ID placement was corrected in the schema. The voice indicator was corrected in the HUD files. A clean reinstall using the `stable` branch should resolve these issues. Thanks
