### ISSUE TITLE
Health of disguised player is cut off?

### ISSUE THREAD

**Issue by Dragonissa** [CriticalFlaw/flawhud#360]
Whatever this is supposed to be (health of disguised?) is cut off

![image](https://github.com/CriticalFlaw/flawhud/assets/4233773/fb33b16c-a1ec-4988-90d6-e246dd83cd82)
![image](https://github.com/CriticalFlaw/flawhud/assets/4233773/92629a1e-135b-4448-a963-e89a13ab887a)

**Comment by CriticalFlaw** [comment]
This has already been fixed in the editor here: https://github.com/CriticalFlaw/TF2HUD.Editor/commit/4731deb8a13f27f8ed57fdd20778a15dbbfbfe66

**Comment by Dragonissa** [comment]
Ah okay. After reinstalling it worked.
![image](https://github.com/CriticalFlaw/flawhud/assets/4233773/5ae9c3d9-8dcc-4e95-a8bf-01c16126d6ca)
