### ISSUE TITLE
Switching PDA menus causes frame drops

### ISSUE THREAD

**Issue by ScratchyNuts** [CriticalFlaw/flawhud#361]
It happens with some other HUDS, and some don't have this issue. However, I haven't seen anyone else report an issue like this. It could be a me issue, but just to be sure I wanted to report it. Thanks for reading :)

**Comment by CriticalFlaw** [comment]
I'm aware of this causing frame drops but not if there is an actual fix for it. Which HUDs do not have this issue?

**Comment by ScratchyNuts** [comment]
> I'm aware of this causing frame drops but not if there is an actual fix for it. Which HUDs do not have this issue?

Some that I've recently used and don't have this issue are ToonHUD, Middle Mann Centered HUD, SpaceHUD, TF2 HUD Fixes, 7Hud, and NostalgiaHUD

If you're interested, some other HUDs I've used that have this issue are PeachHUD, HypnotizeHUD, SunsetHUD, and MonoHUD

**Comment by CriticalFlaw** [comment]
I'd have to ask around on the huds.tf discord because briefly looking at the huds that don't have this issue - nothing stands out that directly addresses the issue.

**Comment by CriticalFlaw** [comment]
According to other developers this is _possibly_ caused by use of #base in the PDA files. This was done to help with maintaining those files, but if it can be proven that they do infact cause frame-drops (by removing those files and using the default PDA) then I'd consider reverting the #base use.

**Comment by ScratchyNuts** [comment]
> According to other developers this is _possibly_ caused by use of #base in the PDA files. This was done to help with maintaining those files, but if it can be proven that they do infact cause frame-drops (by removing those files and using the default PDA) then I'd consider reverting the #base use.

If this alot to ask for, but how can I find the PDA files. I'm stuck on what do you do with the #base files because I can't tell if you delete them or you're saying to delete them then put it back in? (sorry for the bad wording lol)

**Comment by CriticalFlaw** [comment]
The PDA files are located in the following folders:
- `flawhud\resource\ui\build_menu`
- `flawhud\resource\ui\build_menu_360`
- `flawhud\resource\ui\build_menu_sc`
- `flawhud\resource\ui\destroy_menu`

**Comment by ScratchyNuts** [comment]
so do i remove those files and then do something else?

**Comment by CriticalFlaw** [comment]
You can try removing it then switch PDAs to see if the framedrops still occur. You'll have an unsable PDA menu but at least we'll prove a theory.

**Comment by ScratchyNuts** [comment]
https://github.com/CriticalFlaw/flawhud/assets/141075436/8c078d3b-bb22-4c16-8e98-693729585fcb

I tried but it didn't work :( I've linked a vid to show what the frame drop looks like

**Comment by CriticalFlaw** [comment]
Can you show a similar video with the default hud please?

**Comment by ScratchyNuts** [comment]
Also sorry for the compression. Github wont upload anything abv 10mb

https://github.com/CriticalFlaw/flawhud/assets/141075436/0b856a91-64b1-4dae-8daf-9977720d942e

**Comment by CriticalFlaw** [comment]
Interesting note, if you hide the hud using `toggle cl_drawhud` - the lag persists even though nothing is being rendered on screen.

**Comment by ScratchyNuts** [comment]
I don't know how to say this since I don't make HUDs, but could it do with how big the file size of the HUD is? Also, that Middle Mann HUD I mentioned earlier that didn't have this issue now drops frames when I switch between the PDAs. So weird :/

**Comment by CriticalFlaw** [comment]
I did some dumb tests where I kept removing files and restarting. Could you please try deleting `flawhud/cfg/valve.rc` and test again? That files was added to middleman hud recently so I just wanted to see if you could tell a difference

**Comment by ScratchyNuts** [comment]
Good news, removing the valve.rc file doesn't cause the frame drops. However, I don't know it's purpose and if it negatively affects the game at all

**Comment by CriticalFlaw** [comment]
It's main purpose is to ensure that Streamer Mode is not enabled at launch (`cl_hud_minmode 0`). If you don't use that mode or refresh the HUD frequently, it can be removed without other side-effects. Unfortunately it will need to be kept in the HUD because otherwise, users who use minmode will always load into Streamer Mode with flawhud.

**Comment by ScratchyNuts** [comment]
I do use minmode unfortunately, but I don't know how much it negatively affects my game

**Comment by CriticalFlaw** [comment]
It won't be an issue because you can turn off streamer mode in the hud settings. It's just an inconvinience.

**Comment by impale1** [comment]
Perhaps he should also check by deleting each command in the `valve.rs` file in turn

**Comment by impale1** [comment]
I changed the value of the `vgui_cache_res_files` command to `1`, and the game stopped lagging

**Comment by ScratchyNuts** [comment]
How do I open rs files?

**Comment by impale1** [comment]
double-click on the file and then you have to select the notepad application

**Comment by CriticalFlaw** [comment]
Yeah it looks to be tied to vgui_cache_res_files. Changing between 0 and 1 has a noticeable lag when switching PDTs.

**Comment by ScratchyNuts** [comment]
Thanks for the help
