### ISSUE TITLE
Certain "Heads" and "Killstreak" values are cut off

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/flawhud#363]
![image](https://github.com/CriticalFlaw/flawhud/assets/123919000/33ee642b-3863-4ea4-8914-822940949e77)

The value for killstreaks and heads with the eyelander or frontier justice revenge are cut off at value 10 and above

Tested on both 1080p and 1440p (both have same issue)

Demomans stickies are fine, even with the 14 stickies of the Scottish Resistance

**Comment by nigiriemoji** [comment]
Can confirm. Not every double digit killstreak number is displayed. Some examples as medic:
![20230801174656_1](https://github.com/CriticalFlaw/flawhud/assets/53108354/13684ead-5304-434d-a8b5-3129843b921f)
![20230801174445_1](https://github.com/CriticalFlaw/flawhud/assets/53108354/0717aa78-3d38-4aeb-a3fd-b663f80ae0a6)
![20230731180124_1](https://github.com/CriticalFlaw/flawhud/assets/53108354/3112dbf1-0943-4d60-a17f-78febc87f800)

![20230801181731_1](https://github.com/CriticalFlaw/flawhud/assets/53108354/1997330a-3787-4332-ae83-3b85e0d8f2a2)

**Comment by CriticalFlaw** [comment]
Fixed in d8649ce764ff3d5a765167e3bec0a7356e36ddd9. Please retest.

**Comment by Presto06** [comment]
> Fixed in [d8649ce](https://github.com/CriticalFlaw/flawhud/commit/d8649ce764ff3d5a765167e3bec0a7356e36ddd9). Please retest.

Numbers are fixed however the sticky counter isnt there for me even with stickies on the floor

![image](https://github.com/CriticalFlaw/flawhud/assets/123919000/5e1ed079-310e-4557-b3f1-d3ba0dcfc20f)

**Comment by CriticalFlaw** [comment]
Please test with a clean version without applying editor customizations. The schema has not been updated yet.

**Comment by Presto06** [comment]
> Please test with a clean version without applying editor customizations. The schema has not been updated yet.

OK just downloaded it from github (not hud editor) everything seems perfect now

![image](https://github.com/CriticalFlaw/flawhud/assets/123919000/86f3d0a2-3a97-4cec-867d-1c95f51a45e7)

**Comment by Presto06** [comment]
![image](https://github.com/CriticalFlaw/flawhud/assets/123919000/20e653d6-2630-43d9-b700-b7a5fa38e1ba)

Also tested killstreaks of 100+ and they seem fine (lol)

**Comment by CriticalFlaw** [comment]
Thanks for retesting. Closing.
