### ISSUE TITLE
Switching to melee weapon hides charge meter for demoman

### ISSUE THREAD

**Issue by Dragonissa** [CriticalFlaw/flawhud#364]
Version: v2023.0730
Screen resolution: 2560x1600 (16:10)

![image](https://github.com/CriticalFlaw/flawhud/assets/4233773/6174b3ed-b47d-4ad0-ac4a-e2e04e69a368)
![image](https://github.com/CriticalFlaw/flawhud/assets/4233773/69126a3a-0217-488f-a8ee-0925b119f12c)

**Comment by CriticalFlaw** [comment]
Fixed in cc3f29c2ac74beef6317242edbe44b940bfc2680. Please retest
