### ISSUE TITLE
Editor schema mismatches live version

### ISSUE THREAD

**Issue by WishMount** [CriticalFlaw/flawhud#365]
Hi there, 

I downloaded the latest schema, and now I have a similar issue to what I had previously in relation to health + ammo colour/background. I have coloured text, and centered checked in the boxes, however the HUD still places a blank white box behind the text. Screenshots are displayed below 
![image](https://github.com/CriticalFlaw/flawhud/assets/122709014/54e9dbc7-bc99-441b-a959-90ff8ab0580c)
![20230803101716_1](https://github.com/CriticalFlaw/flawhud/assets/122709014/2fee0c34-7dd7-4fcb-bd73-591d40d92c8a)

**Comment by CriticalFlaw** [comment]
Try clicking on `Reinstall` then `Apply Changes`. You likely have an old version of flawhud installed.

**Comment by WishMount** [comment]
Issue still persists! Did a hard uninstall/reinstall and still have the random box behind the numbers. -

**Comment by CriticalFlaw** [comment]
You should have received a schema update that removes the above "Download" option - because right now it's using a version of flawhud that does not match the editor schema. Alternatively, if the schema update does not come up - change from the download from `Stable` to `Dev`.

**Comment by WishMount** [comment]
Bit of progress, the white blank box has now changed to a opaque black box. Honestly, it's tolerable despite it not being gone completely. Below are the current editior settings- on dev mode with the new schema update. 


![20230805195547_1](https://github.com/CriticalFlaw/flawhud/assets/122709014/a62ebb1a-a33e-49d7-863f-15a5b16ab9b2)
![image](https://github.com/CriticalFlaw/flawhud/assets/122709014/53e011c9-d795-427c-a1c3-b8c66c017364)

**Comment by Presto06** [comment]
> Bit of progress, the white blank box has now changed to a opaque black box. Honestly, it's tolerable despite it not being gone completely. Below are the current editior settings- on dev mode with the new schema update.
> 
> ![20230805195547_1](https://user-images.githubusercontent.com/122709014/258577219-a62ebb1a-a33e-49d7-863f-15a5b16ab9b2.jpg) ![image](https://user-images.githubusercontent.com/122709014/258577272-53e011c9-d795-427c-a1c3-b8c66c017364.png)

The black boxes are intentional, to remove them you can try "Colored Box" health style in the hud editor which will remove the black box around hp however if you want colored text without the boxes then you are out of luck but hopefully there will be a option for this soon

**Comment by CriticalFlaw** [comment]
Today's update matches the latest live version. Also added an option for colored health but no box. Thanks.
