### ISSUE TITLE
Demoman heads counter in bottom left of screen

### ISSUE THREAD

**Issue by tummyache123** [CriticalFlaw/flawhud#366]
![demoheads](https://github.com/CriticalFlaw/flawhud/assets/70869203/3321ebfa-0b29-453a-82f4-d0233c041b51)

1440p, charge meter now working correctly after last commit but head counter needs adjusted

**Comment by CriticalFlaw** [comment]
The placement is intention. It's supposed to show above the killstreak. This chagne has not been published in a release yet.

![20230802215325_1](https://github.com/CriticalFlaw/flawhud/assets/6818236/84421497-6efb-45d1-bf86-7d28657478bc)

**Comment by tummyache123** [comment]
ah, okay. thanks for the heads up and all your work!
