### ISSUE TITLE
when taking 10 heads as demoknight head amount turns to 1...

### ISSUE THREAD

**Issue by Polarite** [CriticalFlaw/flawhud#367]
![20230803150227_1](https://github.com/CriticalFlaw/flawhud/assets/34978332/98ee4460-c2ad-4b3c-9cb0-bafb31ed0225)
2k res nothing edited.

**Comment by CriticalFlaw** [comment]
This has already been reported and fixed here: https://github.com/CriticalFlaw/flawhud/issues/363
