### ISSUE TITLE
Demoman charge meters don't display properly

### ISSUE THREAD

**Issue by broken-usb** [CriticalFlaw/flawhud#368]
While using the new version of the Hud Demoman's Shield charge and the Stick counter doesn't show up(the charge on the stick bomb launcher still show up but without text above it), all other types of counters and charge-bars work fine except for Demoman's. I tried testing with both Dev and Stable branch but the issue persisted.

**Comment by CriticalFlaw** [comment]
This should now be fixed with the latest schema update. You'll need to reinstall the HUD from the editor and reapply the customizations.
