### ISSUE TITLE
Current In Game Text Chat Font Is Too Pixelly

### ISSUE THREAD

**Issue by floofycatto** [CriticalFlaw/flawhud#371]
The current in game text chat font is still reminiscent of the 2007's, very outdated
The obvious solution to fixing this would to just use the same font but have it, not pixelated, how do we do this?
Toonhud already offers a similar solution by giving the customization option to change the text chat font, in theory all you would have to do is drag a couple of files into the flawhud folder, and boom, cleaner chat
The current font used for the text chat is Verdana Bold, but TF2 Secondary could also be a good option because I think it would fit the consistency of the current flawhud style

**Comment by CriticalFlaw** [comment]
I agree that a TF2 Secondary font would fit the theme more. We can give it a test run though I can guarantee that someone will want the old style back meaning requiring a schema change.

**Comment by CriticalFlaw** [comment]
I'm going to merge this with #372 as they both relate to the font size and selection, both will have the same change.

**Comment by CriticalFlaw** [comment]
The file to change both the font type and size is `flawhud/resource/chatscheme.res`

I'm open to a PR with a modified version that fits the flawhud style, but this isn't something I plan to work on at this time.

**Comment by floofycatto** [comment]
thanks for the reply and info! I'm not really that experienced with TF2 huds but this would be fun to look into, I'm especially interested in this hud but this is one of the main things holding it back for me, personally, to use it, but like thats kinda the point of hud editing, to make the hud for you

**Comment by floofycatto** [comment]
Did a tiny bit of editing, this was mostly the font, the border size remains the same but I think the fact the font size is bigger makes up for it
also something I noticed when making this is the chat border overlays over the team stuff, I think that's in the base hud tho because all I did was edit the area where it said font
![image](https://github.com/CriticalFlaw/flawhud/assets/86273332/0633538a-018d-46ed-96d4-d0e0350021f1)
[chatscheme.zip](https://github.com/CriticalFlaw/flawhud/files/12268167/chatscheme.zip)

**Comment by CriticalFlaw** [comment]
Implemented in 348a030d05be51e171ecfc8f0cf38bb5735cbbe8. Thanks!
