### ISSUE TITLE
Option To Scale Chat Size?

### ISSUE THREAD

**Issue by floofycatto** [CriticalFlaw/flawhud#372]
I believe the current chat for flawhud is a little cramped and too small, I would like to have the convenience of glancing at the chat without it being too distracting from gameplay, but the current chat size feels like it makes me hyper focus, to negate this issue I suggest adding the option to maybe have 2 or 3 buttons to scale the chat size to have it feel bigger, maybe the 2nd size could increase it by 20% and the 3rd could increase it by 40%?

**Comment by CriticalFlaw** [comment]
Closing as the conversation can resume in #371.
