### ISSUE TITLE
Option to make the eyelander heads and frontier justice crits below the ammo?

### ISSUE THREAD

**Issue by MuchHigher** [CriticalFlaw/flawhud#373]
So it's kinda hard to see how many crits i have before enganging into a battle, the numbers are kinda covered with my player model.

**Comment by MuchHigher** [comment]
And i want to know how to customize the location of the health, ammo, and bar so that i can move it a little closer to the crosshair, what file should i open?

**Comment by CriticalFlaw** [comment]
Moving the head counters under the ammo would overlap them with the item meters.

The counters can be moved by updating the `flawhud/resource/ui/huditemeffect_demoman.res` file. There are no plans to add additional customization options for this in the editor besides what's already included.
