### ISSUE TITLE
Control point countdown on DeGroot Keep is misaligned 

### ISSUE THREAD

**Issue by nigiriemoji** [CriticalFlaw/flawhud#374]
Hi on degroot keep map the final control point is being displayed weirdly. There's a 60s countdown that isn't fully being displayed. Screenshots for example on 2560x1440 res

![20230823115019_1](https://github.com/CriticalFlaw/flawhud/assets/53108354/e863f568-c538-4c54-aeec-dc86ed07beb5)
![20230823114833_1](https://github.com/CriticalFlaw/flawhud/assets/53108354/feddc2f8-e02d-41b9-ab5b-65ea3bf74b78)

**Comment by CriticalFlaw** [comment]
Updated the timer in 8b2cf2501211c7d5b4e6194094270449a61ad774. Thank you for reporting.
![image](https://github.com/CriticalFlaw/flawhud/assets/6818236/84fc5526-cecb-4823-8ad1-1350b27f8377)

**Comment by nigiriemoji** [comment]
thanks a lot!
