### ISSUE TITLE
MapInfoText is too wide

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/flawhud#375]
`mapinfomenu.res` -> `"MapInfoText"`
As a result, some of the text goes off screen

Operating system: Windows 11 Enterprise 22H2
Resolution: 1920x1080

![MapInfoText1](https://github.com/CriticalFlaw/flawhud/assets/117596825/61d1ff67-66f6-4033-afdd-56cf091cc41a)
![MapInfoText2](https://github.com/CriticalFlaw/flawhud/assets/117596825/6b1eea84-0d2f-4a7c-b0c0-72f527c03875)

**Comment by CriticalFlaw** [comment]
What's the change in your second screenshot?

**Comment by impale1** [comment]
"wide" "200"

**Comment by CriticalFlaw** [comment]
Thanks. I think this likely happened because I use an ultra wide monitor. Will check later tonight

**Comment by impale1** [comment]
The solution I gave above is not good because it makes the descriptions of the other maps too narrow

**Comment by CriticalFlaw** [comment]
The ideal value might be somewhere in between then, just so it doesn't hit the very edge of the screen

**Comment by impale1** [comment]
I've checked the text of the maps in all game modes (I hope), and it seems to look fine
"wide" "278"
"tall" "208"
![20230826170934_1](https://github.com/CriticalFlaw/flawhud/assets/117596825/05314fd8-fc51-4660-b664-c212eccf0003)
![20230826171012_1](https://github.com/CriticalFlaw/flawhud/assets/117596825/3b20ec13-242f-4ba0-a1a2-32929666f2f8)

**Comment by impale1** [comment]
I tried to adjust for 16:10 too, but there the text becomes really too narrow so I think we will do only for 16:9
"wide" "204"
"tall" "265"
![20230827003859_1](https://github.com/CriticalFlaw/flawhud/assets/117596825/c6bd7f02-b34b-42f4-a0e5-24c5a24e0ebf)
![20230827003817_1](https://github.com/CriticalFlaw/flawhud/assets/117596825/bf25c1ba-543b-4906-87e4-c2cd56cf0059)

**Comment by CriticalFlaw** [comment]
I've settled on wide = 235 and tall = 250 for now.
![image](https://github.com/CriticalFlaw/flawhud/assets/6818236/2d8639c6-c635-4c38-84e5-65f277033895)
