### ISSUE TITLE
Supernova powerup meter overlaps ammo

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/flawhud#376]
`hudpowerupeffectmeter.res`
![supernova](https://github.com/CriticalFlaw/flawhud/assets/117596825/adf8dd5c-d3e1-41cf-b10d-ec3cf957cb5e)

**Comment by CriticalFlaw** [comment]
Trying overriding it's ypos value to be above the ammo

**Comment by impale1** [comment]
"ypos" "c73"
![20230826174020_1](https://github.com/CriticalFlaw/flawhud/assets/117596825/ead1751f-6522-4511-9e83-8391626a0544)
![20230826174244_1](https://github.com/CriticalFlaw/flawhud/assets/117596825/8d3cd56d-7bed-4241-90d1-7f82f0671ebc)

**Comment by CriticalFlaw** [comment]
Not really a fan of it there. Maybe under the health it would look better

**Comment by impale1** [comment]
![20230827013110_1](https://github.com/CriticalFlaw/flawhud/assets/117596825/d1af1663-3022-4cdf-a850-1ee3be1f8c33)

**Comment by CriticalFlaw** [comment]
Yeah better. Works fine for just one gamemode

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/CriticalFlaw/flawhud/pull/382. Thanks!
