### ISSUE TITLE
Intersecting HUS elements (part 1)

### ISSUE THREAD

**Issue by h9lk** [CriticalFlaw/flawhud#38]
As you can see, here the status bar money blocked improvements Power Up Canteen info
![20181103231902_1](https://user-images.githubusercontent.com/32390006/48127824-b6391980-e295-11e8-9f58-be5bda5bace3.jpg)

And this, here spell and cart, cart behind and spell cast on it - if there is any spell in this mode, then it all intersects what looks like weird
![20181104181803_1](https://user-images.githubusercontent.com/32390006/48127834-bafdcd80-e295-11e8-95fe-50851fc068de.jpg)

**Comment by CriticalFlaw** [comment]
What resolution are you on?

**Comment by h9lk** [comment]
> 
> 
> What resolution are you on?

4:3 1024x768

**Comment by CriticalFlaw** [comment]
It's been fixed in https://github.com/CriticalFlaw/flawhud/commit/a167a7126c1c1c0b24264c1d91850e9b94dafa9b

Download the latest version on here

**Comment by h9lk** [comment]
> 
> 
> It's been fixed in [a167a71](https://github.com/CriticalFlaw/flawhud/commit/a167a7126c1c1c0b24264c1d91850e9b94dafa9b)
> 
> Download the latest version on here

Very grateful for your feedback and for so fast fix my problem, i love your hud and your work on it. Thank you very much  :star:
