### ISSUE TITLE
Item meter redesign for default position (under ammo)

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/flawhud#380]
With the item meters no longer being centered and now below the ammo I feel that the item meters look too simplistic now, this wouldnt be a problem if they were still centered but now that they are under the ammo they just look weird imo

This is why I would suggest redesigning the default meters that are under the ammo while keeping the centered item meters customization still being simplistic

Since it is now under the ammo and not centered theres a lot more breathing room to make these charge bars a bit more unique and not so simplified

Huds such as toonhud and evehud have the same charge bars position and they have more going for them than Flawhud rn and still manages to look simplistic in design

Using the hud merger tool I managed to get evehuds charge bars into flawhud and to see what they look like and imo they look a lot better and this is why im suggesting to redesign the item meters for the default under ammo position (while keeping centered the same and simplified)

1 Charge Bar (FLAWHUD):
![image](https://github.com/CriticalFlaw/flawhud/assets/123919000/480070de-e5d5-4fc1-aecb-847c1ea1f31f)

2 Charge Bar (FLAWHUD):
![image](https://github.com/CriticalFlaw/flawhud/assets/123919000/520554aa-585f-4832-a55d-759d65557726)

1 Charge Bar (EVEHUD BARS IN FLAWHUD):
![image](https://github.com/CriticalFlaw/flawhud/assets/123919000/ad8c6688-350a-4586-ad18-2c00608d9d1a)

2 Charge Bar (EVEHUD BARS IN FLAWHUD) [Minor overlap but you get the point]:
![image](https://github.com/CriticalFlaw/flawhud/assets/123919000/85686b9b-838a-4583-bbf7-29bd98b2f3cd)

Imo the more stylized yet still simplistic charge bars from Evehud look a lot better when inserted into flawhud than the current bars
Am not saying to completely steal the evehud bars but just make your own and make them with a bit more flair

And for anyone who likes how they currently look make the minimal item meters option in the hud editor make them remain how they still are

Just a suggestion though would like to see your input on this change

**Comment by CriticalFlaw** [comment]
There are already options in the HUD editor to change the charge meters to their previous bulky design and also center them as they were previously. As such I don't think this change will be necessary.
