### ISSUE TITLE
Change center print font to TF2 Build

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/flawhud#381]
https://steamcommunity.com/sharedfiles/filedetails/?id=2960307167
Current text is pixelated and doesn't fit the flawhud style
![ctf_foundry0005](https://github.com/CriticalFlaw/flawhud/assets/117596825/9126ef5a-d5b5-4d2a-868d-98c178ebecab)
![ctf_foundry0006](https://github.com/CriticalFlaw/flawhud/assets/117596825/586cebab-4225-49b2-895b-363b0e162522)

**Comment by CriticalFlaw** [comment]
Try "TF2 Build" it may look and.fit better

**Comment by impale1** [comment]
![ctf_foundry0007](https://github.com/CriticalFlaw/flawhud/assets/117596825/dbd78574-24c9-425d-ba7d-68ec6b6e1724)

**Comment by CriticalFlaw** [comment]
Much better. Submit the change as a PR please

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/CriticalFlaw/flawhud/pull/382. Thanks!
