### ISSUE TITLE
Add instructions to the wiki on how to disable hd item images (Mannpower)

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/flawhud#385]
![1](https://github.com/CriticalFlaw/flawhud/assets/117596825/23cb254d-5a39-465e-9b58-af031c92d436)
You will ask: but there are already powerup on the head, why do you need another one? And I will answer that sometimes the camera can glitch and not show the powerups. (screenshot below) It's even worse when the camera is inside the player.
As for the name of the powerup on the bottom right, I found it easier to look at the picture than to read the name of the powerup.
I know how to disable hd item images, I just want other players to know how to do it.
![3](https://github.com/CriticalFlaw/flawhud/assets/117596825/d97a5691-e9a5-425d-84a4-f87d9cfa1371)

**Comment by CriticalFlaw** [comment]
I don't think writing up a wiki page for this niche issue is a good use of time. Preferably valve would just fix this issue on their end.

In flawhud, HD item images you see in game are fed from https://github.com/CriticalFlaw/flawhud/blob/master/resource/ui/hudinspectpanel.res#L39 - so you can change the value to 0 but you would be disabling HD images for freezecam, spectator etc.
