### ISSUE TITLE
Killstreak icon is too narrow with some values

### ISSUE THREAD

**Issue by Wheretf2** [CriticalFlaw/flawhud#387]
When I set my killstreak to particular values, the value seems to overflow it's box and turns into #...
1-9 displays correctly, but other values that have a wider length like 10, 14, and 22 (just the few I tested) turn into #...
See screenshots for example (8, 10, 21, 22)
I tried editing huditemeffectmeter_killstreak.res thinking that was the resource in question, but to no results

![image](https://github.com/CriticalFlaw/flawhud/assets/113801019/40e9f424-3817-4ecb-9122-954964399d89)
![image](https://github.com/CriticalFlaw/flawhud/assets/113801019/9c417cd3-671f-4839-bc2a-86207b32d444)
![image](https://github.com/CriticalFlaw/flawhud/assets/113801019/ec69f71c-9e53-4279-8567-f5a23be442a7)
![image](https://github.com/CriticalFlaw/flawhud/assets/113801019/b87086b8-ab61-4aac-b9bf-ceff81ef0ddc)

**Comment by CriticalFlaw** [comment]
This has already been reported and fixed here: https://github.com/CriticalFlaw/flawhud/issues/363

Are you on the latest version? Did you install it using the editor or directly from GitHub/Gamebanana?

**Comment by Wheretf2** [comment]
I was on an outdated version, 0730
I downloaded from mastercomfig
https://mastercomfig.com/huds/page/flawhud/

The download button shows 0805, however it downloads 0730

Thank you
