### ISSUE TITLE
Scroll bar overlaps text in DetailsView

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/flawhud#389]
`storepreviewitempanel.res` -> `"DetailsView"` (and more)

Operating system: Windows 11 Enterprise 22H2
Resolution: 1920x1080

![440_20230908224150_1](https://github.com/CriticalFlaw/flawhud/assets/117596825/34b1a229-7008-494d-8e54-7a0a803f1634)

**Comment by CriticalFlaw** [comment]
Fixed in de3104bb29f4bb4c528a9731ba54c617fa441b82. Thanks.

**Comment by impale1** [comment]
has not been fully fixed, note products with particularly long text and scroll down
