### ISSUE TITLE
Intersecting HUS elements (part 2)

### ISSUE THREAD

**Issue by h9lk** [CriticalFlaw/flawhud#39]
Today i found another hud elements that intersects
![20181109201923_1](https://user-images.githubusercontent.com/32390006/48478185-99ac5c80-e814-11e8-985c-784e25422dc6.jpg)

And something uncomfortable on medic in mvm for me
![20181111191558_1](https://user-images.githubusercontent.com/32390006/48478321-058ec500-e815-11e8-8d58-a47e630c36e9.jpg)
Don't know how to others, but this line of shield on the medic - confuses me, she is in uber line and i sometimes getting lost in it, not very convenient when these two lines start to fill up, where and what to look  :sweat_smile:

**Comment by CriticalFlaw** [comment]
Oh right those, I've had to fixed but forgot then lost the changes lol

I won't be able to get those fixed until this weekend, but it should be done by then. Thanks for reporting it!

**Comment by CriticalFlaw** [comment]
Fixed. Thank you for reporting this.

**Comment by h9lk** [comment]
Hello CriticalFlaw, didn't want to create new issue, I’ll write better here - comeback from 2018 :sweat:
![20191208161028_1](https://user-images.githubusercontent.com/32390006/70390655-1db42200-19de-11ea-9910-fd8f212aa96f.jpg)

**Comment by CriticalFlaw** [comment]
Thank you for reporting this. It was an oversight from the recent changes to the TargetID.
I've corrected the issue and pushed out the fix to GitHub.
![20191208092559_1](https://user-images.githubusercontent.com/6818236/70390916-84651b80-199d-11ea-800a-5eb9a436e61a.jpg)
