### ISSUE TITLE
SpecCarriedImage is too large

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/flawhud#390]
`hudobjectiveflagpanel.res` -> `"SpecCarriedImage"`

To reproduce this, you need to spectate a player who carries intelligence

Operating system: Windows 11 Enterprise 22H2
Resolution: 1920x1080

![440_20230908222949_1](https://github.com/CriticalFlaw/flawhud/assets/117596825/705bdf59-f1f4-4211-a45c-6ee1e1dbfc54)

**Comment by CriticalFlaw** [comment]
Fixed in de3104bb29f4bb4c528a9731ba54c617fa441b82. Thanks.
