### ISSUE TITLE
RedFlag is 1 unit away

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/flawhud#391]
`hudobjectiveflagpanel.res` -> `"RedFlag"` or `"BlueFlag"`

or vice versa, I don't know.

Operating system: Windows 11 Enterprise 22H2
Resolution: 1920x1080

![440_20230908232359_1](https://github.com/CriticalFlaw/flawhud/assets/117596825/e126cbef-3f44-4066-86f1-2466aba7829c)

**Comment by CriticalFlaw** [comment]
Fixed in de3104bb29f4bb4c528a9731ba54c617fa441b82. Thanks.
