### ISSUE TITLE
Server name overlaps with scoreboard

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/flawhud#392]
Operating system: Windows 11 Enterprise 22H2
Resolution: 1920x1080

![440_20230909001603_1](https://github.com/CriticalFlaw/flawhud/assets/117596825/82db8869-dc5e-4c33-827f-bd6fd8342c88)

**Comment by CriticalFlaw** [comment]
Fixed in de3104bb29f4bb4c528a9731ba54c617fa441b82. Thanks.
