### ISSUE TITLE
Text in mvm loading screen is cutoff

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/flawhud#393]
Operating system: Windows 11 Enterprise 22H2
Resolution: 1920x1080

![440_20230909001516_1](https://github.com/CriticalFlaw/flawhud/assets/117596825/63ab0ccd-c910-4579-bf67-c5f961ab0d08)

**Comment by CriticalFlaw** [comment]
Fixed in de3104bb29f4bb4c528a9731ba54c617fa441b82. Thanks.
