### ISSUE TITLE
Competitive bugs

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/flawhud#394]
Operating system: Windows 11 Enterprise 22H2
Resolution: 1920x1080

![440_20230909225417_1](https://github.com/CriticalFlaw/flawhud/assets/117596825/716bfcf4-1fc8-4e72-a891-a224b3321be0)
![440_20230909232536_1](https://github.com/CriticalFlaw/flawhud/assets/117596825/e5feef59-7641-42c4-800f-8276c9610d38)

**Comment by CriticalFlaw** [comment]
I don't plan on playing competitive to fix these so if anyone else wants to take a stab gopher it

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/CriticalFlaw/flawhud/pull/399
