### ISSUE TITLE
Crashing every few minutes during gameplay

### ISSUE THREAD

**Issue by IceEnder03** [CriticalFlaw/flawhud#396]
I've been experiencing severe crashes every few minutes of gameplay, I tried everything to fix these crashes but nothing worked. But after some testing, I found out that your HUD is causing the lag, tried different types of HUD's and they seem to be pretty fine in terms of gameplay. And when I tested on Flawhud and there is. The crashing, every few minutes. Not sure what's causing this but You may need to fix this up right away, I really love this HUD, I've been using it for many years since I saw it. Please do whatever you can to fix the crashing. 

Thank you.

**Comment by CriticalFlaw** [comment]
I've not seen anyone else report crashes nor have I experienced it myself. Where are you downloading your copy of the HUD from?

**Comment by IceEnder03** [comment]
From your Github as always. I'd always download the latest one if it ever come's out.

**Comment by CriticalFlaw** [comment]
I'm not able to reproduce the crash. Does it happen on every map? Valve server or community?

**Comment by IceEnder03** [comment]
Both Valve and Community servers. Maybe the crashes are only occurring to me. Though in previous updates during the summer update, it was fine, I don't exactly remember when the crashing starts but it was around august it started.

**Comment by CriticalFlaw** [comment]
Is there any commonality with the crashes? Same map, class, event (point capture) etc. If it's easily replicable, record and send a demo file.

**Comment by Dragonissa** [comment]
You might wanna verify games files, or completely reinstall tf2. This just might be a conflict with other custom content or missing files.

**Comment by h9lk** [comment]
> Both Valve and Community servers. Maybe the crashes are only occurring to me. Though in previous updates during the summer update, it was fine, I don't exactly remember when the crashing starts but it was around august it started.

@IceEnder03 
Hello, please enable these settings and send me file that will be created for you after tf2 crash
```
con_enable "1" //Make sure console is enabled on start up
con_timestamp "1" //Adds timestamp so you can easily find output for when your crash is
con_logfile "cfg/tf/console_log" //Location of console log file
```

and in your Steam folder find
`\Steam\dumps`

also attach `.dmp` files
since github does not allow you to attach large archives - recommend using cloud

**Comment by CriticalFlaw** [comment]
@IceEnder03 any updates on this? If crashing still occurs please follow @h9lk's suggestion and provide the crash logs.

**Comment by CriticalFlaw** [comment]
Closing due to lack of response and no similar reports.

**Comment by CriticalFlaw** [comment]
This issue was reported again in Discord and from my troubleshooting with the demo file provided it looks to be linked to the closecaptions file. Deleting them let me play the demo without crashing

**Comment by h9lk** [comment]
> This issue was reported again in Discord and from my troubleshooting with the demo file provided it looks to be linked to the closecaptions file. Deleting them let me play the demo without crashing

@CriticalFlaw Hi, for my part would still be looking at case details. it would be interesting to see logs - from an analyst's perspective can say that you never know if problem is caused by a file, specific settings or system problems :smile:

**Comment by CriticalFlaw** [comment]
Two more crashing reports that were resolved by disabling closed captions. The captions have been removed from flawhud in 2e54d653e4d1155f0cdf478b1e4bd9b1166f40ba and will now be up to the user to install them if they want to use them.

**Comment by Dragonissa** [comment]
This is odd since i use closed captions and never had any issues since switching to flawhud 7 months ago.

**Comment by StShAzzy** [comment]
this could be perhaps due to invalid caption settings, instead of the captions themselves
