### ISSUE TITLE
[Suggestion] Flashing Ubercharge Meter

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/flawhud#398]
When Ubercharge is ready its currently just a flat color which is fine but I think it would be a lot nicer if it flashed just like when you fill the Soldier banners up to max

**Comment by CriticalFlaw** [comment]
Ubercharge already subtly changes color: https://github.com/CriticalFlaw/flawhud/blob/master/scripts/hudanimations_custom.txt#L108 and users have the option to set their own in the editor.

**Comment by Presto06** [comment]
> Ubercharge already subtly changes color: https://github.com/CriticalFlaw/flawhud/blob/master/scripts/hudanimations_custom.txt#L108 and users have the option to set their own in the editor.

Ah yeah, sorry. the flashing is pretty hard to see though and without look closing it looks like a flat color could there be an option to make it a bit more visible?
If not its ok

**Comment by CriticalFlaw** [comment]
I'd like to keep it subtle, you can change it here: https://github.com/CriticalFlaw/flawhud/blob/master/resource/scheme/clientscheme_colors.res#L41
