### ISSUE TITLE
Main Menu Bugs

### ISSUE THREAD

**Issue by CriticalFlaw** [CriticalFlaw/flawhud#40]

**Comment by Cryanthos** [comment]
![1](https://user-images.githubusercontent.com/46229328/50527558-049cb480-0a9e-11e9-96cd-f3d287d3718c.png)

The image is cut off

![2](https://user-images.githubusercontent.com/46229328/50527576-12ead080-0a9e-11e9-912e-3e867d3dd01c.png)

The dark background does not stretch to fill the entire screen.

![3](https://user-images.githubusercontent.com/46229328/50527594-2433dd00-0a9e-11e9-9b37-b185a7b1f027.png)

The text is misaligned.

I love this HUD, hope to see it continue to grow and improve.

**Comment by CriticalFlaw** [comment]
The Warning and Exit screens are borked even in the default HUD if I recall correctly. It's something that Valve broke when they've released Jungle Inferno.

The shading not covering the full screen is hard-coded unfortunately. So it can be edited to fill the screen

**Comment by Kuromu** [comment]
I'm not sure if this is some strange in-game bug i'm experiencing too, but the bar for the Soda Popper *does not appear at all* for me, i'm using the version from december 23rd from huds.tf
