### ISSUE TITLE
Update the Wiki

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/flawhud#400]
Custom crosshairs are now in the hudplayerclass.res

**Comment by CriticalFlaw** [comment]
Renamed the ticket to focus on updating and expanding the wiki as a whole.

**Comment by impale1** [comment]
Add a description of these hotkeys to the wiki, as they are not labeled in the game
![440_20231005165413_1](https://github.com/CriticalFlaw/flawhud/assets/117596825/66c66561-8448-4135-83db-b737743e3613)

**Comment by Soapsuds** [comment]
I'd also like to note there's no speedometer page on the wiki

**Comment by CriticalFlaw** [comment]
Wiki updated for the latest version. Added a misc section for the shortcut keys among others. Added a speedometer page - the wiki will updated and tweaked periodically over time.

https://github.com/CriticalFlaw/flawhud/wiki
