### ISSUE TITLE
MvM stats panel is now slightly higher

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/flawhud#403]
Operating system: Windows 11 Enterprise 22H2
Resolution: 1920x1080
![440_20230915185628_1](https://github.com/CriticalFlaw/flawhud/assets/117596825/731d8bb1-57c5-4702-80fb-fb43d6ed5eb4)

**Comment by CriticalFlaw** [comment]
Fixed in c47b1146dba39e7be361b499932a89a431723493
