### ISSUE TITLE
Abuse report notification overlapping with buttons

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/flawhud#404]
Operating system: Windows 11 Enterprise 22H2
Resolution: 1920x1080
![440_20230915212245_1](https://github.com/CriticalFlaw/flawhud/assets/117596825/7874d3fe-8308-41ae-8837-f06ce6855c35)

**Comment by CriticalFlaw** [comment]
Fixed in 677f2bf528e74de89dd45e49c05a2705c4111392

**Comment by impale1** [comment]
they're still overlapping
![440_20230916134156_1](https://github.com/CriticalFlaw/flawhud/assets/117596825/3a5bbb9c-a45b-43dd-898c-3cac4b90f36b)

**Comment by CriticalFlaw** [comment]
Check with `vgui_drawtree 1` - maybe that element is different from what I'm testing against.

![image](https://github.com/CriticalFlaw/flawhud/assets/6818236/dc936a02-86b9-48ed-89eb-23868076b665)

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/CriticalFlaw/flawhud/pull/409
