### ISSUE TITLE
Respawn label overlaps the "Your team picked up/dropped enemy intelligence" panel in CTF

### ISSUE THREAD

**Issue by Kruphixx** [CriticalFlaw/flawhud#405]
Resolution: 1920x1080

![20230915235414_1](https://github.com/CriticalFlaw/flawhud/assets/50501742/af35bc3d-b600-44d6-bb9c-e19a53b42345)

**Comment by CriticalFlaw** [comment]
Fixed in 35c15d29748d381b239b23321f7199a3d581a84c
