### ISSUE TITLE
[DEV] pomson meter overlapping with metal count

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/flawhud#410]
Operating system: Windows 11 Enterprise 22H2
Resolution: 1920x1080
![20230917151028_1](https://github.com/CriticalFlaw/flawhud/assets/117596825/e6ada678-bde8-40bb-a799-236abe5bd1a0)

**Comment by CriticalFlaw** [comment]
Dev branch is not meant for developing changes. Don't create tickets for issues that aren't in master.
