### ISSUE TITLE
Aiming at teammates briefly shows %HEA... (%HEALTH ?) before showing their actual health value

### ISSUE THREAD

**Issue by neilunger** [CriticalFlaw/flawhud#411]
I'm not sure if this is a game bug or a FlawHUD bug, but I couldn't find anything about it elsewhere, so I figured I'd file it here. 

The %HEALTH is displayed for an extremely brief period (maybe 2-3 frames on my 144hz monitor @200fps, I was very lucky to get a screenshot of it) before the proper health is displayed. 

I'm playing at 2560x1440 on Pop!_OS 22.04, linux native TF2 build, .deb Steam with MasterComfig Medium-High, and FlawHUD with all default HUD settings. 

Screenshot attached (it's from MvM but it happens in Casual too): 
![20230918222915_1](https://github.com/CriticalFlaw/flawhud/assets/31961516/d2a4f40f-7feb-40c8-8313-13dde040ccf9)

**Comment by CriticalFlaw** [comment]
That's a known game bug where at least on the first time it does not player's health in time. I think they tried to fix it in a patch couple of months ago but it still happens.

**Comment by neilunger** [comment]
I see. Thanks for the info!
