### ISSUE TITLE
Changing voice volume in hud options doesn't work

### ISSUE THREAD

**Issue by Blu-Team** [CriticalFlaw/flawhud#414]
Issue: Currently it's at 0 and when I try to make it 100 by dragging the slider to 100 it resets back to 0. Wtf? 
Version: v2023.0805 
Time of writing: 9/30/2023 (american format)
Last update as of writing: 1 week ago. I downloaded it from code then download as zip.

**Comment by CriticalFlaw** [comment]
Cannot reproduce the issue on the latest `master` branch. Does it reset while in-game and in console do you see the value change when you enter `voice_scale`?

**Comment by Blu-Team** [comment]
> Cannot reproduce the issue on the latest `master` branch. Does it reset while in-game and in console do you see the value change when you enter `voice_scale`?

Yes I was on the master branch and no voice_scale did not get affected from my testing. However, I did change the voice_scale myself before I installed this hud, maybe that's why? (I changed it because other voices and my voice was a bit quiet.)

Edit: I have not tried the latest version beta version. Also, 2023.0805 is the latest release branch which I assume to be stable.

**Comment by CriticalFlaw** [comment]
Nothing has changed relating to that setting between 2023.0805 and latest `master` branch. The only thing I can think of is either (1) it's an in-game bug or (2) there's a configuration issue.

**Comment by Blu-Team** [comment]
> Nothing has changed relating to that setting between 2023.0805 and latest `master` branch. The only thing I can think of is either (1) it's an in-game bug or (2) there's a configuration issue.

I should be able to test it in game later today. I'll edit this comment when I can play tf2. My best guess would be a mod that's messing it up.

**Comment by Blu-Team** [comment]
> Nothing has changed relating to that setting between 2023.0805 and latest `master` branch. The only thing I can think of is either (1) it's an in-game bug or (2) there's a configuration issue.

I finally remembered it. And, yes it still happens.

**Comment by CriticalFlaw** [comment]
Potential fix for this was implemented in #422 by @impale1. @Blu-Team could you please retest with the below version?

[flawhud-master.zip](https://github.com/CriticalFlaw/flawhud/files/13223597/flawhud-master.zip)

**Comment by Blu-Team** [comment]
> Potential fix for this was implemented in #422 by @impale1. @Blu-Team could you please retest with the below version?
> 
> [flawhud-master.zip](https://github.com/CriticalFlaw/flawhud/files/13223597/flawhud-master.zip)

I can change the bar if I hold left click then alt tab. However, it doesn't seem to affect anything. It almost seems like the bar is only visual (?) and doesn't do anything. If I don't alt tab it just resets back to 1.0. My biggest guess would be that my voice_scale is at 2.2 so it's bugging out the menu. I'll have to test around later today. Do you have this issue?

**Comment by CriticalFlaw** [comment]
@impale1 see the above comment and let me know if we need to revert your changes. Thanks

**Comment by impale1** [comment]
do not revert this fix because it fixes a different problem, partly unrelated to this issue

**Comment by impale1** [comment]
@Blu-Team Ok, then let's try the heavy artillery. Reset TF2 to default settings by following these instructions: https://docs.comfig.app/latest/setup/clean_up/

then install only the flawhud latest `master` branch and nothing else

**Comment by CriticalFlaw** [comment]
> > Potential fix for this was implemented in #422 by @impale1. @Blu-Team could you please retest with the below version?
> > [flawhud-master.zip](https://github.com/CriticalFlaw/flawhud/files/13223597/flawhud-master.zip)
> 
> I can change the bar if I hold left click then alt tab. However, it doesn't seem to affect anything. It almost seems like the bar is only visual (?) and doesn't do anything. If I don't alt tab it just resets back to 1.0. My biggest guess would be that my voice_scale is at 2.2 so it's bugging out the menu. I'll have to test around later today. Do you have this issue?

Also try setting voice_scale in console to 0 then try the sliders again.

**Comment by Blu-Team** [comment]
> @Blu-Team Ok, then let's try the heavy artillery. Reset TF2 to default settings by following these instructions: https://docs.comfig.app/latest/setup/clean_up/
> 
> then install only the flawhud latest `master` branch and nothing else

After doing all of that it actually works! I had to change my voice scale for it to work. Thanks!

**Comment by CriticalFlaw** [comment]
Glad to hear that. Thank you on working together to resolve this.
