### ISSUE TITLE
Make these scroll bars bigger

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/flawhud#417]
![vsh_tinyrock0018](https://github.com/CriticalFlaw/flawhud/assets/117596825/53347c1b-693a-42f3-91cd-7aedd9a5bbe6)
![snapshot0017](https://github.com/CriticalFlaw/flawhud/assets/117596825/afd97efc-dbcb-4554-a801-fbb2765dc4b5)

**Comment by CriticalFlaw** [comment]
I don't see the benefit or point in making them bigger. You can scroll using the mouse wheel anyway.

**Comment by impale1** [comment]
* is it convenient to click on them in the steam deck?
* even on pc it's more comfortable to click on the big scroll bars
* people with a broken mouse wheel will be uncomfortable

**Comment by CriticalFlaw** [comment]
> * is it convenient to click on them in the steam deck?

it's not convinient to use the mouse cursor on the steam deck throughout.

> * even on pc it's more comfortable to click on the big scroll bars

debatable because you can scroll through the page without clicking, just hover over and scroll.

> * people with a broken mouse wheel will be uncomfortable

then you still can't even scroll through your weapons. At that point the person who fix their mouse before playing.

**Comment by impale1** [comment]
If someone makes a pull request for this issue, will you accept it?

**Comment by CriticalFlaw** [comment]
sure - so long as it's not causing any other overlaps/issues

**Comment by CriticalFlaw** [comment]
Implemented in #422. Thanks
