### ISSUE TITLE
Missing lines

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/flawhud#418]
![koth_harvest_final0004](https://github.com/CriticalFlaw/flawhud/assets/117596825/30b920b3-a002-45ed-9cbd-a714127abcd2)
![koth_harvest_final0005](https://github.com/CriticalFlaw/flawhud/assets/117596825/8c248c85-6cd3-4745-b29b-f6cab6086096)

**Comment by CriticalFlaw** [comment]
Not sure where in https://github.com/CriticalFlaw/flawhud/blob/master/resource/ui/hudmatchsummary.res that line would be.

**Comment by CriticalFlaw** [comment]
Never mind that. Found it. Apparently that panel has a border whose color is the same as the panel itself. Just need to update the border schema to use the corrected dark color variant.

**Comment by CriticalFlaw** [comment]
![20231009214403_1](https://github.com/CriticalFlaw/flawhud/assets/6818236/d7649738-49de-4766-8874-a40be293be75)
