### ISSUE TITLE
Advanced options text cutoff

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/flawhud#419]
![20231010041016_1](https://github.com/CriticalFlaw/flawhud/assets/117596825/d908b5fd-8679-40a1-892f-8456f36c6871)

**Comment by CriticalFlaw** [comment]
Looks to be resolution issue or graphical glitch. Not a hud-bug.

![20231009203833_1](https://github.com/CriticalFlaw/flawhud/assets/6818236/fc60ab0d-479f-4137-ad81-858c4087ab19)
