### ISSUE TITLE
How do I add damage numbers up when hitting multiple targets?

### ISSUE THREAD

**Issue by Theepiclord911** [CriticalFlaw/flawhud#423]
Look at the image it obstructs my view so much when they don't add up ("hud_combattext_batching 1" and "hud_combattext_batching_window 2" doesn't fix it since im hitting multiple targets). Also is there a way i can make damage numbers get smaller the further away the enemy is?
![image](https://github.com/CriticalFlaw/flawhud/assets/128190523/e8e1c847-c5ad-4e81-832b-848ebce9aa76)

**Comment by CriticalFlaw** [comment]
I don't believe either one of these asks can be accomodated by the HUD. Batching is done per target and distance is not configurable in the HUD.
