### ISSUE TITLE
Map intro movies look weird/bland

### ISSUE THREAD

**Issue by Platina6978** [CriticalFlaw/flawhud#425]
See the screenshot attached below. Without the backdrop that vanilla has/had, the looks of this movie seem a little weird/off, with the sharp edges between the movie and the actual map in the background etc. This is from arena_perks, probably the same happens with other intro movies from other maps/gamemodes but I haven't checked.

![20231029230143_1](https://github.com/CriticalFlaw/flawhud/assets/71837773/93c91992-97b5-4fc7-99cf-cfb384564125)

**Comment by CriticalFlaw** [comment]
The default background for the movies does not match the flawhud theme. The current iteration aligns with other menus seen when entering a map so it will not be changed.
