### ISSUE TITLE
Update arena hybrid hud

### ISSUE THREAD

**Issue by impale1** [CriticalFlaw/flawhud#426]
Update arena hybrid hud to match the flawhud theme

The file that's responsible for this: https://github.com/Hypnootize/TF2-Default-HUD/blob/master/resource/ui/hudobjectivearenahybrid.res

Maps: `arena_lumberyard_event` and `arena_perks`.

![20231031022710_1](https://github.com/CriticalFlaw/flawhud/assets/117596825/10c6836b-ed99-4127-a456-070fcbe5d91c)

**Comment by CriticalFlaw** [comment]
Added in a8f0ee03f002f710fd21ddb85c0ac68fc9b852cb. Note that the placement of the player count is hardcoded and is too close to the "setup" and "waiting for players" labels, see screenshots below. Until they Valve makes those movable I'll leave the player count as-is. Thanks.

### Default
![20231101230904_1](https://github.com/CriticalFlaw/flawhud/assets/6818236/551500fa-cb74-4d68-a03b-4a9f1159362b)
![20231101231013_1](https://github.com/CriticalFlaw/flawhud/assets/6818236/6a39352f-f65f-4f72-b419-bf01aeee7f13)

### FlawHUD
![20231101231131_1](https://github.com/CriticalFlaw/flawhud/assets/6818236/abc1a76d-ca7e-4cb3-be88-c986b87ec8d4)
![20231101231235_1](https://github.com/CriticalFlaw/flawhud/assets/6818236/817a532d-8539-42a3-acf1-6f0dab71c107)
