### ISSUE TITLE
Damage done font size

### ISSUE THREAD

**Issue by MirrorWars** [CriticalFlaw/flawhud#427]
Greetings!
How do I change font size of damage numbers which appears above enemy players when damage dealt? IMHO by default they are way too large and obstructs view (for heavy).

**Comment by CriticalFlaw** [comment]
Answered one Discord, just going to copy the answer from there.

> The font for those is set in resource/ui/huddamageaccount.res. There’s damage value which appears next to your health then there’s “delta_item_font” which is the health that appears above other players
