### ISSUE TITLE
Red text color shown for full health instead of green

### ISSUE THREAD

**Issue by nigiriemoji** [CriticalFlaw/flawhud#428]
2560x1440 display, latest flawhud reinstalled as of Dec 4 using tf2hudeditor. Sometimes when I have 100% health, the text color shows as red as if I've been damaged and not at 100% health. I expect it to be always white when at 100% and green color when higher than 100%. Sometimes it works fine and shows white. Examples pasted below

![20231204230038_1](https://github.com/CriticalFlaw/flawhud/assets/53108354/9ef7a8cc-26ef-4127-8133-050c8e93d3ce)
![image](https://github.com/CriticalFlaw/flawhud/assets/53108354/4df77271-4007-456b-8eea-f97eb65a7edb)
![20231204224030_1](https://github.com/CriticalFlaw/flawhud/assets/53108354/ac9070d5-9f4c-4cd8-9de3-57b834bab233)

**Comment by CriticalFlaw** [comment]
This is a known game bug where full health will appear red or whichever color a given hud has set as low. The only way to fix it is to force another health animation to trigger, such as damaging yourself then healing.

**Comment by nigiriemoji** [comment]
thanks for the info, didnt know that! closed
