### ISSUE TITLE
Preview during Decal Tool not properly displayed

### ISSUE THREAD

**Issue by nigiriemoji** [CriticalFlaw/flawhud#435]
I'm using the decal tool on a conscientious objector sign. The image applied to the decal just fine, but before that the preview section didn't render anything. Was wondering if this is a flawhud issue. I use a 2560x1440 display on windows 11. Latest flawhud, reinstalled as of this week

![20231222223145_1](https://github.com/CriticalFlaw/flawhud/assets/53108354/c6af6a9c-e9ba-42f0-b512-8b76349e5581)
![20231222223151_1](https://github.com/CriticalFlaw/flawhud/assets/53108354/0297b6c4-1e4c-40b6-a9db-a662a676f4f6)

**Comment by CriticalFlaw** [comment]
Does the same issue occur on the default HUD?

**Comment by nigiriemoji** [comment]
You're right, it's prob mastercomfig at this point. Closing ticket
