### ISSUE TITLE
Inspect Item menu is not centered

### ISSUE THREAD

**Issue by thejaviertc** [CriticalFlaw/flawhud#439]
When you inspect an item, the 3D model is not centered.

Original TF2 HUD:

![imagen](https://github.com/CriticalFlaw/flawhud/assets/45662206/ddb011bf-5133-448f-8d14-ab2173e15af7)

Flawhud:

![imagen](https://github.com/CriticalFlaw/flawhud/assets/45662206/06562ff6-5ae2-474a-b6b5-66b76ab03c76)

**Comment by CriticalFlaw** [comment]
It's not centered because the right side is where the war paint menu is shown when its needed. Go to the War Paints screen to see it. This is intended behavior.

**Comment by CriticalFlaw** [comment]
Closing as this is an intentional change. See comment above.
