### ISSUE TITLE
Certain characters with new chat font are in bold

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/flawhud#440]
![image](https://github.com/CriticalFlaw/flawhud/assets/123919000/f5205b68-ddd5-4d8c-a733-ab8bf58af279)

May be a bit hard to see, but certain characters such as N W and V are in bold for some reason and look a bit weird

**Comment by CriticalFlaw** [comment]
@floofycatto is this something that can be corrected?

**Comment by CriticalFlaw** [comment]
We can probably just revert the font change then since it has this issue.
