### ISSUE TITLE
Streamer mode still shows profile pictures

### ISSUE THREAD

**Issue by ghost** [CriticalFlaw/flawhud#441]
As title says

**Comment by CriticalFlaw** [comment]
It's not intended to hide profile pictures

**Comment by Tiagoquix** [comment]
> It's not intended to hide profile pictures

But doesn't that go against the, for the lack of a better word, "principles" of streamer mode (anonymous mode)?

**Comment by CriticalFlaw** [comment]
> > It's not intended to hide profile pictures
> 
> But doesn't that go against the, for the lack of a better word, "principles" of streamer mode (anonymous mode)?

No, it does not.
