### ISSUE TITLE
Automatically strating with streamer mode on everytime

### ISSUE THREAD

**Issue by javvathebaba** [CriticalFlaw/flawhud#447]
Everytime i start tf2 streamer mode is enabled and it takes like 10 seconds to turn it off every time tf2 starts up. and it keeps enabling itself everytime i start it

**Comment by CriticalFlaw** [comment]
Check your other config files for `cl_hud_minmode` being enabled somewhere. In flawhud minmode/streamer mode are purposely being disabled on startup: https://github.com/CriticalFlaw/flawhud/blob/master/cfg/valve.rc#L19

The only explanation is that a subsequent mod or config overwrites it.

**Comment by javvathebaba** [comment]
Okay, thank you, I will try that.
