### ISSUE TITLE
mat_aaquality value

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/flawhud#459]
Hi there.

Considering this command is used to do a hard reload of the HUD files, and also that it does not seem to be really used, shouldn't we set it to `0` via `valve.rc` to reset it on every start-up? Not sure if it causes performance drops or something.

It's related to anti-aliasing quality, but it was removed from mastercomfig because, IIRC, it was incorrect or did not work properly.

Thank you for your attention.

**Comment by CriticalFlaw** [comment]
If `mat_aaquality` does not have any notable impact on performance or user experience whether its on or off, then it doesn't need to be included in the `valve.rc` file.

However, if there is a notable difference and it would be beneficial to have it at a certain value at all times then we can either look into resetting it or use a different cvar entirely. I guess, I'd like to understand the impact of it more first

**Comment by Tiagoquix** [comment]
As far as I can tell, `mat_aaquality` is dead code related to anti-aliasing.
When changing its value, it forces a material system reload, and a material system reload can degrade performance over time.

https://github.com/mastercomfig/mastercomfig/blob/4a016b47443d472f4ac1341a656eefe7174a1122/config/mastercomfig/cfg/comfig/comfig.cfg#L1894-L1896

However, it's also used by mastercomfig to force a material system reload:

https://github.com/mastercomfig/mastercomfig/blob/4a016b47443d472f4ac1341a656eefe7174a1122/config/mastercomfig/cfg/comfig/comfig.cfg#L1257C1-L1257C48

I"m not sure how we should approach this. Maybe considering that even mastercomfig doesn't care to reset its value, then neither should we?

**Comment by CriticalFlaw** [comment]
> Maybe considering that even mastercomfig doesn't care to reset its value, then neither should we?

Agreed. Had it impacted something notable we could have gone and changed something but otherwise I feel like no action is needed. This is a very rare case where dead code actually comes in handy. Hopefully Joshie doesn't fix this :)
