### ISSUE TITLE
 Disable server name

### ISSUE THREAD

**Issue by rejedai** [CriticalFlaw/flawhud#461]
Add option disable server name in in-game hud, below playername

**Comment by CriticalFlaw** [comment]
May I ask why?

**Comment by rejedai** [comment]
This element seems highly annoying, especially for a minimalist HUD.

I'll attach a screenshot to make it clear what I mean.
![image](https://github.com/CriticalFlaw/flawhud/assets/92713267/654ddc6b-fbde-49a5-b99e-36c7e215dc53)

**Comment by CriticalFlaw** [comment]
That's not part of the HUD. Looks to be imposed by the server. Which server are you playing on?

**Comment by rejedai** [comment]
I have the same thought that some plugin, but turning on streamer mode removes it. That's why I assumed that it can be disabled at the hud level.

Links: 
steam://connect/80.76.60.139:27015
https://chillout.pw/connect/2fort - This is redirect to game connect. 

![Screenshot_2024_06_22_05_29_49](https://github.com/CriticalFlaw/flawhud/assets/92713267/65591984-50e7-405e-b560-c9437eafcd80)

**Comment by CriticalFlaw** [comment]
There is a HUD element that is used for superimposing text on screen but its controlled by the server not the HUD. To remove it means to remove it from being used by official servers.

**Comment by CriticalFlaw** [comment]
Closing as the label text is being imposed by the server and removing it would impact official modes.
