### ISSUE TITLE
Reset Stats button looks odd when playing in Russian

### ISSUE THREAD

**Issue by Meladoom** [CriticalFlaw/flawhud#464]
RESET STATS

![image](https://github.com/CriticalFlaw/flawhud/assets/30764362/68cb402c-e23c-4ed1-8f6f-2fda9d994ccd)

RUSSIAN VANILLA

![image](https://github.com/CriticalFlaw/flawhud/assets/30764362/c9849440-05a1-43f3-bd1c-67d90eded2b9)

The TEAM STATUS HUD (toggle) from #462 looks tolerable

![image](https://github.com/CriticalFlaw/flawhud/assets/30764362/e2a4538a-4eff-4478-87b2-8c5b42b772ee)

**Comment by CriticalFlaw** [comment]
Thanks but changing HUD elements for non-English languages is not in scope of this mod.
