### ISSUE TITLE
Ubercharge meter appearing on the side of the screen

### ISSUE THREAD

**Issue by dragontwist** [CriticalFlaw/flawhud#468]
Sometimes i need to reinstall the hud to be able to queue into casual

ubercharge meter is all the way to the right
![image](https://github.com/CriticalFlaw/flawhud/assets/21246746/7e9b1f54-caa8-4ac9-8981-04e01ca3e427)

~~custom crosshair is still enabled on sniper while zoomed in~~
![image](https://github.com/CriticalFlaw/flawhud/assets/21246746/f1e0c929-9672-47f6-9981-47d03c8d777b)

**Comment by CriticalFlaw** [comment]
> Sometimes i need to reinstall the hud to be able to queue into casual

Intermittent issues like that are not caused by the HUD. Please check if you have any conflicting mods in your `tf/custom` folder.

> ubercharge meter is all the way to the right

Are you using the TF2 HUD Editor? Latest version of flawhud from GitHub does not have this issue.

**Comment by dragontwist** [comment]
> Intermittent issues like that are not caused by the HUD. Please check if you have any conflicting mods in your tf/custom folder.

Will check perhaps it was a one time thing, 

> Are you using the TF2 HUD Editor? Latest version of flawhud from GitHub does not have this issue.

i am using the Editor.

**Comment by CriticalFlaw** [comment]
For editor related issues, check that you have the latest schema. There's usually a notification that comes up asking you to update. There have been several changes made over the past few days relating to the Ubercharge meter

**Comment by dragontwist** [comment]
Came on, about 30 mins ago. There was a update, Updated it reinstalled the ui 

![image](https://github.com/CriticalFlaw/flawhud/assets/21246746/117f60a0-dd47-440b-b724-b69a4a4ceec1)

and its still persists

current verison

![image](https://github.com/CriticalFlaw/flawhud/assets/21246746/313da05f-0958-489d-a308-d22a257091ed)

**Comment by dragontwist** [comment]
Did a full restart of pc and uninstalled and did a clean slate works now. 

sorry for the inconveince and thank you for your work
