### ISSUE TITLE
Flawhud does not work on linux

### ISSUE THREAD

**Issue by lilwat1** [CriticalFlaw/flawhud#471]
title.
it is marked as compatible on the download website but when loaded onto a tf2 installation on linux (in my case mint) it does not work with the game.

**Comment by lilwat1** [comment]
i will add it is specifically mint 21.3, with bash, and cinnamon DE.

**Comment by CriticalFlaw** [comment]
Can you post a screenshot of your tf/custom directory please.

**Comment by lilwat1** [comment]
It seems I have forgotten a crucial detail in this whole thing!
![image](https://github.com/user-attachments/assets/2143501b-a50c-432d-a9ce-3830080cf0f0)
folders with capital letters with them do not get mounted at all on linux!
