### ISSUE TITLE
Extra backpack slots dont display properly

### ISSUE THREAD

**Issue by TheSyncronisedGamer** [CriticalFlaw/flawhud#474]
the extra backpack slots do not display correctly as you can see in the images attached, as well as after slot 75 not being visible at all
![20240814142648_1](https://github.com/user-attachments/assets/970707dc-7bed-4ad1-9adb-3284d7d87165)
![20240814153006_1](https://github.com/user-attachments/assets/10e018b3-06cc-4ddd-943b-e8aa7e8f529a)

**Comment by TheRSO** [comment]
It was updated yesterday you can redownload the zip or use the [hud editor](https://github.com/CriticalFlaw/TF2HUD.Editor) to update it.

Changes
https://github.com/CriticalFlaw/flawhud/commits/master/

**Comment by CriticalFlaw** [comment]
Closing as this has already been fixed in 24f686ac54ef29cb22cd5d0a1bf4f7af6e2c37eb
