### ISSUE TITLE
Chat appears to be overlapping with health in latest build

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/flawhud#477]
![20240918184400_1](https://github.com/user-attachments/assets/253ecf26-007b-455b-9ddb-f2aca490094a)

**Comment by CriticalFlaw** [comment]
Do a HUD reload or enter `hud_reloadscheme` into console to correct it. Sometimes the game doesn't use the ypos defined in https://github.com/CriticalFlaw/flawhud/blob/master/resource/ui/basechat.res#L10

There's also a customization option in the HUD Editor to lower the chat but it won't account for overlaps.

**Comment by Presto06** [comment]
Appreciate the quick response.

but it seems that using hud_reloadscheme only corrects it for the current match. Loading into a new match will make it go back to the former position. Which is strange since this has never happened on older versions of flawhud.

Im currently not using the "lowered chat" customization and have tried the latest build through github and the hud editor, both have had the issue. Latest release however that I downloaded through gamebanana doesnt have this issue present.

**Comment by CriticalFlaw** [comment]
Very odd. I'll take a look - must be an animation change since that release if a fresh copy off GitHub without the editor has this problem

**Comment by Presto06** [comment]
Ive found the issue, The fixes in this commit https://github.com/CriticalFlaw/flawhud/commit/870617c2bfe290f90fc71a53b97330fbd938dbc0 was using the default huds chat ypos value. Ive created a pull request that changes it to use Flawhuds

**Comment by Presto06** [comment]
You may wanna also update the "Lowered Chat" customization and update the ypos value for the "stuck fix". in hudanimations_custom.
I dunno how to work with the hud editor so I cant make a pull request for that unfort.
