### ISSUE TITLE
Mode selection doesn't display correctly

### ISSUE THREAD

**Issue by mazeratibooloo** [CriticalFlaw/flawhud#481]
Running TF2 on Linux, latest update to the HUD gave me this issue with both the old and reworked mode selection. Old doesn't display any buttons at all, reworked mode selection has all the buttons overlapping each other.

![2024-10-12_07-23](https://github.com/user-attachments/assets/e6664d41-1c3d-4762-8fae-b90834fc3eca)
![oldmode](https://github.com/user-attachments/assets/5de7198a-0ad5-4845-9edf-357bbb95e720)

**Comment by CriticalFlaw** [comment]
Check that you have the latest schema updates on the editor before applying these changes. Also try it without applying any customizations at all. From my test everything is working as intended on latest versions

![20241012193346_1](https://github.com/user-attachments/assets/d5315663-d5b0-49d0-83bc-f7ba9a967b5e)

![20241012193438_1](https://github.com/user-attachments/assets/813790f2-c849-479c-9fda-cf95124e919b)

**Comment by mazeratibooloo** [comment]
Hmm, might just be an issue with the editor then. FlawHUD as is does show the mode selection correctly. But even after updating the schema with the editor, still got the exact same issue with the mode selection.

For all I know, it could be my janky setup I put together to attempt and configure FlawHUD from Linux as well; tried to symlink my tf folder to a VM, but it just froze my VM whenever I tried to use the editor that way. Made a tf/custom folder in the VM itself and it would work fine, just had to move the HUD it made out of the VM and use it that way.

Either way, it does appear this is out of scope for the HUD specifically, and I think there may just be too many variables at play. Shame, because I don't really know any other way to configure FlawHUD on Linux aside from TF2 HUD Editor. Here's to hoping for a Linux port of that eventually.
