### ISSUE TITLE
Tabbing causing white borders

### ISSUE THREAD

**Issue by Kurumesu** [CriticalFlaw/flawhud#483]
![image](https://github.com/user-attachments/assets/c7983482-e53b-4ffd-88ef-7166dac2d5b7)

This picture says it all

**Comment by TheRSO** [comment]
If you're using the HUD Editor you may have to clear your cache and check for updates, then uninstall and reinstall.
![Screenshot 2024-10-14 115718](https://github.com/user-attachments/assets/0f45b2ca-3e77-4694-9779-cf76c61db529)
![Screenshot 2024-10-14 115943](https://github.com/user-attachments/assets/ed04adb1-05d2-4d92-8910-754a611e4604)

**Comment by Kurumesu** [comment]
> If you're using the HUD Editor you may have to clear your cache and check for updates, then uninstall and reinstall. ![Screenshot 2024-10-14 115718](https://private-user-images.githubusercontent.com/145300650/376313935-0f45b2ca-3e77-4694-9779-cf76c61db529.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MjIwMTAsIm5iZiI6MTcyODkyMTcxMCwicGF0aCI6Ii8xNDUzMDA2NTAvMzc2MzEzOTM1LTBmNDViMmNhLTNlNzctNDY5NC05Nzc5LWNmNzZjNjFkYjUyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQxNjAxNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZjZlZGQ5Y2MyZTNlY2Y5Y2NmYmU4NjlhODViZjlkNzU5MWY5MzMwNGQwMDMxMzJjMWU0NjYwMDI5YmU0NzYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TE6OlnUFi_Q68kK3fc1s90_KtqNNfaGEh9QjcSHfS2c) ![Screenshot 2024-10-14 115943](https://private-user-images.githubusercontent.com/145300650/376314147-ed04adb1-05d2-4d92-8910-754a611e4604.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MjIwMTAsIm5iZiI6MTcyODkyMTcxMCwicGF0aCI6Ii8xNDUzMDA2NTAvMzc2MzE0MTQ3LWVkMDRhZGIxLTA1ZDItNGQ5Mi04OTEwLTc1NGE2MTFlNDYwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQxNjAxNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MzA3NDk4MTdiY2JiNzg1MGFmNzkzZmYzZWM2MDRkZDRiZDdmMzk2NTQ3NDZhYjY5NjE2NTQwYzZhNWQ0MWM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yBNpZAcGXCZP91NYbr88l_Jmd_vO41lLBDGxTIZNeiQ)

I don't use HUD editor. Is it fixable without or no?

**Comment by TheRSO** [comment]
After discussion,
User downloaded from https://comfig.app/huds/page/flawhud/
Downloads the release version from 10/11, which didn't include the drawing board fix. (https://github.com/CriticalFlaw/flawhud/commit/5b8cc2e71372a0c669ffed80260f9edc60b62476)
![image](https://github.com/user-attachments/assets/fe54d4b7-c624-4e65-98d0-31d5196df858)

**Comment by CriticalFlaw** [comment]
I think comfig pulls from releases instead of the master branch - will need to check it out

**Comment by Kurumesu** [comment]
> After discussion, User downloaded from https://comfig.app/huds/page/flawhud/ Downloads the release version from 10/11, which didn't include the drawing board fix. ([5b8cc2e](https://github.com/CriticalFlaw/flawhud/commit/5b8cc2e71372a0c669ffed80260f9edc60b62476)) ![image](https://private-user-images.githubusercontent.com/145300650/376317651-fe54d4b7-c624-4e65-98d0-31d5196df858.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MzQwMDUsIm5iZiI6MTcyODkzMzcwNSwicGF0aCI6Ii8xNDUzMDA2NTAvMzc2MzE3NjUxLWZlNTRkNGI3LWM2MjQtNGU2NS05OGQwLTMxZDUxOTZkZjg1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQxOTIxNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02M2M2MzM3ZWY0ZjYxNGQwY2Y5MTE4MGVmYTYyYmY2M2JlNDExZTE3Y2YzNjYwODNmMDUwNDBhNzAzNDdhNWE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.f-BAgXg8AksN2pekIt-1fIVcf049gu9cev6EUq4U7W8)

This was the issue, fixed now
