### ISSUE TITLE
Pulling up scoreboard blocks the screen with white border

### ISSUE THREAD

**Issue by HamsterGabe** [CriticalFlaw/flawhud#484]
I don't know how else to describe it, you'll just have to see it to know what I'm talking about. I have no idea why this happens but it wasn't a problem with the previous version.
![20241015095158_1](https://github.com/user-attachments/assets/c454cc25-9000-420e-9e70-5ef97c8f0ec8)

**Comment by TheRSO** [comment]
https://github.com/CriticalFlaw/flawhud/issues/483#issuecomment-2411701351

Can download the latest version [here](https://github.com/CriticalFlaw/flawhud)
![image](https://github.com/user-attachments/assets/66b964f6-1076-432f-b7df-2fd5bcf8cffc)

**Comment by CriticalFlaw** [comment]
The GitHub and Gamebanana releases have been updated with this bug fixed as TheRSO suggested.

The comfig release will be fixed soon. There are some background changes going on at the moment.

**Comment by CriticalFlaw** [comment]
I'll keep this issue open until the comfig page is fixed just in case others encounter the same issue.

**Comment by CriticalFlaw** [comment]
Comfig page updated with the latest release.
