### ISSUE TITLE
Overtime text is cut off when match hud is disabled

### ISSUE THREAD

**Issue by wulufu** [CriticalFlaw/flawhud#486]
This seems to only be an issue in KOTH maps where there are two timers at the top of the screen.

Match HUD disabled:
![20241017102932_1](https://github.com/user-attachments/assets/afb2abeb-dc4c-4d05-9065-ed6094975eeb)

Match HUD enabled:
![20241017102939_1](https://github.com/user-attachments/assets/61d1dad1-13f0-464f-ba4d-7c369ae5f883)

**Comment by CriticalFlaw** [comment]
Fixed in 317a3c801d72694b7e34b01b54e3477dfd5fe05c. Thanks
