### ISSUE TITLE
Score and ping are too large with _Pro fonts. 

### ISSUE THREAD

**Issue by Soapsuds** [CriticalFlaw/flawhud#487]
Using 1440P 
![Screenshot_20241024_061435](https://github.com/user-attachments/assets/98f71c2c-30cb-44bc-820f-20d5972ce386)

**Comment by CriticalFlaw** [comment]
You may not be on the latest version because this has already been fixed.

![20241025163630_1](https://github.com/user-attachments/assets/1891ffaf-0553-4eb4-a42d-6e9b8665e53f)

Download latest version from this link: https://github.com/CriticalFlaw/flawhud/archive/refs/heads/master.zip

**Comment by Soapsuds** [comment]
Hey! I upgraded to the latest but it looks the same. Any ideas? Any other information I can provide to help? 
![Screenshot_20241027_081334](https://github.com/user-attachments/assets/7c3f5a82-e925-47bf-88c1-008920bf60ac)

**Comment by CriticalFlaw** [comment]
What resolution are you using?

**Comment by Soapsuds** [comment]
This is on 1440p. 
Here's my console log. https://pastebin.com/wB2JPQ9T
Here's a screenshot of the default font and with _pro again. 
![default_font](https://github.com/user-attachments/assets/f5ea6b3b-41f6-4c8b-9ccb-9fa33c4d5d96)
![sourcepro](https://github.com/user-attachments/assets/7066dd1b-17db-40b7-94fc-577369a55f14)

My video options in TF2.
![options](https://github.com/user-attachments/assets/0fc09896-649b-4625-a4be-e8119073ec27)

To enable PRO I'm just editing clientscheme.res and setting this line #base "scheme/clientscheme_fonts_pro.res", is that right? 

I tried playing with the vgui_ui_scale options but that doesn't seem to change anything with the scoreboard. 

I checked at 1080p and it looks good: 
![1080p](https://github.com/user-attachments/assets/6ce542cd-4e2b-4ed7-b1b6-0f5fd461bfa5)

**Comment by CriticalFlaw** [comment]
Can you paste your copy of the `flawhud/resource/scheme/clientscheme_fonts_pro.res` please? I wonder if it's still using the old version for some reason

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/CriticalFlaw/flawhud/commit/96d0756e8f7b42e8724e42f94722e6f71eed1520. Please download the latest GitHub version to see the changes. Thanks!

![20241104211411_1](https://github.com/user-attachments/assets/a1aeb393-2f4e-421e-9de1-f0b2ffb32e54)

**Comment by Soapsuds** [comment]
Can confirm, looks great! Thanks
![good](https://github.com/user-attachments/assets/62b4d077-bbb1-4544-94cf-c1d7af0311dc)
