### ISSUE TITLE
Increase size of heal target's ammo

### ISSUE THREAD

**Issue by Meladoom** [CriticalFlaw/flawhud#490]
![image](https://github.com/user-attachments/assets/ef077c64-98ed-4b64-8325-ff6a3abd5b1d)

![image](https://github.com/user-attachments/assets/d140704c-1815-4a32-8292-abb54764ea2d)

![image](https://github.com/user-attachments/assets/c969651e-ca0a-43e3-a6db-1c0225690d46)

Would be nice to increase their size and outline, to make the 0/4 rockets easier to see. (And not give early kritz)

Also it seems that the icon on the left is the weapon dmg type, but I doubt the RL or Flamethrower deal bullet-type dmg

**Comment by TheRSO** [comment]
Regarding the icon it's there to indicate that it's ammo, not the damage type.

**Comment by CriticalFlaw** [comment]
Fixed in #491 by @TheRSO. Thanks!
