### ISSUE TITLE
FlawHUD displaying hud elements in the wrong place

### ISSUE THREAD

**Issue by Blue0din** [CriticalFlaw/flawhud#499]
![Screenshot 2024-12-07 201716](https://github.com/user-attachments/assets/138b77dc-8213-4704-83eb-44f82d0bdedd)

**Comment by TheRSO** [comment]
Freshly installed from editor. 
![image](https://github.com/user-attachments/assets/fdc5e0da-311f-4180-a806-7844d30bc44f)
Make sure to clear cache then check for schema updates
![376313935-0f45b2ca-3e77-4694-9779-cf76c61db529](https://github.com/user-attachments/assets/b3cb7a46-8533-4048-a5ca-d8b9d860e571)
![376314147-ed04adb1-05d2-4d92-8910-754a611e4604](https://github.com/user-attachments/assets/8da62ade-ec65-44bb-87ae-7d1c6da39439)
 
(if above doesn't work refer to https://github.com/CriticalFlaw/TF2HUD.Editor)

**Comment by CriticalFlaw** [comment]
Enable auto-update files as well in the same options menu

**Comment by Blue0din** [comment]
Thanks, it worked
