### ISSUE TITLE
Game Mode Selection UI's shadow does not cover the entire menu

### ISSUE THREAD

**Issue by ghost** [CriticalFlaw/flawhud#59]
![main_menu_game_mode_selection](https://user-images.githubusercontent.com/27376783/66705716-98d4c100-ed2a-11e9-9625-bd1ed3505537.png)

**Comment by CriticalFlaw** [comment]
Hello. This is an issue present in all custom huds, because Valve hard-coded the height of the shadow. It unfortunately cannot be fixed unless you mess with your configurations

**Comment by CriticalFlaw** [comment]
I can point you in the right direction if that's something you want to look into but otherwise it sadly may not be worth the effort

**Comment by ghost** [comment]
Hi! I see. Unfortunately, I am not into the whole custom HUD's thing; I cannot do more than apply a workaround to my configuration. Thank you for your input and time to reply to this issue, though~

Edit: If I understand this correctly, it is not a Linux-specific issue?

**Comment by CriticalFlaw** [comment]
Yes, it's not Linux specific. This is seen on every operating system.
