### ISSUE TITLE
Death freeze cam health sometimes doesn't fill

### ISSUE THREAD

**Issue by Douile** [CriticalFlaw/flawhud#60]
Occasionally in the death freezecam (`resource/ui/freezepanelkillerhealth.res` : `PlayerStatusHealthValueFreezePanel`) the value `%Health%` is not replaced with the other players health and instead remains as `%Health%`.

OS: Windows
TF2: 5508706
FlawHUD: 2019.1123

**Comment by CriticalFlaw** [comment]
I definitely notice it at least one per match (not round), usually on the first death. This is a common bug with custom HUDs but I would like to see if it's something that has started occurring more frequently as of late and if it's something that can be fixed.

**Comment by Douile** [comment]
Ah ok, if it happens in other HUDs it's probably a TF2 issue and not a HUD issue.
I also noticed it happening with teammate health markers and the username on the same death panel. It seems to happen more during lag, happens for me a few times each round.

**Comment by Tiagoquix** [comment]
Use hud_reloadscheme in your first spawn after opening the game to avoid this issue.

**Comment by CriticalFlaw** [comment]
This should be kept closed because it cannot be fixed. `hud_reloadscheme` in console is a workaround.

**Comment by Douile** [comment]
@CriticalFlaw fair enough, but do you know if there's a way this can be run as part of the HUD? I tried in valve.rc but that runs at startup so doesn't help.

**Comment by CriticalFlaw** [comment]
`hud_reloadscheme` is used to refresh the HUD if anything hasn't loaded or there is some visual bug. It's not a command you can apply once on startup, you would call it if when you're experiencing an issues.

**Comment by Douile** [comment]
Oh ok thanks for the info
