### ISSUE TITLE
Failed to load resource/UI/HudItemEffectMeter_Action.res

### ISSUE THREAD

**Issue by Douile** [CriticalFlaw/flawhud#62]
Error when loading HUD
```
Failed to load resource/UI/HudItemEffectMeter_Action.res
resource/UI/HudItemEffectMeter_Action.res missing ContinuousProgressBar field "ItemEffectMeter"
```

**Comment by CriticalFlaw** [comment]
This is a game issue where the `HudItemEffectMeter_Action` is still being referenced by the game code even though it's unused and does not exist in the files. I would close this because it's a Valve issue and it has no impact on the game.
