### ISSUE TITLE
valve.rc is not needed

### ISSUE THREAD

**Issue by Perkzitos** [CriticalFlaw/FlawHUD#64]
Hello CriticalFlaw.
I know that you added the `valve.rc` file to remove the `Unknown command "dimmer_clicked"` but I think that is not necessary at all. It just a console message, not so annoying. Also, this addition removes the ability to directly open TF2 and connect into a server because of the `mat_antialias` in the start-up.

**Comment by CriticalFlaw** [comment]
That file is used to remove the entire main menu dimmer, not just the console line. 

![image](https://user-images.githubusercontent.com/6818236/71526578-91db3a80-28a5-11ea-86f6-c8910951b0ad.png)

The ability to open TF2 and connect directly to the server still works. Just tested it by clicking the following connection link: steam://connect/167.71.163.148:27015

**Comment by Perkzitos** [comment]
Alright then. Thanks for the reply!
