### ISSUE TITLE
Unfriendly hud for mvm

### ISSUE THREAD

**Issue by h9lk** [CriticalFlaw/flawhud#65]
For some reason realized that this hud very strange in relation to mvm. Aready used a lot
![20200102231327_1](https://user-images.githubusercontent.com/32390006/71755041-f1cf7380-2e99-11ea-858b-dc22b89955bc.jpg)

sometimes notice elements by accident
![20200103165801_1](https://user-images.githubusercontent.com/32390006/71755220-a8335880-2e9a-11ea-9fc3-d35f1008da18.jpg)

I respect you as developer - use this hud for a long time, really like him, happy new year to you, good luck and inspiration for future projects! :sparkling_heart: (Sorry if I distract you from relaxing on a well-deserved New Year's weekend)

**Comment by CriticalFlaw** [comment]
Could you post the entirety of the second screenshot so I can determine how to replicate that visual bug? Thanks.

**Comment by h9lk** [comment]
![20200105204308_1](https://user-images.githubusercontent.com/32390006/71783735-13e10700-2ffc-11ea-99a4-fc2de85de682.jpg)

**Comment by CriticalFlaw** [comment]
Both issues have been fixed. Please download the latest version off GitHub.

Thank you for reporting the issue!
