### ISSUE TITLE
valve.rc doesn't work

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/flawhud#66]
It doesn't work as intedeed. Does not remove the menu dimmer. Tested several times.

**Comment by Tiagoquix** [comment]
Can be a possible conflict with the mastercomfig anti-alias setting (I use mastercomfig).

**Comment by CriticalFlaw** [comment]
Like you said, the mastercomfig overwrites the `mat_antialias` variable increment that's being done in valve.rc. However, unless it's also not working without mastercomfig then I'd say it's working as intended.

**Comment by Tiagoquix** [comment]
It works sometimes and it doesn't works sometimes.
I think you should request (or maybe I) a feature from Valve to disable dimmer with a HUD file or a console variable.
I don't care about the main menu dimmer, but the file makes the game take longer to get 100% ready to play.
Thanks for the reply, I'll close this now.

**Comment by Tiagoquix** [comment]
I found the problem. If you run the command hud_reloadscheme on the console, the menu dimmer returns. I always run it once spawning in a match to fix hud issues.
The valve.rc works, but only in the first launch, before joining in a server.
