### ISSUE TITLE
The subfiles are false, apparently

### ISSUE THREAD

**Issue by thiccest** [CriticalFlaw/FlawHUD#67]
https://gyazo.com/0749571b31d73201e462d2d54428be92

This error keeps popping up when I try to launch TF2, and it will keep popping up until I delete the FlawHUD from custom, any way to fix this?

**Comment by Perkzitos** [comment]
How did you install FlawHUD? Send a screenshot of your `custom` folder.

**Comment by thiccest** [comment]
Nevermind, your comment made me try to reinstall the main folder to see if I was supposed to extract the entire folder and not the folders inside. Thank you.
