### ISSUE TITLE
Localization support for the FlawHUD

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/flawhud#69]
Is there any possibility of adding support for the game translations on the HUD when using the # labels of the localization files?

For example, I'm a brazilian, so, "Steam Workshop" is "Oficina Steam" for me, and in the localization files is:

```
"MMenu_SteamWorkshop"	"Oficina"
"[english]MMenu_SteamWorkshop"	"Workshop"
```

So, in `mainmenuoverride.res` we can replace the
```
"labeltext" "STEAM WORKSHOP"
```
with
```
"labeltext" "#MMenu_SteamWorkshop"
```
and it will have localization support.

What do you think of this, CriticalFlaw?

**Comment by CriticalFlaw** [comment]
That's a good idea. Some labels are already localized but not others. It'll just be a matter of tracking them all down

**Comment by Tiagoquix** [comment]
> That's a good idea. Some labels are already localized but not others. It'll just be a matter of tracking them all down

I can do this (find the labels), but if you can tell me all the HUD files that use "labelText", it would help me a lot.

**Comment by CriticalFlaw** [comment]
An issue I'm encountering while updating labels to use localized strings is that FlawHUD has many strings that use shortcut keys. Such 1-9 for class selection or Q for returning to a previous page. tf_english doesn't have those specific shortcuts and they cannot be combined in the UI files. So we'll end up with a notable number of labels not being translated.

**Comment by CriticalFlaw** [comment]
Also the space allocated for the text is only accounted for in English. So some translated text will not fit properly, for example in Russian the class names for Scout, Pyro, Demoman and Heavy are often cut off.

**Comment by Tiagoquix** [comment]
Alright, I did not think about that. But, what do you think for something like "FlawHUD custom files for localization support"? I can provide these in Brazilian Portuguese.

**Comment by CriticalFlaw** [comment]
Implemented in: https://github.com/CriticalFlaw/FlawHUD/commit/428b3c3935ba2d74ae1f5ee7832b12b3db26adeb

**Comment by Blueberryy** [comment]
You can use **chat_english.txt** for custom localization texts

**Comment by Blueberryy** [comment]
@CriticalFlaw
