### ISSUE TITLE
Localization strings

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/flawhud#71]
In the main menu, the localization strings are not in uppercase, which you can see in the screenshot below (identities have been hidden).

![image](https://user-images.githubusercontent.com/30274161/74666354-18164d80-5180-11ea-988e-9a9175333b90.png)

The "Options" (Opções) and the "Oficina" (Workshop) are in lowercase. A suggestion of mine to fix this is to move the buttons along with the row of small buttons at the left center, leaving only the two main ITENS and MANN CO. STORE buttons. It will be like this:

![image](https://user-images.githubusercontent.com/30274161/74666142-c241a580-517f-11ea-9b42-853095dd170f.png)

In the screenshot (edited), there I represent that we must move the Options button to the green square and the Workshop button to the blue square, thus removing the 2 large buttons, leaving them together with the row of small buttons.

And that is it.

**Comment by CriticalFlaw** [comment]
Better solution is to force the text to be in uppercase. That's been corrected here: https://github.com/CriticalFlaw/FlawHUD/commit/8742ed34b4460571399f8d03a3dd3c9f43d96987

**Comment by CriticalFlaw** [comment]
![image](https://user-images.githubusercontent.com/6818236/74667330-15f8c280-5171-11ea-8aa4-a9b554a4dbb6.png)

**Comment by Tiagoquix** [comment]
I didn't know this was possible! Thank you.
