### ISSUE TITLE
FlawHUD fonts not displaying Brazilian Portuguese properly

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/flawhud#72]
Hi. I switched to the TF font on the hud, and in my playtesting, I found three problems with it. I am playing with the language Brazilian Portuguese (PT-BR).

1- Party messages on the main menu are hard to read.

2- Sometimes, some letters are cut out from the chat, for example: "oi, eu vi isso" ("hi, I saw that", in Brazilian Portuguese), the letter "o" gets cut out and instead it shows like the letter "c", so it is like: "oi, eu vi issc", and it is only possible to read the full message by opening the console.

3- The number 9 does not look like a number 9, instead, it looks like a deformed number 5.

That's all.

**Comment by CriticalFlaw** [comment]
Unfortunately it's beyond my control how the text is handled by the TF2 fonts. This would be an issue to report on Valve's issue tracker here: https://github.com/ValveSoftware/Source-1-Games/issues

**Comment by Tiagoquix** [comment]
> 1- Party messages on the main menu are hard to read.

Sadly, this has not been fixed with the latest HUD update.

> 2- Sometimes, some letters are cut out from the chat, for example: "oi, eu vi isso" ("hi, I saw that", in Brazilian Portuguese), the letter "o" gets cut out and instead it shows like the letter "c", so it is like: "oi, eu vi issc", and it is only possible to read the full message by opening the console.

This is a minor issue. Sometimes, by just opening the full chat without the console, the message can be fully read.

> 3- The number 9 does not look like a number 9, instead, it looks like a deformed number 5.

The problem stills the same.

**Comment by Tiagoquix** [comment]
> Unfortunately it's beyond my control how the text is handled by the TF2 fonts. This would be an issue to report on Valve's issue tracker here: https://github.com/ValveSoftware/Source-1-Games/issues

I tested the number 5 on the default HUD, and **sometimes** it works fine.

**Comment by CriticalFlaw** [comment]
Regardless these are issues with the way TF2 displays its own fonts, and is not something that can be fixed on my end.
