### ISSUE TITLE
Medi Gun Ubercharge Meter

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/flawhud#73]
Sometimes it is white, sometimes it is green. Might you do a default? Only green or only white? It would be great.

That's all.

**Comment by Tiagoquix** [comment]
If you want to know, I prefer the green meter.

**Comment by CriticalFlaw** [comment]
The color of the medigun has been changed to green while charging https://github.com/CriticalFlaw/FlawHUD/commit/871ffdfec4657061bebb72e9b4b33247ef245b86

**Comment by Tiagoquix** [comment]
@CriticalFlaw Thanks for the update! The Ubercharge meter looks so much better now.
