### ISSUE TITLE
Update Clovervidia Captions

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/flawhud#78]
The new version is 2.5.4 and FlawHUD is with the version 2.5.3.
I suggest to put the "clovervidiac" captions in the HUD.

https://github.com/clovervidia/clovervidias-captions

**Comment by CriticalFlaw** [comment]
What's the difference between the two versions? The captions in FlawHUD are modified and it look a lot of work so unless the changes in version 2.5.4 can justify the effort, I won't be updating them.

**Comment by Tiagoquix** [comment]
The changelog says:

> v2.5.4 2015-05-25
> Fixed "Spy on fire" captions not showing up, thanks iSk_

I do not know if this happens on the FlawHUD's version.

**Comment by CriticalFlaw** [comment]
I've compared the versions and FlawHUD already has the latest CC changes added. They just haven't updated the version number from v2.5.3 to v2.5.4 in their text files on line 4640. Closing.

![image](https://user-images.githubusercontent.com/6818236/79241823-8e15f880-7e41-11ea-8f27-f1b331d0ded8.png)
