### ISSUE TITLE
HUD not showing

### ISSUE THREAD

**Issue by Kangar3w** [CriticalFlaw/FlawHUD#81]
Placed in my custom folder and nothing is happening, after the Blue moon update, I haven't been able to get any custom mod working.

**Comment by CriticalFlaw** [comment]
Could you post a screenshot of your tf/custom folder please?

**Comment by CriticalFlaw** [comment]
Closing as I haven't received a reply in over two weeks. I'd suggest trying the FlawHUD Installer to install the HUD for you: https://github.com/CriticalFlaw/FlawHUD.Installer/releases
