### ISSUE TITLE
[Streamer HUD] Change killfeed to show teams

### ISSUE THREAD

**Issue by maikdevries** [CriticalFlaw/flawhud#82]
At the moment, the killfeed in the streamer version of FlawHUD only shows the weapons and hides the username. Instead, I think it would make a good change to show the team the players are on.

Example: `RED [weapon] BLUE` instead of `playerOne [weapon] playerTwo` which is the case in normal HUDs and in the case of the streamer version just `[weapon]`.

**Comment by CriticalFlaw** [comment]
After looking into it, turns out that the text you see on the killfeed is generated by the game code and cannot be overwritten. Best you can do is change the font, so this change is looking to be impossible

**Comment by maikdevries** [comment]
Someone suggested earlier today that you could also change the font to one which only has `■` as their letters. After thinking about it however, people hardly look at the killfeed anyway so no harm done if it doesn't get implemented down the road.

**Comment by CriticalFlaw** [comment]
Closing as this change cannot be implemented.
