### ISSUE TITLE
[2020.0302] Old health cross not working

### ISSUE THREAD

**Issue by markdwhite** [CriticalFlaw/flawhud#84]
Following the instructions to enable the old health cross:

 https://steamcommunity.com/groups/FlawHUD/announcements/detail/1759123375921304163

Relevant sections of flawhud/resource/ui/hudplayerhealth.res now look like:

    "HealthBG"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"HealthBG"
		"xpos"			"64"
		"ypos"			"29"
		"zpos"			"1"
		"wide"			"100"
		"tall"			"43"
		"visible"		"0"
		"enabled"		"0"
		"defaultbgcolor_override"	"HudBlack"
		"PaintBackgroundType"		"2"
	}
	
	"PlayerStatusHealthBonusImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"PlayerStatusHealthBonusImage"
		"xpos"			"82"
		"ypos"			"20"
		"zpos"			"3"
		"wide"			"60"
		"tall"			"60"
		"visible"		"1"
		"enabled"		"1"
		"image"			"../hud/health_over_bg"
		"scaleImage"	"1"
	}

Expected:

![xsnap140338](https://user-images.githubusercontent.com/292063/80569179-9580f880-8a22-11ea-8174-4b493f0aeeb3.png)

Actually saw:

![xsnap140556](https://user-images.githubusercontent.com/292063/80569231-ac274f80-8a22-11ea-940f-5ee077fa62b0.png)

Am I expecting the wrong thing here? Can I get this to appear as expected?

Thanks

**Comment by CriticalFlaw** [comment]
The old health cross refers to the health cross used by FlawHUD years ago. It doesn't show up on the targetID but does on the main UI, replacing the box that surrounds the health normally. See screenshot below

![20200429084106_1](https://user-images.githubusercontent.com/6818236/80597013-3ce73680-89f5-11ea-86e0-dd8d9e65f92e.jpg)

**Comment by markdwhite** [comment]
Ah - I got the wrong end of the stick. Fair enough :-)
