### ISSUE TITLE
[BUG] KnuckleCrosses wrongly mapped

### ISSUE THREAD

**Issue by maikdevries** [CriticalFlaw/flawhud#85]
Setting `visible`, `enable` to `1` and specifying your preferred crosshair by setting the `labelText` in `flawhud/scripts/hudlayout.res` does not always result in the right crosshair.

As example, set `labelText` to `d` for the following crosshair:
![image](https://user-images.githubusercontent.com/44983425/80805324-06a5e480-8bb8-11ea-9006-2ebf96f73d5a.png)

This results in the following crosshair actually showing up:
![image](https://user-images.githubusercontent.com/44983425/80805354-17eef100-8bb8-11ea-8799-a9cff5c10273.png)

It seems that certain crosshairs are wrongly mapped to the `labelText` defined in `KnuckleCrosses.png`.

**Comment by CriticalFlaw** [comment]
The actual letter for the crosshair you want is **T**

That's because in `KnuckleCrosses.png` each crosshair's corresponding letter is shown above the crosshair, not below. I know it's confusing, but that's how it's organized in FontForge which is where that image was taken from.

**Comment by maikdevries** [comment]
I should probably wake up some more next time. Thanks for clarifying.

**Comment by CriticalFlaw** [comment]
All good, it happens :)
