### ISSUE TITLE
Update the Lightning Charge Meter

### ISSUE THREAD

**Issue by RayHammer** [CriticalFlaw/flawhud#88]
No changes were made to resource/ui/HudLighningCharge.res and instead it was moved all the way to the left. This makes it hard to keep track of the lightning ammo, so my suggestion is to move the charge meter either to the ammo value or below the crosshairs. Keep in mind that this UI element shares the same box as the Medic's Ubercharge

**Comment by CriticalFlaw** [comment]
The lightning gun, along with the lunge meter have been updated to match the other meters.

![image](https://user-images.githubusercontent.com/6818236/82057420-4f1dd180-9691-11ea-9c72-7b84672af948.png)
