### ISSUE TITLE
Demo player display breaks on 4:3 stretched

### ISSUE THREAD

**Issue by qwedas** [CriticalFlaw/flawhud#89]
When watching a demo the UI doesn't display red teams player names. I'm using Linux.

![Screenshot from 2020-05-21 12-01-20](https://user-images.githubusercontent.com/32962637/82579312-9c031b80-9b5b-11ea-9edd-91ad9c68eab1.png)
![Screenshot from 2020-05-21 12-06-10](https://user-images.githubusercontent.com/32962637/82579316-9c9bb200-9b5b-11ea-8bf9-85fc94ae9123.png)

**Comment by CriticalFlaw** [comment]
Unfortunately I haven't been able to make the red player list to appear on the right side across all resolutions. As a compromise you can fix the issues yourself by opening `flawhud/resource/ui/spectatortournament.res` and changing the number highlighted in yellow to 141.

![image](https://user-images.githubusercontent.com/6818236/83341733-d3d53600-a2b4-11ea-90db-f38a2509a9d3.png)

**Comment by qwedas** [comment]
Thank you for the response. After changing the value of "team2_player_base_offset_x" to 141 There was definitely an improvement.
![Screenshot from 2020-06-02 20-07-16](https://user-images.githubusercontent.com/32962637/83581786-c797e580-a50d-11ea-946f-315426ac628b.png)

I played around with the number and 162 seems to be the right value.
![Screenshot from 2020-06-02 20-14-33](https://user-images.githubusercontent.com/32962637/83581826-ded6d300-a50d-11ea-97b2-6bbe48ffa1d3.png)
