### ISSUE TITLE
File Conflict with GameBanana?

### ISSUE THREAD

**Issue by Sigiliph** [CriticalFlaw/flawhud#9]
I tried to install a few skins from gamebanana - I put them all in the custom folder, and then launched the game. The HUD wasn't working. So, I tried taking them all out - everything is in it's normal state - and the HUD still doesn't work. I then tried using different paths for a few hours and now I'm screwed. HUD is still default and ugly.

**Comment by CriticalFlaw** [comment]
Best practice is to segregate each mod into its' own folder, unless it's a .vpk which can be located in the root of the custom folder. What I would recommend is, clear everything out of the custom folder, then install FlawHUD as normal. Then install each skin at a time, making sure each is in it's own folder, again unless it's a .vpk file.

If you're still having issues, let me know which skins you're attempting to install.
