### ISSUE TITLE
Control Point Icon Bug

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/flawhud#91]
The recent updates changed the server browser menu background to be gray instead of black as it was. My opinion is to revert this change, since being gray "conflicts" with the server searching menu on the bottom, since it is the same color. I also prefer black. [Screenshot](https://i.imgur.com/WV4xxFU.jpg).
Also some things are too "big" in the menu with the Brazilian Portuguese language that they get cut out. For example, in the same screenshot, "Lista simplificada" (Simplified list) is cut out, "Marcador/incluir" are overlapping each other and "Workshop" is not localizated (I do not know if it can be). And, the scroll bar in the server browser menu is not perfectly adjusted. It is slightly smaller than the up/down buttons.

Also, when capping a point, now it shows a line in the middle of the cap square, and this is weird and ugly at the same time. Can you remove it? The line was not present before. [Screenshot](https://i.imgur.com/Cu7JoCY.jpg).

And that is all.

**Comment by CriticalFlaw** [comment]
I can certainly address the coloring on the server browser (that was an oversight from the previous update) and the middle line on the control points when capped.

The rest like scrollbar and the text size in other languages sadly won't be addressed. The scroll bar is hardcoded and to change the size of text for one language would mean to change it for everyone. It's not an ideal solution as it still may not fit for other languages and making it smaller may make it harder to see for English players who make up the majority of the FlawHUD users.

**Comment by CriticalFlaw** [comment]
Reverted the color change to the source scheme and removed the custom control point icons for when capping. I've figured the custom icons were causing too many issues and it looks fine as is with the defaults.

**Comment by Tiagoquix** [comment]
Thank you!
