### ISSUE TITLE
Phlog Mmmph Meter Missing When Used With Gas Passer

### ISSUE THREAD

**Issue by tetra8** [CriticalFlaw/flawhud#93]
When using the phlogistinator and the gas passer, only the gas passer's recharge meter can be seen.

**Comment by CriticalFlaw** [comment]
I'm not seeing the same problem on my end. Are you using the latest version?

![20200609125249_1](https://user-images.githubusercontent.com/6818236/84176952-2a2e3b80-aa50-11ea-8c01-fda5a7c51148.jpg)

**Comment by tetra8** [comment]
Hmm, I was using the latest version (got it from huds.tf). Using the latest version from github and verifying my game files also didn't change anything. This is what I see:

![download](https://user-images.githubusercontent.com/42025133/84252137-c9326080-ab40-11ea-89e1-785ce9de6b7b.jpg)

**Comment by CriticalFlaw** [comment]
Oh I forgot. If you have minmode enabled (in advanced options) a different style for item meters is used. Turning that off will go to the style that doesn't have this issue but i'll get it fixed in the next version

**Comment by tetra8** [comment]
Oh alright. Thanks then :)

**Comment by CriticalFlaw** [comment]
Fixed. Please download the latest version from GitHub.
