### ISSUE TITLE
How to change net_graph width?

### ISSUE THREAD

**Issue by ghost** [CriticalFlaw/flawhud#94]
Is there a way where I can change the width? Lerp value sometimes get overlapped. On 1024x768 resolution.
![image](https://user-images.githubusercontent.com/34733116/84838624-beb81100-afef-11ea-88e5-1a60212d87ab.png)

Also huntsman charge meter not aligned lol
![image](https://user-images.githubusercontent.com/34733116/84839099-0be8b280-aff1-11ea-9a8d-b86d664de686.png)

**Comment by CriticalFlaw** [comment]
Not sure about making it wider, but you can try using the following cvars and see if it helps move the net_graph to fix the overlap.

- `net_graphproportionalfont "1"`
- `net_graphpos "2"`

**Comment by ghost** [comment]
> Not sure about making it wider, but you can try using the following cvars and see if it helps move the net_graph to fix the overlap.
> 
> * `net_graphproportionalfont "1"`
> * `net_graphpos "2"`

Did not work unfortunately

**Comment by CriticalFlaw** [comment]
Unfortunately I don't think there is a way to make it wider. You'd have to play around with the font definitions in `resource/sourchscheme.res`
