### ISSUE TITLE
Payload Race and Medic Spectating Bugs

### ISSUE THREAD

**Issue by h9lk** [CriticalFlaw/flawhud#95]
In payload race can't see when red team cap pl, number of "cap" people isn't visible

![20200621223121_1](https://user-images.githubusercontent.com/32390006/85276617-c9a8f080-b48a-11ea-8e16-5aad5010a41c.jpg)

when u start spectate on medic - his nickname just blocks name of patient

![20200621170838_1](https://user-images.githubusercontent.com/32390006/85276766-0248ca00-b48b-11ea-92b4-77c6c8fed806.jpg)

**Comment by CriticalFlaw** [comment]
Fixed in the latest version (v2020.0704) available on GitHub.

**Comment by h9lk** [comment]
@CriticalFlaw  think it's 4:3 1024x768 problem?

![20200717132504_1](https://user-images.githubusercontent.com/32390006/87782407-16d67300-c83b-11ea-9429-44430c30b538.jpg)

![20200717140634_1](https://user-images.githubusercontent.com/32390006/87782475-37063200-c83b-11ea-9e98-e13d839353e6.jpg)
