### ISSUE TITLE
"Self Aware Beauty Mark" Preview bug 

### ISSUE THREAD

**Issue by lieutenantnightly** [CriticalFlaw/flawhud#96]
When using the Self Aware Beauty Mark, the preview for it breaks in your backpack loadout screen and preview ingame. - https://imgur.com/a/6FFKnE8

**Comment by CriticalFlaw** [comment]
This a game bug and cannot be fixed through the HUD.

**Comment by lieutenantnightly** [comment]
> This a game bug and cannot be fixed through the HUD.

alrighty!
